//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:46.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/reader/multi_reader_status.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID MULTI_READER_STATUS_INTF_ID = { daq::IMultiReaderStatus::Id.Data1, daq::IMultiReaderStatus::Id.Data2, daq::IMultiReaderStatus::Id.Data3, daq::IMultiReaderStatus::Id.Data4_UInt64 };

ErrCode MultiReaderStatus_getEventPackets(MultiReaderStatus* self, Dict** eventPackets)
{
    return reinterpret_cast<daq::IMultiReaderStatus*>(self)->getEventPackets(reinterpret_cast<daq::IDict**>(eventPackets));
}

ErrCode MultiReaderStatus_getMainDescriptor(MultiReaderStatus* self, EventPacket** descriptor)
{
    return reinterpret_cast<daq::IMultiReaderStatus*>(self)->getMainDescriptor(reinterpret_cast<daq::IEventPacket**>(descriptor));
}

ErrCode MultiReaderStatus_createMultiReaderStatus(MultiReaderStatus** obj, EventPacket* mainDescriptor, Dict* eventPackets, Bool valid, Number* offset)
{
    daq::IMultiReaderStatus* ptr = nullptr;
    ErrCode err = daq::createMultiReaderStatus(&ptr, reinterpret_cast<daq::IEventPacket*>(mainDescriptor), reinterpret_cast<daq::IDict*>(eventPackets), valid, reinterpret_cast<daq::INumber*>(offset));
    *obj = reinterpret_cast<MultiReaderStatus*>(ptr);
    return err;
}
