//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:38.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/reader/packet_reader.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID PACKET_READER_INTF_ID = { daq::IPacketReader::Id.Data1, daq::IPacketReader::Id.Data2, daq::IPacketReader::Id.Data3, daq::IPacketReader::Id.Data4_UInt64 };

ErrCode PacketReader_read(PacketReader* self, Packet** packet)
{
    return reinterpret_cast<daq::IPacketReader*>(self)->read(reinterpret_cast<daq::IPacket**>(packet));
}

ErrCode PacketReader_readAll(PacketReader* self, List** packets)
{
    return reinterpret_cast<daq::IPacketReader*>(self)->readAll(reinterpret_cast<daq::IList**>(packets));
}

ErrCode PacketReader_createPacketReader(PacketReader** obj, Signal* signal)
{
    daq::IPacketReader* ptr = nullptr;
    ErrCode err = daq::createPacketReader(&ptr, reinterpret_cast<daq::ISignal*>(signal));
    *obj = reinterpret_cast<PacketReader*>(ptr);
    return err;
}

ErrCode PacketReader_createPacketReaderFromPort(PacketReader** obj, InputPortConfig* port)
{
    daq::IPacketReader* ptr = nullptr;
    ErrCode err = daq::createPacketReaderFromPort(&ptr, reinterpret_cast<daq::IInputPortConfig*>(port));
    *obj = reinterpret_cast<PacketReader*>(ptr);
    return err;
}
