//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:40.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/reader/reader_status.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID READER_STATUS_INTF_ID = { daq::IReaderStatus::Id.Data1, daq::IReaderStatus::Id.Data2, daq::IReaderStatus::Id.Data3, daq::IReaderStatus::Id.Data4_UInt64 };

ErrCode ReaderStatus_getReadStatus(ReaderStatus* self, ReadStatus* status)
{
    return reinterpret_cast<daq::IReaderStatus*>(self)->getReadStatus(reinterpret_cast<daq::ReadStatus*>(status));
}

ErrCode ReaderStatus_getEventPacket(ReaderStatus* self, EventPacket** packet)
{
    return reinterpret_cast<daq::IReaderStatus*>(self)->getEventPacket(reinterpret_cast<daq::IEventPacket**>(packet));
}

ErrCode ReaderStatus_getValid(ReaderStatus* self, Bool* valid)
{
    return reinterpret_cast<daq::IReaderStatus*>(self)->getValid(valid);
}

ErrCode ReaderStatus_getOffset(ReaderStatus* self, Number** offset)
{
    return reinterpret_cast<daq::IReaderStatus*>(self)->getOffset(reinterpret_cast<daq::INumber**>(offset));
}

ErrCode ReaderStatus_createReaderStatus(ReaderStatus** obj, EventPacket* eventPacket, Bool valid, Number* offset)
{
    daq::IReaderStatus* ptr = nullptr;
    ErrCode err = daq::createReaderStatus(&ptr, reinterpret_cast<daq::IEventPacket*>(eventPacket), valid, reinterpret_cast<daq::INumber*>(offset));
    *obj = reinterpret_cast<ReaderStatus*>(ptr);
    return err;
}
