/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <condition_variable>
#include <filesystem>
#include <memory>
#include <mutex>
#include <queue>
#include <thread>

#include <opendaq/opendaq.h>

#include <basic_csv_recorder_module/common.h>
#include <basic_csv_recorder_module/csv_writer.h>

BEGIN_NAMESPACE_OPENDAQ_BASIC_CSV_RECORDER_MODULE

/*!
 * A worker thread which records packet data to a CSV file. The worker is implemented as a
 * producer/consumer queue. The caller is the producer, enqueuing packets to be recorded. The
 * caller is then free to proceed with other activities. The background thread is the consumer,
 * dequeuing packets and recording them to the CSV file.
 *
 * If an I/O or data processing error occurs, the CSV file is closed, and all future packets
 * are ignored. A warning message is logged to the console.
 */
class BasicCsvRecorderThread
{
    public:

        /*!
         * Opens a CSV file for the specified signal, and launches a worker thread in the
         * background.
         *
         * @param path The directory in which to open a CSV file for this signal. The filename
         *     is generated by sanitizing the @p signal object's global ID and appending a ".csv"
         *     suffix.
         * @param signal The openDAQ signal object to be recorded.
         */
        BasicCsvRecorderThread(
            std::filesystem::path path,
            const SignalPtr& signal,
            const LoggerComponentPtr& loggerComponent);

        /*!
         * Stops the worker thread and closes the CSV file.
         */
        ~BasicCsvRecorderThread();

        /*!
         * Enqueues a packet (either an event packet or a data packet) to be recorded. A reference
         * to this packet object will be held internally in the work queue. The reference is
         * released when the worker thread has recorded the data or when this object is destroyed.
         *
         * @param packet The packet to record.
         */
        void post(const PacketPtr& packet);

    private:

        void threadMain();

        /*!
         * @brief Records the values a packet to the CSV file.
         *
         * @param packet The packet received.
         *
         * @throws std::ios_base::failure A data line could not be written to the CSV file due to
         *     an I/O error.
         */
        void onPacketReceived(const PacketPtr& packet);

        /*!
         * @brief Responds to input port events.
         *
         * The first descriptor-change event received causes headers to be written to the CSV
         * file, if they have not already been written. Subsequent descriptor-change events, or
         * descriptor-change events when headers have already been written, cause the CSV file
         * to be closed, because descriptor changes during recording are not supported. All other
         * event types are ignored.
         *
         * @param packet The event packet.
         *
         * @throws std::ios_base::failure A header line could not be written to the CSV file due
         *     to an I/O error.
         */
        void onEventPacketReceived(const EventPacketPtr packet);

        /*!
         * @brief Records the values the specified packet to the CSV file.
         *
         * @todo Templated writer functions are selected based on the packet's sample type. This
         *     involves inspecting the descriptor for every packet. This could be optimized by
         *     inspecting the descriptor only when it changes, and caching pointers to the
         *     appropriate writer function.
         *
         * @param packet The data packet to record.
         *
         * @throws std::ios_base::failure A data line could not be written to the CSV file due to
         *     an I/O error.
         */
        void onDataPacketReceived(const DataPacketPtr packet);

        /*!
         * @brief Writes headers to the CSV file, or closes the file if headers were already
         *     written.
         *
         * @param descriptor The data descriptor of the value signal.
         * @param domainDescriptor The data descriptor of the domain signal.
         *
         * @throws std::ios_base::failure The header line could not be written to the CSV file due
         *     to an I/O error.
         */
        void tryWriteHeaders(const DataDescriptorPtr& descriptor, const DataDescriptorPtr& domainDescriptor);

        LoggerComponentPtr loggerComponent;

        std::unique_ptr<CsvWriter> writer;
        bool headersWritten = false;

        std::mutex mutex;
        std::condition_variable cv;

        std::queue<PacketPtr> queue;

        std::thread thread;
};

END_NAMESPACE_OPENDAQ_BASIC_CSV_RECORDER_MODULE
