//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:12.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

    typedef struct AddressInfoBuilder AddressInfoBuilder;
    typedef struct AddressInfo AddressInfo;
    typedef struct String String;

    EXPORTED extern const IntfID ADDRESS_INFO_BUILDER_INTF_ID;

    ErrCode EXPORTED AddressInfoBuilder_build(AddressInfoBuilder* self, AddressInfo** address);
    ErrCode EXPORTED AddressInfoBuilder_getAddress(AddressInfoBuilder* self, String** address);
    ErrCode EXPORTED AddressInfoBuilder_setAddress(AddressInfoBuilder* self, String* address);
    ErrCode EXPORTED AddressInfoBuilder_getConnectionString(AddressInfoBuilder* self, String** connectionString);
    ErrCode EXPORTED AddressInfoBuilder_setConnectionString(AddressInfoBuilder* self, String* connectionString);
    ErrCode EXPORTED AddressInfoBuilder_getType(AddressInfoBuilder* self, String** type);
    ErrCode EXPORTED AddressInfoBuilder_setType(AddressInfoBuilder* self, String* type);
    ErrCode EXPORTED AddressInfoBuilder_getReachabilityStatus(AddressInfoBuilder* self, AddressReachabilityStatus* addressReachability);
    ErrCode EXPORTED AddressInfoBuilder_setReachabilityStatus(AddressInfoBuilder* self, AddressReachabilityStatus addressReachability);
    ErrCode EXPORTED AddressInfoBuilder_createAddressInfoBuilder(AddressInfoBuilder** obj);

#ifdef __cplusplus
}
#endif
