//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    /*!
     * @brief This class manages the lock state of an object, usually a device. A device can be locked either with a specific user or without one. If the device is locked with a specific user, only that user can unlock it. If the device is locked without a user, any user can unlock it.
     */
    DAQ_EXTENDS_INTERFACE(daqUserLock, daqBaseObject);

    typedef struct daqUserLock daqUserLock;
    typedef struct daqUser daqUser;

    EXPORTED extern const daqIntfID DAQ_USER_LOCK_INTF_ID;
    void EXPORTED daqUserLock_getInterfaceId(daqIntfID* intfId);

    /*!
     * @brief Lock the object. Only the user who locked the object can unlock it. If the object was locked without a specific user, or with an anonymous user, any user can unlock it.
     * @param user User performing the lock action.
     */
    daqErrCode EXPORTED daqUserLock_lock(daqUserLock* self, daqUser* user DAQ_DEFAULT_VALUE(nullptr));

    /*!
     * @brief Unlock the object. Only the user who locked the object can unlock it. If the object was locked without a specific user, or with an anonymous user, any user can unlock it.
     * @param user User performing the unlock action.
     */
    daqErrCode EXPORTED daqUserLock_unlock(daqUserLock* self, daqUser* user DAQ_DEFAULT_VALUE(nullptr));

    /*!
     * @brief Forcefully unlock the object. A force unlock will always succeed, regardless of which user initially locked the object.
     */
    daqErrCode EXPORTED daqUserLock_forceUnlock(daqUserLock* self);

    /*!
     * @brief Returns true if the object is locked.
     * @param isLockedOut[out] True if the object is locked.
     */
    daqErrCode EXPORTED daqUserLock_isLocked(daqUserLock* self, daqBool* isLockedOut);

    /*!
     * @brief Creates an unlocked UserLock object.
     */
    daqErrCode EXPORTED daqUserLock_createUserLock(daqUserLock** obj);

#ifdef __cplusplus
}
#endif
