//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 18.08.2025 07:22:30.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/server/server.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_SERVER_INTF_ID = { daq::IServer::Id.Data1, daq::IServer::Id.Data2, daq::IServer::Id.Data3, daq::IServer::Id.Data4_UInt64 };

daqErrCode daqServer_stop(daqServer* self)
{
    return reinterpret_cast<daq::IServer*>(self)->stop();
}

daqErrCode daqServer_getId(daqServer* self, daqString** serverId)
{
    return reinterpret_cast<daq::IServer*>(self)->getId(reinterpret_cast<daq::IString**>(serverId));
}

daqErrCode daqServer_enableDiscovery(daqServer* self)
{
    return reinterpret_cast<daq::IServer*>(self)->enableDiscovery();
}

daqErrCode daqServer_getSignals(daqServer* self, daqList** signals, daqSearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IServer*>(self)->getSignals(reinterpret_cast<daq::IList**>(signals), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

daqErrCode daqServer_getStreaming(daqServer* self, daqStreaming** streaming)
{
    return reinterpret_cast<daq::IServer*>(self)->getStreaming(reinterpret_cast<daq::IStreaming**>(streaming));
}
