//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/utility/device_update_options.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_DEVICE_UPDATE_OPTIONS_INTF_ID = { daq::IDeviceUpdateOptions::Id.Data1, daq::IDeviceUpdateOptions::Id.Data2, daq::IDeviceUpdateOptions::Id.Data3, daq::IDeviceUpdateOptions::Id.Data4_UInt64 };

void daqDeviceUpdateOptions_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_DEVICE_UPDATE_OPTIONS_INTF_ID;
}

daqErrCode daqDeviceUpdateOptions_getLocalId(daqDeviceUpdateOptions* self, daqString** localId)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getLocalId(reinterpret_cast<daq::IString**>(localId));
}

daqErrCode daqDeviceUpdateOptions_getManufacturer(daqDeviceUpdateOptions* self, daqString** manufacturer)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getManufacturer(reinterpret_cast<daq::IString**>(manufacturer));
}

daqErrCode daqDeviceUpdateOptions_getSerialNumber(daqDeviceUpdateOptions* self, daqString** serialNumber)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getSerialNumber(reinterpret_cast<daq::IString**>(serialNumber));
}

daqErrCode daqDeviceUpdateOptions_getConnectionString(daqDeviceUpdateOptions* self, daqString** connectionString)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

daqErrCode daqDeviceUpdateOptions_setNewManufacturer(daqDeviceUpdateOptions* self, daqString* manufacturer)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->setNewManufacturer(reinterpret_cast<daq::IString*>(manufacturer));
}

daqErrCode daqDeviceUpdateOptions_getNewManufacturer(daqDeviceUpdateOptions* self, daqString** manufacturer)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getNewManufacturer(reinterpret_cast<daq::IString**>(manufacturer));
}

daqErrCode daqDeviceUpdateOptions_setNewSerialNumber(daqDeviceUpdateOptions* self, daqString* serialNumber)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->setNewSerialNumber(reinterpret_cast<daq::IString*>(serialNumber));
}

daqErrCode daqDeviceUpdateOptions_getNewSerialNumber(daqDeviceUpdateOptions* self, daqString** serialNumber)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getNewSerialNumber(reinterpret_cast<daq::IString**>(serialNumber));
}

daqErrCode daqDeviceUpdateOptions_setNewConnectionString(daqDeviceUpdateOptions* self, daqString* connectionString)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->setNewConnectionString(reinterpret_cast<daq::IString*>(connectionString));
}

daqErrCode daqDeviceUpdateOptions_getNewConnectionString(daqDeviceUpdateOptions* self, daqString** connectionString)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getNewConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

daqErrCode daqDeviceUpdateOptions_setNewLocalId(daqDeviceUpdateOptions* self, daqString* localId)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->setNewLocalId(reinterpret_cast<daq::IString*>(localId));
}

daqErrCode daqDeviceUpdateOptions_getNewLocalId(daqDeviceUpdateOptions* self, daqString** localId)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getNewLocalId(reinterpret_cast<daq::IString**>(localId));
}

daqErrCode daqDeviceUpdateOptions_getUpdateMode(daqDeviceUpdateOptions* self, daqDeviceUpdateMode* mode)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getUpdateMode(reinterpret_cast<daq::DeviceUpdateMode*>(mode));
}

daqErrCode daqDeviceUpdateOptions_setUpdateMode(daqDeviceUpdateOptions* self, daqDeviceUpdateMode mode)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->setUpdateMode(static_cast<daq::DeviceUpdateMode>(mode));
}

daqErrCode daqDeviceUpdateOptions_getChildDeviceOptions(daqDeviceUpdateOptions* self, daqList** childDeviceOptions)
{
    return reinterpret_cast<daq::IDeviceUpdateOptions*>(self)->getChildDeviceOptions(reinterpret_cast<daq::IList**>(childDeviceOptions));
}

daqErrCode daqDeviceUpdateOptions_createDeviceUpdateOptions(daqDeviceUpdateOptions** obj, daqString* setupString)
{
    daq::IDeviceUpdateOptions* ptr = nullptr;
    daqErrCode err = daq::createDeviceUpdateOptions(&ptr, reinterpret_cast<daq::IString*>(setupString));
    *obj = reinterpret_cast<daqDeviceUpdateOptions*>(ptr);
    return err;
}
