= Glossary

[#daq]
== DAQ
An acronym for **D**ata **A**c**q**uisition.

[#component]
== Component
A name for <<DAQ>> elements that share some common functionality.
An example of these components are <<device>>, <<function_block>>, <<channel>> and <<signal>>.

[#folder]
== Folder
An element that <<component>>s use to organize the children <<component>>s.

[#device]
== Device

An openDAQ(TM) device represents a container of <<channel>>s, <<function_block>>s, <<signal>>s, and other child devices.
openDAQ(TM) Devices can be split into three categories, with each Device being part of one or more of them.

* *Physical device* used for measuring data and is used to represent data acquisition hardware in openDAQ(TM).
* *Client device* used to connect to another device, adding them below itself in the device hierarchy.
It forms a parent-child relationship between itself and the connected-to devices.
* *Function Block device* that defines data processing entities called <<function_block>>s.
These can generate, process and output data as <<signal>>s.
Here device acts as a parent of zero-or-more <<function_block>>s, and allows for their creation / removal / configuration.

Each Device also has a Device Info object containing information about it, such as its name and manufacturer.

// TODO: Add explanation of architecture

[#domain]
== Domain
Domain is a reference to a point where a <<sample>> was acquired.
In most cases, this is time but can also be something else, for example, frequency, angle, revolution or distance.

[#signal]
== Signal

A Signal is used to form connections between data producers and consumers (<<device>>s, <<channel>>s, and <<function_block>>s).
It carries data in the form of <<data_packet,Packets>> and describes the form of the data with a <<data_descriptor>>.

Signals can have a reference to another Signal that provides its domain data.
The domain data is used to align the samples and determine the distance between them.
Most often, openDAQ(TM) signals use the time domain.
In that case, a signal carrying measurement data will have a time signal as its domain signal, which provides the timestamps of each measured value.

[#sample]
== Sample
A discrete value of a signal at some domain point (usually time).

[#data_packet]
== Data Packet

Data packets are used to forward data from a <<signal>> through a <<connection>>, and into an <<input_port>>.
They contain a pointer to a data buffer and a reference to a <<data_descriptor>>, describing the format of the data.
Data packets have a specialization called Value packets.
Value packets, in addition to the aforementioned, contain a pointer to another Data packet containing domain (most often time) data samples.

If packet data is _implicit_ (calculated), the buffer is `null`, and the value of each sample is calculated using the
signal's <<data_rule>>, given a packet offset.Each Data packet with an implicit rule contains a Packet offset.

// TODO: Remove value packet explanation once merged with data packet 

[#event_packet]
== Event Packet

Event packets are used to signalize to listeners that an event happened.
They're passed through a <<signal>> in the same way as <<data_packet>>s.
They contain an event id, and a dictionary payload containing key-value pairs relevant to a specific event.

[#descriptor_changed]
A common event in openDAQ(TM) is the _Signal-descriptor-changed_ event, which notifies all listeners that the <<signal>>'s description has been changed.

* xref:background_info:packets.adoc#event_packet[More in the architecture section]

[#data_descriptor]
== Data Descriptor

Contains information about the <<signal>> data format such as sample type.
Each <<signal>> has a data descriptor.
When said descriptor is changed, each signal listener is notified of the change with an event packet.

Allows anyone receiving <<signal>> data to interpret the <<data_packet,Packet>> data buffers.

The Data Descriptor contains information required to interpret and read the value of a single sample in a <<data_packet>>'s
buffer.
It contains information about the sample type (int, double, byte,...), whether the sample is a scalar, vector, or matrix, as well as other necessary information.

The data descriptor is immutable, and can only be replaced in whole - its fields can't be altered individually once assigned to a signal.

In special cases when complex data structures are sent via the <<signal>>, the Data descriptor can contain a list of Data descriptors as Struct fields.
When this list is configured, the samples in a <<data_packet>> of the <<signal>> are composed of multiple types of data (each described by a Data Descriptor in the aforementioned list), aligned consecutively in the data buffer.

[#data_rule]
== Data Rule

Part of the <<data_descriptor>>.
Defines whether the values contained in the <<signal>>'s <<data_packet>>s are present in the buffer, or calculated via a rule and packet offset.
The Packet offset is contained in every packet with a _non-explicit_ rule.

* If the Data rule is _explicit_, samples are found as part of the data buffer.
* If the Data rule is _linear_, or _constant_, the buffer is `null`, and each sample is calculated with a given packet offset
(the packet offset is available in every <<data_packet>> when required for the rule calculation):
** *Linear rule*: `Sample value = Packet offset + Index * Delta + Start`; Where `Index` is the index of the sample in a
packet. `Delta` and `Start` are given by the Data rule.
** *Constant rule*: `Sample value = Constant`; Where `Constant` is given by the Data rule.

== Post-scaling

Part of the <<data_descriptor>>.
Defines a scaling rule which is applied to a <<data_packet>>'s samples when read.
When present, the <<data_packet>>s contain raw, unscaled values in their buffers, and are scaled as defined by the Scaling rule when they're first read.

openDAQ(TM) defines a *Linear scaling rule*, which scales samples as follows:
----
Sample value = Raw value * Delta + Offset
----
Where `Delta` and `Offset` are given by the Scaling rule.

Post-scaling is most often used to reduce bandwidth requirements by outputting data in a smaller data format, such as
`Int32`, then scaling it on the client side into `Double` precision values.

== Dimension

<<data_descriptor>>s contain a list of Dimensions.
The number of Dimensions defines the rank of the data.
For example, if a <<data_descriptor>> has no Dimensions, a sample is composed of a __single__ value.
If it has 1 Dimension, a sample is composed of an __array__ of values.
If it has 2, a sample is a __matrix__ of values.

The Dimension itself contains information about its size.
The definition is in row-major order, so e.g., 2 dimensions of size 10 and 20 would represent a matrix with 10 rows and 20 columns.

Additionally, it can assign custom labels to each Dimension, defining the row/column width. A vector with Dimension labels
`[0, 2, 4, 6, 8]` specifies that each value in the vector is a distance of 2 units apart.

[#unit]
== Unit

Describes a physical unit of measurement, as defined in 
https://unece.org/trade/cefact/UNLOCODE-Download[Codes for Units of Measurement used in International Trade].
openDAQ(TM) defines the ID, symbol, name, and quantity fields for each of its units.

[#tick_resolution]
== Tick resolution and Origin

The tick resolution and origin are most often used to scale domain data from ticks to a given physical unit. The
Resolution defines a ratio multiplier, while the origin defines a starting point in the domain to which a domain
sample value is added to obtain the absolute domain value. A `tick` represents an integer value that is available
in domain <<data_packet>>s, representing an unscaled domain data value.

:iso-8601-url: https://www.iso.org/iso-8601-date-and-time-format.html

For example, when using the time domain, the Origin represents an epoch, most often represented as a string
according to the {iso-8601-url}[ISO 8601 standard]. Let's consider an example
with the UNIX epoch:

* Origin = `"1970-01-01T00:00:00Z"`
* Resolution = `1 / 1000000`
* Unit = `"s"` (seconds)
* Sample value in ticks = `1676464831000000`

We calculate the relative timestamp in seconds as `Value * Resolution` ->
`1676464831000000 * (1 / 1000000) = 1676464831`, yielding the timestamp in seconds.

Converting the result into the {iso-8601-url}[ISO 8601 standard], and adding it to the Origin, we obtain the following
absolute time value: `"2023-02-15T12:40:31Z"`, or `15th February 2023, 12h 40m 31s`.

[#function_block]
== Function Block

Data processing objects that are used to generate, process, and/or output data.
They define zero-or-more <<input_port>>s to which input <<signal>>s are connected.
They process inputs or generate their own data, usually outputting it either to their output <<signal>>s, or some other sink such as a file.

Function blocks are themselves a <<property_object>>.
They contain a set of <<property,Properties>> and corresponding <<property_value>>s that can be adjusted to modify the behavior of the Function Block.

Examples of Function Blocks:

* *Statistics* calculates statistics of its inputs, outputting averaged and rms signals
* *Signal Generator* outputs simulated sine waves
* *File Writer* writes input signal data into text files

.Function blocks with different combinations of input ports and output signals
image::opendaq:getting_started:function-block-types.svg[Function Blocks,align="center"]

Some more complex Function Blocks might have Function Blocks nested within them, to provide a better representation of hierarchical <<property,Properties>>, <<signal>>s, and <<input_port, Ports>>.
For example, a __File Writer__ Function Block might have a nested __Trigger__ Function Block that specifies trigger conditions on when <<signal>> data should be written to a file.

* xref:background_info:function_blocks.adoc[More in the architecture section]

[#channel]
== Channel

Specialization of a <<function_block>> that represents a channel on physical hardware. openDAQ(TM) physical <<device>>s contain a list of channels.
Examples might include channels representing Analog inputs / outputs and CAN buses.

* xref:background_info:function_blocks.adoc#channel[More in the architecture section]

[#input_port]
== Input Port

A <<signal>> can be connected to an input port forming a <<connection>> between the two of them.
Whenever a packet is sent by the <<signal>>, it is added to a queue of <<data_packet,packets>> (the <<connection>> object) and can be read by the owner of the Input Port.

An Input Port can specify a callback method, which determines whether a <<signal>> is compatible with the port.
If it is not, the <<signal>> can't be connected.

Input Ports are most often used by <<function_block>>s to obtain input data to process and <<reader>>s which read data sent by <<signal>>s.

* xref:background_info:function_blocks.adoc#input_port[More in the architecture section]

[#connection]
== Connection

Represents a connection between a <<signal>> and an <<input_port>>.
In openDAQ(TM), a Connection is an object holding a FIFO (first in, first out) queue of <<data_packet,Packets>>.
Any <<data_packet,Packet>> sent by a <<signal>> is added to the queues of all Connections formed with the <<signal>>.

[#reader]
== Reader

Used to read data sent by <<signal>>s.
Readers connect to <<signal>>s and provide an easy way of reading signal data in openDAQ(TM).

openDAQ(TM) provides different types of readers that can be used depending on user requirements:

* xref:background_info:readers.adoc#packet_reader[*Packet reader*] reads one-or-more packets at a time
* xref:background_info:readers.adoc#stream_reader[*Stream reader*] reads data as a stream of values, merging data packets into a continuous data buffer.
* xref:background_info:readers.adoc#tail_reader[*Tail reader*] reads the last n values output by the signal.
* xref:background_info:readers.adoc#block_reader[*Block reader*] reads the data in predefined block size and can't read less than a full block.
* xref:background_info:readers.adoc#multi_reader[*Multi reader*] reads aligned data from multiple signals.

// split from the above list
* xref:background_info:readers.adoc[More in the architecture section]

[#property_object]
== Property Object

Property Objects act as containers of <<property,Properties>> and their corresponding <<property_value,value>>s.
Each Property-Value pair is joined by a string key that is unique within a Property Object - the <<property>>'s **name**.
In this pairing, the <<property>> provides meta information that restricts the <<property_value,value>>, defines its default value, and provides insight on how to interpret it.

In openDAQ(TM), <<device>>s, <<channel>>s, and <<function_block>>s are Property Objects.
They define a set of <<property,Properties>> with default values.
Adjusting the <<property_value,value>>s of said <<property,Properties>> allows users to configure their behavior.

[#property]
== Property

A Property describes the metadata of a property that is part of a <<property_object>>.
It defines what value its corresponding <<property_value>> can hold, as well as other characteristics.

Examples of Property metadata fields:

* *Name*: The name of the property.The Property is linked to a <<property_value,value>> via the name field.
* *Visible*: If `false`, the property is not visible from outside the object.
* *Read-only*: If `true`, the property value can't be modified.

[#property_value]
== Property Value

The value of a <<property>>.
It can be obtained from a <<property_object>>, using its name as the getter parameter.
Conversely, a <<property_value>> can be modified on a <<property_object>> in the same manner but using the setter function.

If the <<property_value>> has not been explicitly configured, it will return the default value of the corresponding <<property>>.

A Property Value can't be set unless a corresponding <<property>> is added to the <<property_object>>.

[#context]
== Context
The Context serves as an "environment" context and contains the <<scheduler>> and <<logger>>.
It originates at the <<instance>>, and is passed to the <<root_device>>, which forwards it to <<component>>s such as <<function_block>>s and <<signal>>s.

[#scheduler]
== Scheduler
A thread-pool scheduler that supports scheduling execution of one-off functions as well as dependency graphs.

[#logger]
== Logger
Provides the ability for disparate components to record information on events and their severity.
This can be output on the console, written to a file or otherwise displayed to the user.

[#instance]
== Instance

The Instance is the entry point object to every openDAQ(TM) application.
On creation, it initializes a xref:opendaq:background_info:modules.adoc[Module Manager] that loads all available modules from a specified directory (and its subdirectories).
By default, it creates a standard openDAQ(TM) <<root_device>>, which allows access to all loaded <<module>> capabilities (adding <<function_block>>s, adding <<device>>s, starting xref:glossary.adoc#opendaq_opcua_server_module[Servers]).

The openDAQ(TM) Instance forwards all <<device>> function calls to its Root Device.

[#root_device]
== Root device

The top-level <<device>> in the openDAQ(TM) <<device>> hierarchy.
It is the <<device>> that is directly accessed when calling <<device>> functions on the <<instance>>.
When an <<instance>> is constructed, it creates a default root device.
That <<device>>, when doing actions such as adding a <<device>>, or enumerating available <<device>>s, iterates through all loaded xref:glossary.adoc#module[Modules] and asks them whether they can add a given <<device>> or what <<function_block>>s they have available.

When an <<instance>> (device) hosts an xref:glossary.adoc#opendaq_opcua_server_module[OPC UA Server], any client connecting to it will see the <<device>>'s structure, starting with the Root Device at the top.

[#module]
== Module

A Module is usually a dynamically loaded library that provides a set of <<function_block>>s, servers, and supported <<device>> types.
It can be asked to add a provided <<function_block>> / server to an openDAQ(TM) application, and to connect to a <<device>>.

Not all modules provide each of these. 
For example, openDAQ(TM) provides:

* `opcua_client_module`,`native_stream_cl_module` and `ws_stream_cl_module` which allow for connecting to <<device>>s.
* `opcua_server_module` which allows for setting up a server that advertises <<device>> structure.
* `native_stream_srv_module` which allows for setting up a server that advertises <<device>> structure, <<signal>>s and stream <<device>> data.
* `ws_stream_srv_module` which allows for setting up a server that advertises <<device>> <<signal>>s and stream <<device>> data.

[#device_discovery]
== Device discovery

// TODO: Fix caps=TMS once changed

:mdns-wiki: https://en.wikipedia.org/wiki/Multicast_DNS

When enumerating available <<device>>s, each <<module>> is queried for what <<device>>s it can connect to / create.
This is done with the <<module>>'s provided discovery mechanism.
The openDAQ(TM) xref:glossary.adoc#opendaq_opcua_client_module[OPC-UA Client Module], xref:glossary.adoc#opendaq_native_client_module[Native Streaming Module] and
xref:glossary.adoc#opendaq_streaming_lt_client_module[Streaming LT Client Module] use a {mdns-wiki}[mDNS] query to discover all supported devices on the network.
Those <<device>>s are assumed to be running a {mdns-wiki}[mDNS] discovery service, 
advertising the `_opcua-tcp._tcp.local.` service, with a `TXT` record entry of `caps=TMS` if device is openDAQ(TM) OPC UA-supported,
a {mdns-wiki}[mDNS] discovery service, advertising the `_opendaq-streaming-native._tcp.local.` service, with a `TXT` record entry of `caps=OPENDAQ_NS` if device is Native-streaming-supported.
and a {mdns-wiki}[mDNS] discovery service, advertising the `_streaming-lt._tcp.local.` service, with a `TXT` record entry of `caps=LT` if device is Websocket-streaming-supported.

[#opc_foundation]
== OPC Foundation
:opc-foundation-website: https://opcfoundation.org

The {opc-foundation-website}[OPC Foundation] (Open Platform Communications) is an industry consortium that creates and maintains standards for open connectivity of industrial automation devices and systems, such as industrial control systems and process control generally.

[#opc_ua]
== OPC-UA
:opcua-website: https://opcfoundation.org/about/opc-technologies/opc-ua/
:iec-opcua: https://webstore.iec.ch/publication/61114

{opcua-website}[OPC Unified Architecture (OPC UA)] is a cross-platform, open-source, {iec-opcua}[IEC62541 standard] for data exchange from sensors to cloud applications developed by the <<opc_foundation>>.

[#opendaq_opcua]
== openDAQ(TM) OPC UA standard

// suppress inspection "GrazieInspection"
A test-and-measurement standard that describes openDAQ devices based on the OPC UA for devices standard.
It is a protocol that describes the structure of a <<device>>.
The openDAQ(TM) xref:glossary.adoc#opendaq_opcua_client_module[OPC-UA Client Module] can connect to <<device>>s that adhere to this protocol.

[#opendaq_opcua_server_module]
== OPC-UA Server Module

Allows for the creation of an OPC UA server on an openDAQ(TM) <<instance>>.
It publishes the structure of the <<root_device>> and all its descendants (other <<device>>s and <<function_block>>s), and allows for changing the <<property_value>>s of all the structures from a remote client.

The structure is as of this moment locked to the state it is when the Server is created.
If a new <<function_block>>, <<device>>, <<channel>>, or other <<component>> is added, the Server doesn't yet react to that change.

[#opendaq_opcua_client_module]
== OPC-UA Client Module

Allows for connecting to xref:glossary.adoc#opendaq_opcua[openDAQ(TM) OPC UA]-enabled devices running an OPC UA server.
It reads the structure of the remote <<device>> and mirrors it as a sub-device.
Settings changed on the <<device>> mirror are also changed on the actual <<device>> itself.

The openDAQ(TM) OPC-UA Client <<module>> also can use xref:glossary.adoc#opendaq_native_client_module[openDAQ(TM) Native Client Module]
and xref:glossary.adoc#opendaq_streaming_lt_client_module[openDAQ(TM) Streaming LT Client Module]
to connect to the server component created by the corresponding Streaming Server Module.
Doing so enables transferring <<data_packet>>s from server <<signal>>s into client xref:glossary.adoc#device[Signals].

[#opendaq_streaming_lt_server_module]
== Streaming LT Server Module

// suppress inspection "GrazieInspection"
Allows for the creation of a web-socket streaming-lt server on an <<instance>>.
It publishes <<device>> <<signal>>s and streams <<device>> data.

[#opendaq_streaming_lt_client_module]
== Streaming LT Client Module

Allows for connecting to <<device>>s running a web-socket streaming-lt server.

The openDAQ(TM) Streaming LT Client Module enables its own web-socket streaming client, which connects
to the server component created by the xref:glossary.adoc#opendaq_streaming_lt_server_module[openDAQ(TM) Streaming LT Server Module].
Doing so reads server signals and transfers data packets from server signals into client signals.

The openDAQ(TM) Streaming LT Client Module allows to read the list of all signals of
the remote <<device>> and mirror these as a flat list as if owned by a "pseudo" local <<device>>.
This "Pseudo" <<device>> does not mirror <<channel>>s or <<function_block>>s of the remote <<device>>s,
and does not provide a mechanism to change settings of the remote <<device>>.

[#streaming_lt_protocol]
== openDAQ(TM) Streaming LT protocol

The data transfer protocol used by openDAQ(TM) to publish <<device>> available <<signal>>s and send data from <<device>>s running an
xref:glossary.adoc#opendaq_streaming_lt_server_module[openDAQ(TM) Streaming LT Server]
to an xref:glossary.adoc#opendaq_streaming_lt_client_module[openDAQ(TM) Streaming LT Client].

[#opendaq_native_server_module]
== Native Server Module

// suppress inspection "GrazieInspection"
Allows for the creation of native configuration and streaming servers on an openDAQ(TM) <<instance>>.

The configuration server publishes the structure of the <<root_device>> and all its descendants (other <<device>>s and <<function_block>>s),
and allows for changing the <<property_value>>s of all the structures from a remote client.
The structure also dynamically adjusts to accommodate broader modifications, such as the addition of new
<<function_block>>s, <<device>>s, <<channel>>s, or other <<component>>s.

The streaming server publishes <<device>> <<signal>>s and streams <<device>> data.

[#opendaq_native_client_module]
== Native Client Module

Allows for connecting to <<device>>s running native configuration and streaming servers.

It reads the structure of the remote <<device>> and mirrors it as a sub-device.
Settings changed on the <<device>> mirror are also changed on the actual <<device>> itself.

The openDAQ(TM) Native Client Module enables its own native streaming client, which connects
to the server streaming component created by the xref:glossary.adoc#opendaq_native_server_module[openDAQ(TM) Native Server Module].
Doing so reads server signals and transfers data packets from server signals into client signals.

The openDAQ(TM) Native Client Module also allows to read the list of all signals of
the remote <<device>> and mirror these as a flat list as if owned by a "pseudo" local <<device>>.
The "Pseudo" <<device>> does not mirror <<channel>>s or <<function_block>>s of the remote <<device>>s,
and does not provide a mechanism to change settings of the remote <<device>>.

[#native_streaming_protocol]
== openDAQ(TM) Native streaming protocol

The data transfer protocol used by openDAQ(TM) to publish <<device>> available <<signal>>s and send data from <<device>>s running an
xref:glossary.adoc#opendaq_native_server_module[openDAQ(TM) Native Server]
to an xref:glossary.adoc#opendaq_native_client_module[openDAQ(TM) Native Client].

[#native_configuration_protocol]
== openDAQ(TM) Native configuration protocol

// suppress inspection "GrazieInspection"
It is a protocol that describes the structure of a <<device>>.
The openDAQ(TM) xref:glossary.adoc#opendaq_native_client_module[openDAQ(TM) Native Client] can connect to <<device>>s that adhere to this protocol.

[#streaming]
== Streaming

The generalized transport layer mechanism for continuous and real-time receiving of data from a data
acquisition <<device>>.

// TODO: openDAQ(TM) component, tags, Folder, Global ID, Local ID