site:
  title: openDAQ
  start_page: opendaq::introduction.adoc
asciidoc:
  attributes:
    doxygen_module: "Home"
    doxygen_interface_version: "v3.3.1"
    doxygen_document_date: "01.06.2022"
    doxygen_source_repo: "https://github.com/OpenSimulationInterface/open-simulation-interface.git"
    page-pagination: true
    tabs-sync-option: true
    gpp: g++
    docs-prefix: docs
    docs-website: https://{docs-prefix}.opendaq.com/
  extensions:
    - "@asciidoctor/tabs"

antora:
  extensions:
    - require: "@antora/lunr-extension" 
      index_latest_only: true
    - require: "@springio/antora-extensions/tabs-migration-extension"
    - require: './asam-antora-extensions/asam-antora_extension.js'
      doxygen: true

content:
  sources:
  - url: .
    branches: HEAD
    start_paths: docs/Antora, docs/Antora-specs
ui:
  bundle:
    url: https://github.com/openDAQ/antora-ui-spring/releases/download/1.11-opendaq/ui-bundle.zip
    snapshot: true
