#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstring>
#include <functional>
#include <iomanip>
#include <sstream>
#include <stdexcept>

#include <coreobjects/callable_info_factory.h>
#include <coreobjects/eval_value_factory.h>
#include <opendaq/custom_log.h>
#include <opendaq/opendaq.h>

#include <file_recorder_module/common.h>
#include <file_recorder_module/file_player_fb_impl.h>

BEGIN_NAMESPACE_OPENDAQ_FILE_RECORDER_MODULE

using namespace file_format;

namespace
{

/*!
 * The domain generated by the FixedSampleRate mode counts nanoseconds, which keeps the linear
 * rule's delta an exact integer for every sample rate up to 1 GHz.
 */
constexpr Int GENERATED_TICKS_PER_SECOND = 1000000000;

/*!
 * The number of samples the reader is asked for at a time. It bounds the reader's buffers, not
 * the size of an output packet: a run this long is still split to fit the packet interval.
 */
constexpr std::size_t MAX_RUN_SAMPLES = 8192;

constexpr double MIN_SAMPLE_RATE = 1e-6;

}

FunctionBlockTypePtr FilePlayerFbImpl::createType()
{
    return FunctionBlockType(TYPE_ID, "FilePlayer", "Replays a recorded file into an output signal", PropertyObject());
}

FilePlayerFbImpl::FilePlayerFbImpl(const ContextPtr& context,
                                   const ComponentPtr& parent,
                                   const StringPtr& localId,
                                   const PropertyObjectPtr& config)
    : FunctionBlock(createType(), context, parent, localId, nullptr)
{
    initComponentStatus();
    initProperties();
    initSignals();
    readProperties();
}

FilePlayerFbImpl::~FilePlayerFbImpl()
{
    stopPlayback();
}

EvalValuePtr FilePlayerFbImpl::lockedWhilePlaying()
{
    // EvalValueFunc resolves the bare identifier through the callback, which lets the flag read
    // the playback state directly instead of needing a property to mirror it.
    return EvalValueFunc("playing", Function([this](const BaseObjectPtr& /*name*/) { return BooleanPtr(playing.load()); }));
}

void FilePlayerFbImpl::initProperties()
{
    objPtr.addProperty(StringPropertyBuilder(Props::FILE_PATH, "").setReadOnly(lockedWhilePlaying()).build());

    objPtr.addProperty(SelectionPropertyBuilder(Props::PLAYBACK_MODE, List<IString>("FixedSampleRate", "RecordedDomain"), 0)
                           .setReadOnly(lockedWhilePlaying())
                           .build());

    objPtr.addProperty(FloatPropertyBuilder(Props::SAMPLE_RATE, 1000.0)
                           .setVisible(EvalValue("$PlaybackMode == 0"))
                           .setReadOnly(lockedWhilePlaying())
                           .setMinValue(MIN_SAMPLE_RATE)
                           .build());

    objPtr.addProperty(BoolPropertyBuilder(Props::SHIFT_DOMAIN_TO_NOW, True)
                           .setVisible(EvalValue("$PlaybackMode == 1"))
                           .setReadOnly(lockedWhilePlaying())
                           .build());

    objPtr.addProperty(BoolPropertyBuilder(Props::LOOP, False).setReadOnly(lockedWhilePlaying()).build());

    objPtr.addProperty(
        BoolPropertyBuilder(Props::CONTINUE_INTO_NEXT_PARTS, True).setReadOnly(lockedWhilePlaying()).build());

    objPtr.addProperty(IntPropertyBuilder(Props::OUTPUT_PACKET_INTERVAL_MS, 20)
                           .setMinValue(1)
                           .setReadOnly(lockedWhilePlaying())
                           .build());

    objPtr.addProperty(FunctionProperty(Props::START_PLAYBACK, ProcedureInfo()));
    objPtr.setPropertyValue(Props::START_PLAYBACK, Procedure([this] { this->startPlayback(); }));

    objPtr.addProperty(FunctionProperty(Props::STOP_PLAYBACK, ProcedureInfo()));
    objPtr.setPropertyValue(Props::STOP_PLAYBACK, Procedure([this] { this->stopPlayback(); }));
}

void FilePlayerFbImpl::initSignals()
{
    outputSignal = createAndAddSignal("Output");
    outputDomainSignal = createAndAddSignal("OutputDomain", nullptr, false);
    outputSignal.setDomainSignal(outputDomainSignal);
}

void FilePlayerFbImpl::readProperties()
{
    filePath = fs::path(static_cast<std::string>(objPtr.getPropertyValue(Props::FILE_PATH))).lexically_normal();
    playbackMode = static_cast<PlaybackMode>(static_cast<Int>(objPtr.getPropertyValue(Props::PLAYBACK_MODE)));
    sampleRate = objPtr.getPropertyValue(Props::SAMPLE_RATE);
    shiftDomainToNow = static_cast<bool>(objPtr.getPropertyValue(Props::SHIFT_DOMAIN_TO_NOW));
    loopPlayback = static_cast<bool>(objPtr.getPropertyValue(Props::LOOP));
    continueIntoNextParts = static_cast<bool>(objPtr.getPropertyValue(Props::CONTINUE_INTO_NEXT_PARTS));

    const Int intervalMs = objPtr.getPropertyValue(Props::OUTPUT_PACKET_INTERVAL_MS);
    packetInterval = std::chrono::milliseconds(std::max<Int>(1, intervalMs));
}

void FilePlayerFbImpl::startPlayback()
{
    auto lock = getRecursiveConfigLock();

    if (playing)
        return;

    readProperties();

    try
    {
        reader = std::make_unique<SignalFileReader>(filePath);
    }
    catch (const std::exception& e)
    {
        reader.reset();
        setComponentStatusWithMessage(ComponentStatus::Error, fmt::format("Cannot replay {}: {}", filePath.string(), e.what()));
        return;
    }

    if (playbackMode == PlaybackMode::RecordedDomain && !reader->hasDomain())
    {
        // Without a recorded domain there is nothing to take the intervals from, so the only
        // thing left to pace by is the configured rate.
        playbackMode = PlaybackMode::FixedSampleRate;
        setComponentStatusWithMessage(ComponentStatus::Warning,
                                      "The recording has no domain signal; replaying at the configured sample rate instead");
    }
    else
    {
        setComponentStatus(ComponentStatus::Ok);
    }

    if (playbackMode == PlaybackMode::FixedSampleRate)
    {
        if (sampleRate < MIN_SAMPLE_RATE)
            sampleRate = MIN_SAMPLE_RATE;

        generatedDelta = std::max<Int>(1, static_cast<Int>(std::llround(GENERATED_TICKS_PER_SECOND / sampleRate)));
    }

    publishDescriptors();

    if (playbackMode == PlaybackMode::RecordedDomain && tickResolutionSeconds <= 0.0)
    {
        reader.reset();
        setComponentStatusWithMessage(ComponentStatus::Error,
                                      "The recording's domain has no tick resolution, so its timing cannot be reproduced");
        return;
    }

    firstPartPath = filePath;
    currentPartPath = filePath;

    resetPacing();
    loopOffsetInt = 0;
    loopOffsetDouble = 0.0;
    emittedSamples = 0;

    stopRequested = false;
    playing = true;

    thread = std::thread(&FilePlayerFbImpl::threadMain, this);

    LOG_I("File player: replaying {}", filePath.string())
}

void FilePlayerFbImpl::configureRecordedDomain()
{
    recordedDomainDescriptor = reader->getHeader().domainDescriptor;

    domainDescriptor = buildRecordedDomainDescriptor(recordedDomainDescriptor);
    domainSampleType = domainDescriptor.getSampleType();
    domainIsFloatingPoint = isFloatingPointSampleType(domainSampleType);
    tickResolutionSeconds = reader->getTickResolutionSeconds();

    // An implicit domain has one constant spacing, which is also the gap to leave between loop
    // passes. An explicit one is measured as it is replayed.
    recordedDeltaInt = reader->getDomainDeltaInt();
    recordedDeltaDouble = reader->getDomainDeltaDouble();
    lastStepInt = recordedDeltaInt;
    lastStepDouble = recordedDeltaDouble;
}

void FilePlayerFbImpl::publishDescriptors()
{
    valueDescriptor = reader->getHeader().valueDescriptor;

    if (playbackMode == PlaybackMode::RecordedDomain)
    {
        configureRecordedDomain();
    }
    else
    {
        recordedDomainDescriptor = nullptr;
        domainDescriptor = buildGeneratedDomainDescriptor();
        domainSampleType = SampleType::Int64;
        domainIsFloatingPoint = false;
        tickResolutionSeconds = 1.0 / static_cast<double>(GENERATED_TICKS_PER_SECOND);
    }

    outputDomainSignal.setDescriptor(domainDescriptor);
    outputSignal.setDescriptor(valueDescriptor);
}

void FilePlayerFbImpl::resetPacing()
{
    anchored = false;
    firstTick = 0.0;
    firstTickInt = 0;
    lastTick = 0.0;
    lastTickInt = 0;
}

std::optional<fs::path> FilePlayerFbImpl::nextPartPath(const fs::path& current)
{
    const auto stem = current.stem().string();

    const auto separator = stem.find_last_of('_');
    if (separator == std::string::npos)
        return std::nullopt;

    const auto digits = stem.substr(separator + 1);
    if (digits.empty() || !std::all_of(digits.begin(), digits.end(), [](unsigned char ch) { return std::isdigit(ch) != 0; }))
        return std::nullopt;

    Int index = 0;
    try
    {
        index = std::stoll(digits);
    }
    catch (const std::exception&)
    {
        return std::nullopt;
    }

    std::ostringstream filename;
    filename << stem.substr(0, separator + 1) << std::setfill('0') << std::setw(static_cast<int>(digits.size())) << (index + 1)
             << FILE_EXTENSION;

    auto path = current.parent_path() / filename.str();

    std::error_code error;
    if (!fs::exists(path, error) || error)
        return std::nullopt;

    return path;
}

bool FilePlayerFbImpl::openPart(const fs::path& path)
{
    std::unique_ptr<SignalFileReader> nextReader;
    try
    {
        nextReader = std::make_unique<SignalFileReader>(path);
    }
    catch (const std::exception& e)
    {
        LOG_W("File player: cannot open {}: {}", path.string(), e.what())
        setComponentStatusWithMessage(ComponentStatus::Warning, fmt::format("Cannot open {}: {}", path.string(), e.what()));
        return false;
    }

    if (playbackMode == PlaybackMode::RecordedDomain && !nextReader->hasDomain())
    {
        setComponentStatusWithMessage(ComponentStatus::Warning,
                                      fmt::format("{} has no domain signal to take its timing from", path.string()));
        return false;
    }

    const auto& header = nextReader->getHeader();

    const bool valueChanged = header.valueDescriptor != valueDescriptor;
    const bool domainChanged =
        playbackMode == PlaybackMode::RecordedDomain && header.domainDescriptor != recordedDomainDescriptor;

    reader = std::move(nextReader);
    currentPartPath = path;

    // A part is only ever a new file because of a size limit or because the signal changed, so
    // most of the time there is nothing to republish and the stream carries on seamlessly.
    if (valueChanged)
    {
        valueDescriptor = header.valueDescriptor;
        outputSignal.setDescriptor(valueDescriptor);
    }

    if (domainChanged)
    {
        configureRecordedDomain();
        outputDomainSignal.setDescriptor(domainDescriptor);

        if (tickResolutionSeconds <= 0.0)
        {
            setComponentStatusWithMessage(ComponentStatus::Warning,
                                          fmt::format("{} has a domain without a tick resolution", path.string()));
            return false;
        }

        // The new domain may count in entirely different units, so continuing the old timeline
        // would be meaningless. Time starts again from this part.
        resetPacing();
        loopOffsetInt = 0;
        loopOffsetDouble = 0.0;
    }

    return true;
}

FilePlayerFbImpl::PartAdvance FilePlayerFbImpl::advanceToNextPart()
{
    if (!continueIntoNextParts)
        return PartAdvance::NoMoreParts;

    const auto next = nextPartPath(currentPartPath);
    if (!next.has_value())
        return PartAdvance::NoMoreParts;

    if (!openPart(*next))
        return PartAdvance::Failed;

    LOG_D("File player: continuing into {}", next->string())
    return PartAdvance::Continued;
}

void FilePlayerFbImpl::stopPlayback()
{
    std::thread stopping;

    {
        auto lock = getRecursiveConfigLock();

        if (!playing && !thread.joinable())
            return;

        {
            std::lock_guard threadLock(threadMutex);
            stopRequested = true;
        }
        threadCv.notify_one();

        stopping = std::move(thread);
    }

    // Joined outside the function block's lock: the playback thread takes that same lock to send
    // packets and to report status, so waiting for it while holding it would deadlock.
    if (stopping.joinable())
        stopping.join();

    auto lock = getRecursiveConfigLock();

    reader.reset();

    if (playing)
    {
        playing = false;
        LOG_I("File player: playback stopped")
    }
}

void FilePlayerFbImpl::activeChanged()
{
    if (!active)
        stopPlayback();
}

void FilePlayerFbImpl::removed()
{
    stopPlayback();
}

DataDescriptorPtr FilePlayerFbImpl::buildGeneratedDomainDescriptor() const
{
    return DataDescriptorBuilder()
        .setSampleType(SampleType::Int64)
        .setUnit(Unit("s", -1, "seconds", "time"))
        .setTickResolution(Ratio(1, GENERATED_TICKS_PER_SECOND))
        .setRule(LinearDataRule(generatedDelta, 0))
        .setOrigin(toIso8601(std::chrono::system_clock::now()))
        .setName("Time")
        .build();
}

DataDescriptorPtr FilePlayerFbImpl::buildRecordedDomainDescriptor(const DataDescriptorPtr& recorded) const
{
    if (!shiftDomainToNow)
        return recorded;

    // The ticks themselves are rebased to start at zero by the playback thread; moving the origin
    // to now is what makes those rebased ticks describe the present.
    return DataDescriptorBuilderCopy(recorded).setOrigin(toIso8601(std::chrono::system_clock::now())).build();
}

void FilePlayerFbImpl::threadMain()
{
    SignalFileReader::Run run;

    while (true)
    {
        {
            std::lock_guard threadLock(threadMutex);
            if (stopRequested)
                break;
        }

        bool read = false;
        try
        {
            read = reader->readRun(MAX_RUN_SAMPLES, run);
        }
        catch (const std::exception& e)
        {
            LOG_W("File player: {}", e.what())
            setComponentStatusWithMessage(ComponentStatus::Warning, fmt::format("Playback stopped: {}", e.what()));
            break;
        }

        if (!read)
        {
            const auto advance = advanceToNextPart();
            if (advance == PartAdvance::Continued)
                continue;
            if (advance == PartAdvance::Failed)
                break;

            if (!loopPlayback)
            {
                LOG_I("File player: reached the end of {}", currentPartPath.string())
                break;
            }

            if (!beginNextLoop())
                break;

            continue;
        }

        for (std::size_t offset = 0; offset < run.sampleCount;)
        {
            const auto count = sliceLength(run, offset);

            if (!waitForSlice(run, offset))
                return;

            emitSlice(run, offset, count);
            offset += count;
        }
    }
}

std::size_t FilePlayerFbImpl::sliceLength(const SignalFileReader::Run& run, std::size_t offset) const
{
    const auto remaining = run.sampleCount - offset;

    // In the fixed rate mode the reader was already asked for one interval's worth of samples,
    // and the domain is regenerated, so the run is emitted as a single packet.
    if (playbackMode == PlaybackMode::FixedSampleRate || run.domainKind == DomainKind::None)
        return remaining;

    const auto intervalSeconds = std::chrono::duration<double>(packetInterval).count();
    const auto sliceStartTick = reader->tickAt(run, offset);

    auto previousTick = sliceStartTick;
    for (std::size_t i = 1; i < remaining; ++i)
    {
        const auto tick = reader->tickAt(run, offset + i);

        // A pause longer than the packet interval ends the packet, so that it is reproduced as a
        // wait before the next packet rather than being hidden inside this one.
        if ((tick - previousTick) * tickResolutionSeconds > intervalSeconds)
            return i;

        if ((tick - sliceStartTick) * tickResolutionSeconds > intervalSeconds)
            return i;

        previousTick = tick;
    }

    return remaining;
}

bool FilePlayerFbImpl::waitForSlice(const SignalFileReader::Run& run, std::size_t offset)
{
    const bool paceByDomain = playbackMode == PlaybackMode::RecordedDomain && run.domainKind != DomainKind::None;

    const auto tick = paceByDomain ? reader->tickAt(run, offset) : 0.0;

    if (!anchored)
    {
        // The first sample defines both references: it is emitted immediately, and every later
        // deadline is measured from here.
        anchored = true;
        playbackStart = std::chrono::steady_clock::now();

        if (paceByDomain)
        {
            firstTick = tick;
            firstTickInt = domainIsFloatingPoint ? 0 : reader->tickAtAsInt(run, offset);
        }
    }

    const double elapsedSeconds = paceByDomain ? (tick - firstTick + loopOffsetDouble) * tickResolutionSeconds
                                               : static_cast<double>(emittedSamples) / sampleRate;

    const auto deadline =
        playbackStart + std::chrono::duration_cast<std::chrono::steady_clock::duration>(std::chrono::duration<double>(elapsedSeconds));

    return waitUntil(deadline);
}

bool FilePlayerFbImpl::waitUntil(std::chrono::steady_clock::time_point deadline)
{
    std::unique_lock threadLock(threadMutex);

    // Waiting on the condition variable rather than sleeping means a stop takes effect at once,
    // even in the middle of reproducing a pause that lasts minutes.
    threadCv.wait_until(threadLock, deadline, [this] { return stopRequested; });

    return !stopRequested;
}

DataPacketPtr FilePlayerFbImpl::createDomainPacket(const SignalFileReader::Run& run, std::size_t offset, std::size_t count)
{
    if (playbackMode == PlaybackMode::FixedSampleRate || run.domainKind == DomainKind::None)
        return DataPacket(domainDescriptor, count, Integer(static_cast<Int>(emittedSamples) * generatedDelta));

    const auto domainSampleSize = reader->getDomainSampleSize();

    if (run.domainKind == DomainKind::Implicit)
    {
        // The run's ticks follow the recorded linear rule, so only its start value has to be
        // carried; the packet offset is exactly what implicit packets are for.
        if (domainIsFloatingPoint)
        {
            const auto start = readTickAsDouble(run.domainData.data(), domainSampleType);
            return DataPacket(domainDescriptor,
                              count,
                              Floating(start + static_cast<double>(offset) * recordedDeltaDouble + emitShiftDouble()));
        }

        const auto start = readTickAsInt(run.domainData.data(), domainSampleType);
        return DataPacket(domainDescriptor, count, Integer(start + static_cast<Int>(offset) * recordedDeltaInt + emitShiftInt()));
    }

    auto packet = DataPacket(domainDescriptor, count);
    auto* target = static_cast<char*>(packet.getRawData());
    const auto* source = run.domainData.data() + offset * domainSampleSize;

    std::memcpy(target, source, count * domainSampleSize);

    if (domainIsFloatingPoint)
    {
        const auto shift = emitShiftDouble();
        if (shift != 0.0)
            for (std::size_t i = 0; i < count; ++i)
                writeTickAsDouble(target + i * domainSampleSize,
                                  domainSampleType,
                                  readTickAsDouble(target + i * domainSampleSize, domainSampleType) + shift);
    }
    else
    {
        const auto shift = emitShiftInt();
        if (shift != 0)
            for (std::size_t i = 0; i < count; ++i)
                writeTickAsInt(target + i * domainSampleSize,
                               domainSampleType,
                               readTickAsInt(target + i * domainSampleSize, domainSampleType) + shift);
    }

    return packet;
}

void FilePlayerFbImpl::emitSlice(const SignalFileReader::Run& run, std::size_t offset, std::size_t count)
{
    const auto domainPacket = createDomainPacket(run, offset, count);

    auto packet = DataPacketWithDomain(domainPacket, valueDescriptor, count);
    const auto valueSampleSize = reader->getValueSampleSize();
    std::memcpy(packet.getRawData(), run.valueData.data() + offset * valueSampleSize, count * valueSampleSize);

    outputDomainSignal.sendPacket(domainPacket);
    outputSignal.sendPacket(packet);

    if (playbackMode == PlaybackMode::RecordedDomain && run.domainKind != DomainKind::None)
    {
        const auto lastIndex = offset + count - 1;

        const auto newLastTick = reader->tickAt(run, lastIndex);
        const Int newLastTickInt = domainIsFloatingPoint ? 0 : reader->tickAtAsInt(run, lastIndex);

        // An explicit domain has no single spacing, so the interval between the final two samples
        // stands in for it when a loop pass has to be placed after this one. Those two samples
        // are often in different packets, because a gap wider than the packet interval ends a
        // packet, so the measurement has to work across a packet boundary as well as within one.
        if (run.domainKind == DomainKind::Explicit)
        {
            if (count >= 2)
            {
                lastStepDouble = newLastTick - reader->tickAt(run, lastIndex - 1);
                if (!domainIsFloatingPoint)
                    lastStepInt = newLastTickInt - reader->tickAtAsInt(run, lastIndex - 1);
            }
            else if (emittedSamples > 0 && newLastTick > lastTick)
            {
                // Guarded against going backwards, which is what the first sample of a new loop
                // pass looks like before its offset is applied.
                lastStepDouble = newLastTick - lastTick;
                if (!domainIsFloatingPoint)
                    lastStepInt = newLastTickInt - lastTickInt;
            }
        }

        lastTick = newLastTick;
        lastTickInt = newLastTickInt;
    }

    emittedSamples += count;
}

Int FilePlayerFbImpl::emitShiftInt() const
{
    return (shiftDomainToNow ? -firstTickInt : 0) + loopOffsetInt;
}

double FilePlayerFbImpl::emitShiftDouble() const
{
    return (shiftDomainToNow ? -firstTick : 0.0) + loopOffsetDouble;
}

bool FilePlayerFbImpl::beginNextLoop()
{
    if (playbackMode == PlaybackMode::RecordedDomain && anchored)
    {
        // The next pass replays the same ticks, so it is offset past the end of this one.
        // Without this the replayed domain would jump backwards on every repetition, and the
        // pacing would try to emit the whole pass at once to catch up.
        loopOffsetDouble += lastTick - firstTick + (lastStepDouble != 0.0 ? lastStepDouble : 1.0);

        if (!domainIsFloatingPoint)
            loopOffsetInt += lastTickInt - firstTickInt + (lastStepInt != 0 ? lastStepInt : 1);
    }

    // A recording spanning several parts loops back to the part playback started from, not to the
    // last one read. openPart() clears the offsets just accumulated when it re-anchors, so they
    // are restored afterwards; a single-part recording rewinds in place instead.
    if (currentPartPath != firstPartPath)
    {
        const auto loopOffsetIntBefore = loopOffsetInt;
        const auto loopOffsetDoubleBefore = loopOffsetDouble;

        if (!openPart(firstPartPath))
            return false;

        loopOffsetInt = loopOffsetIntBefore;
        loopOffsetDouble = loopOffsetDoubleBefore;
    }
    else
    {
        reader->rewind();
    }

    LOG_D("File player: looping back to the start of {}", firstPartPath.string())
    return true;
}

END_NAMESPACE_OPENDAQ_FILE_RECORDER_MODULE
