//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:57.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/allocator.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID ALLOCATOR_INTF_ID = { daq::IAllocator::Id.Data1, daq::IAllocator::Id.Data2, daq::IAllocator::Id.Data3, daq::IAllocator::Id.Data4_UInt64 };

ErrCode Allocator_allocate(Allocator* self, DataDescriptor* descriptor, SizeT bytes, SizeT align, void** address)
{
    return reinterpret_cast<daq::IAllocator*>(self)->allocate(reinterpret_cast<daq::IDataDescriptor*>(descriptor), bytes, align, address);
}

ErrCode Allocator_free(Allocator* self, void* address)
{
    return reinterpret_cast<daq::IAllocator*>(self)->free(address);
}

ErrCode Allocator_createMallocAllocator(Allocator** obj)
{
    daq::IAllocator* ptr = nullptr;
    ErrCode err = daq::createMallocAllocator(&ptr);
    *obj = reinterpret_cast<Allocator*>(ptr);
    return err;
}

// ErrCode Allocator_createMiMallocAllocator(Allocator** obj)
// {
//     daq::IAllocator* ptr = nullptr;
//     ErrCode err = daq::createMiMallocAllocator(&ptr);
//     *obj = reinterpret_cast<Allocator*>(ptr);
//     return err;
// }

ErrCode Allocator_createExternalAllocator(Allocator** obj, void* data, Deleter* deleter)
{
    daq::IAllocator* ptr = nullptr;
    ErrCode err = daq::createExternalAllocator(&ptr, data, reinterpret_cast<daq::IDeleter*>(deleter));
    *obj = reinterpret_cast<Allocator*>(ptr);
    return err;
}
