//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:54.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/signal/data_rule_builder.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID DATA_RULE_BUILDER_INTF_ID = { daq::IDataRuleBuilder::Id.Data1, daq::IDataRuleBuilder::Id.Data2, daq::IDataRuleBuilder::Id.Data3, daq::IDataRuleBuilder::Id.Data4_UInt64 };

ErrCode DataRuleBuilder_build(DataRuleBuilder* self, DataRule** dataRule)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->build(reinterpret_cast<daq::IDataRule**>(dataRule));
}

ErrCode DataRuleBuilder_setType(DataRuleBuilder* self, DataRuleType type)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->setType(static_cast<daq::DataRuleType>(type));
}

ErrCode DataRuleBuilder_getType(DataRuleBuilder* self, DataRuleType* type)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->getType(reinterpret_cast<daq::DataRuleType*>(type));
}

ErrCode DataRuleBuilder_setParameters(DataRuleBuilder* self, Dict* parameters)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->setParameters(reinterpret_cast<daq::IDict*>(parameters));
}

ErrCode DataRuleBuilder_getParameters(DataRuleBuilder* self, Dict** parameters)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->getParameters(reinterpret_cast<daq::IDict**>(parameters));
}

ErrCode DataRuleBuilder_addParameter(DataRuleBuilder* self, String* name, BaseObject* parameter)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->addParameter(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IBaseObject*>(parameter));
}

ErrCode DataRuleBuilder_removeParameter(DataRuleBuilder* self, String* name)
{
    return reinterpret_cast<daq::IDataRuleBuilder*>(self)->removeParameter(reinterpret_cast<daq::IString*>(name));
}

ErrCode DataRuleBuilder_createDataRuleBuilder(DataRuleBuilder** obj)
{
    daq::IDataRuleBuilder* ptr = nullptr;
    ErrCode err = daq::createDataRuleBuilder(&ptr);
    *obj = reinterpret_cast<DataRuleBuilder*>(ptr);
    return err;
}

ErrCode DataRuleBuilder_createDataRuleBuilderFromExisting(DataRuleBuilder** obj, DataRule* ruleToCopy)
{
    daq::IDataRuleBuilder* ptr = nullptr;
    ErrCode err = daq::createDataRuleBuilderFromExisting(&ptr, reinterpret_cast<daq::IDataRule*>(ruleToCopy));
    *obj = reinterpret_cast<DataRuleBuilder*>(ptr);
    return err;
}
