//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:34:05.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/event_packet.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID EVENT_PACKET_INTF_ID = { daq::IEventPacket::Id.Data1, daq::IEventPacket::Id.Data2, daq::IEventPacket::Id.Data3, daq::IEventPacket::Id.Data4_UInt64 };

ErrCode EventPacket_getEventId(EventPacket* self, String** id)
{
    return reinterpret_cast<daq::IEventPacket*>(self)->getEventId(reinterpret_cast<daq::IString**>(id));
}

ErrCode EventPacket_getParameters(EventPacket* self, Dict** parameters)
{
    return reinterpret_cast<daq::IEventPacket*>(self)->getParameters(reinterpret_cast<daq::IDict**>(parameters));
}

ErrCode EventPacket_createEventPacket(EventPacket** obj, String* id, Dict* params)
{
    daq::IEventPacket* ptr = nullptr;
    ErrCode err = daq::createEventPacket(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IDict*>(params));
    *obj = reinterpret_cast<EventPacket*>(ptr);
    return err;
}

ErrCode EventPacket_createDataDescriptorChangedEventPacket(EventPacket** obj, DataDescriptor* dataDescriptor, DataDescriptor* domainDataDescriptor)
{
    daq::IEventPacket* ptr = nullptr;
    ErrCode err = daq::createDataDescriptorChangedEventPacket(&ptr, reinterpret_cast<daq::IDataDescriptor*>(dataDescriptor), reinterpret_cast<daq::IDataDescriptor*>(domainDataDescriptor));
    *obj = reinterpret_cast<EventPacket*>(ptr);
    return err;
}

ErrCode EventPacket_createImplicitDomainGapDetectedEventPacket(EventPacket** obj, Number* diff)
{
    daq::IEventPacket* ptr = nullptr;
    ErrCode err = daq::createImplicitDomainGapDetectedEventPacket(&ptr, reinterpret_cast<daq::INumber*>(diff));
    *obj = reinterpret_cast<EventPacket*>(ptr);
    return err;
}
