//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:50.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/reference_domain_info.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_REFERENCE_DOMAIN_INFO_INTF_ID = { daq::IReferenceDomainInfo::Id.Data1, daq::IReferenceDomainInfo::Id.Data2, daq::IReferenceDomainInfo::Id.Data3, daq::IReferenceDomainInfo::Id.Data4_UInt64 };

daqErrCode daqReferenceDomainInfo_getReferenceDomainId(daqReferenceDomainInfo* self, daqString** referenceDomainId)
{
    return reinterpret_cast<daq::IReferenceDomainInfo*>(self)->getReferenceDomainId(reinterpret_cast<daq::IString**>(referenceDomainId));
}

daqErrCode daqReferenceDomainInfo_getReferenceDomainOffset(daqReferenceDomainInfo* self, daqInteger** referenceDomainOffset)
{
    return reinterpret_cast<daq::IReferenceDomainInfo*>(self)->getReferenceDomainOffset(reinterpret_cast<daq::IInteger**>(referenceDomainOffset));
}

daqErrCode daqReferenceDomainInfo_getReferenceTimeSource(daqReferenceDomainInfo* self, daqTimeSource* referenceTimeSource)
{
    return reinterpret_cast<daq::IReferenceDomainInfo*>(self)->getReferenceTimeSource(reinterpret_cast<daq::TimeSource*>(referenceTimeSource));
}

daqErrCode daqReferenceDomainInfo_getUsesOffset(daqReferenceDomainInfo* self, daqUsesOffset* usesOffset)
{
    return reinterpret_cast<daq::IReferenceDomainInfo*>(self)->getUsesOffset(reinterpret_cast<daq::UsesOffset*>(usesOffset));
}

daqErrCode daqReferenceDomainInfo_createReferenceDomainInfoFromBuilder(daqReferenceDomainInfo** obj, daqReferenceDomainInfoBuilder* builder)
{
    daq::IReferenceDomainInfo* ptr = nullptr;
    daqErrCode err = daq::createReferenceDomainInfoFromBuilder(&ptr, reinterpret_cast<daq::IReferenceDomainInfoBuilder*>(builder));
    *obj = reinterpret_cast<daqReferenceDomainInfo*>(ptr);
    return err;
}
