//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:51.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/reusable_data_packet.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_REUSABLE_DATA_PACKET_INTF_ID = { daq::IReusableDataPacket::Id.Data1, daq::IReusableDataPacket::Id.Data2, daq::IReusableDataPacket::Id.Data3, daq::IReusableDataPacket::Id.Data4_UInt64 };

daqErrCode daqReusableDataPacket_reuse(daqReusableDataPacket* self, daqDataDescriptor* newDescriptor, daqSizeT newSampleCount, daqNumber* newOffset, daqDataPacket* newDomainPacket, daqBool canReallocMemory, daqBool* success)
{
    return reinterpret_cast<daq::IReusableDataPacket*>(self)->reuse(reinterpret_cast<daq::IDataDescriptor*>(newDescriptor), newSampleCount, reinterpret_cast<daq::INumber*>(newOffset), reinterpret_cast<daq::IDataPacket*>(newDomainPacket), canReallocMemory, success);
}
