//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:38:05.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/signal/rule_private.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID RULE_PRIVATE_INTF_ID = { daq::IRulePrivate::Id.Data1, daq::IRulePrivate::Id.Data2, daq::IRulePrivate::Id.Data3, daq::IRulePrivate::Id.Data4_UInt64 };

ErrCode RulePrivate_verifyParameters(RulePrivate* self)
{
    return reinterpret_cast<daq::IRulePrivate*>(self)->verifyParameters();
}
