//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:55.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/signal_config.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_SIGNAL_CONFIG_INTF_ID = { daq::ISignalConfig::Id.Data1, daq::ISignalConfig::Id.Data2, daq::ISignalConfig::Id.Data3, daq::ISignalConfig::Id.Data4_UInt64 };

daqErrCode daqSignalConfig_setDescriptor(daqSignalConfig* self, daqDataDescriptor* descriptor)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->setDescriptor(reinterpret_cast<daq::IDataDescriptor*>(descriptor));
}

daqErrCode daqSignalConfig_setDomainSignal(daqSignalConfig* self, daqSignal* signal)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->setDomainSignal(reinterpret_cast<daq::ISignal*>(signal));
}

daqErrCode daqSignalConfig_setRelatedSignals(daqSignalConfig* self, daqList* signals)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->setRelatedSignals(reinterpret_cast<daq::IList*>(signals));
}

daqErrCode daqSignalConfig_addRelatedSignal(daqSignalConfig* self, daqSignal* signal)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->addRelatedSignal(reinterpret_cast<daq::ISignal*>(signal));
}

daqErrCode daqSignalConfig_removeRelatedSignal(daqSignalConfig* self, daqSignal* signal)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->removeRelatedSignal(reinterpret_cast<daq::ISignal*>(signal));
}

daqErrCode daqSignalConfig_clearRelatedSignals(daqSignalConfig* self)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->clearRelatedSignals();
}

daqErrCode daqSignalConfig_sendPacket(daqSignalConfig* self, daqPacket* packet)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->sendPacket(reinterpret_cast<daq::IPacket*>(packet));
}

daqErrCode daqSignalConfig_sendPackets(daqSignalConfig* self, daqList* packets)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->sendPackets(reinterpret_cast<daq::IList*>(packets));
}

daqErrCode daqSignalConfig_sendPacketAndStealRef(daqSignalConfig* self, daqPacket* packet)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->sendPacketAndStealRef(reinterpret_cast<daq::IPacket*>(packet));
}

daqErrCode daqSignalConfig_sendPacketsAndStealRef(daqSignalConfig* self, daqList* packets)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->sendPacketsAndStealRef(reinterpret_cast<daq::IList*>(packets));
}

daqErrCode daqSignalConfig_setLastValue(daqSignalConfig* self, daqBaseObject* lastValue)
{
    return reinterpret_cast<daq::ISignalConfig*>(self)->setLastValue(reinterpret_cast<daq::IBaseObject*>(lastValue));
}

daqErrCode daqSignalConfig_createSignal(daqSignalConfig** obj, daqContext* context, daqComponent* parent, daqString* localId, daqString* className)
{
    daq::ISignalConfig* ptr = nullptr;
    daqErrCode err = daq::createSignal(&ptr, reinterpret_cast<daq::IContext*>(context), reinterpret_cast<daq::IComponent*>(parent), reinterpret_cast<daq::IString*>(localId), reinterpret_cast<daq::IString*>(className));
    *obj = reinterpret_cast<daqSignalConfig*>(ptr);
    return err;
}

daqErrCode daqSignalConfig_createSignalWithDescriptor(daqSignalConfig** obj, daqContext* context, daqDataDescriptor* descriptor, daqComponent* parent, daqString* localId, daqString* className)
{
    daq::ISignalConfig* ptr = nullptr;
    daqErrCode err = daq::createSignalWithDescriptor(&ptr, reinterpret_cast<daq::IContext*>(context), reinterpret_cast<daq::IDataDescriptor*>(descriptor), reinterpret_cast<daq::IComponent*>(parent), reinterpret_cast<daq::IString*>(localId), reinterpret_cast<daq::IString*>(className));
    *obj = reinterpret_cast<daqSignalConfig*>(ptr);
    return err;
}
