//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:34:05.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct DimensionRuleBuilder DimensionRuleBuilder;
    typedef struct DimensionRule DimensionRule;
    typedef struct Dict Dict;
    typedef struct String String;

    EXPORTED extern const IntfID DIMENSION_RULE_BUILDER_INTF_ID;

    ErrCode EXPORTED DimensionRuleBuilder_build(DimensionRuleBuilder* self, DimensionRule** dimensionRule);
    ErrCode EXPORTED DimensionRuleBuilder_setType(DimensionRuleBuilder* self, DimensionRuleType type);
    ErrCode EXPORTED DimensionRuleBuilder_getType(DimensionRuleBuilder* self, DimensionRuleType* type);
    ErrCode EXPORTED DimensionRuleBuilder_setParameters(DimensionRuleBuilder* self, Dict* parameters);
    ErrCode EXPORTED DimensionRuleBuilder_getParameters(DimensionRuleBuilder* self, Dict** parameters);
    ErrCode EXPORTED DimensionRuleBuilder_addParameter(DimensionRuleBuilder* self, String* name, BaseObject* parameter);
    ErrCode EXPORTED DimensionRuleBuilder_removeParameter(DimensionRuleBuilder* self, String* name);
    ErrCode EXPORTED DimensionRuleBuilder_createDimensionRuleBuilder(DimensionRuleBuilder** obj);
    ErrCode EXPORTED DimensionRuleBuilder_createDimensionRuleBuilderFromExisting(DimensionRuleBuilder** obj, DimensionRule* ruleToCopy);

#ifdef __cplusplus
}
#endif
