//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:55.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

    typedef struct DimensionBuilder DimensionBuilder;
    typedef struct Dimension Dimension;
    typedef struct String String;
    typedef struct Unit Unit;
    typedef struct DimensionRule DimensionRule;

    EXPORTED extern const IntfID DIMENSION_BUILDER_INTF_ID;

    ErrCode EXPORTED DimensionBuilder_build(DimensionBuilder* self, Dimension** dimension);
    ErrCode EXPORTED DimensionBuilder_setName(DimensionBuilder* self, String* name);
    ErrCode EXPORTED DimensionBuilder_getName(DimensionBuilder* self, String** name);
    ErrCode EXPORTED DimensionBuilder_setUnit(DimensionBuilder* self, Unit* unit);
    ErrCode EXPORTED DimensionBuilder_getUnit(DimensionBuilder* self, Unit** unit);
    ErrCode EXPORTED DimensionBuilder_setRule(DimensionBuilder* self, DimensionRule* rule);
    ErrCode EXPORTED DimensionBuilder_getRule(DimensionBuilder* self, DimensionRule** rule);
    ErrCode EXPORTED DimensionBuilder_createDimensionBuilder(DimensionBuilder** obj);
    ErrCode EXPORTED DimensionBuilder_createDimensionBuilderFromExisting(DimensionBuilder** obj, Dimension* dimensionToCopy);

#ifdef __cplusplus
}
#endif
