//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:34:15.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct SignalEvents SignalEvents;
    typedef struct Connection Connection;
    typedef struct Signal Signal;

    EXPORTED extern const IntfID SIGNAL_EVENTS_INTF_ID;

    ErrCode EXPORTED SignalEvents_listenerConnected(SignalEvents* self, Connection* connection);
    ErrCode EXPORTED SignalEvents_listenerDisconnected(SignalEvents* self, Connection* connection);
    ErrCode EXPORTED SignalEvents_domainSignalReferenceSet(SignalEvents* self, Signal* signal);
    ErrCode EXPORTED SignalEvents_domainSignalReferenceRemoved(SignalEvents* self, Signal* signal);

#ifdef __cplusplus
}
#endif
