//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:38:08.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

    typedef struct Signal Signal;
    typedef struct DataDescriptor DataDescriptor;
    typedef struct List List;

    EXPORTED extern const IntfID SIGNAL_INTF_ID;

    ErrCode EXPORTED Signal_getPublic(Signal* self, Bool* isPublic);
    ErrCode EXPORTED Signal_setPublic(Signal* self, Bool isPublic);
    ErrCode EXPORTED Signal_getDescriptor(Signal* self, DataDescriptor** descriptor);
    ErrCode EXPORTED Signal_getDomainSignal(Signal* self, Signal** signal);
    ErrCode EXPORTED Signal_getRelatedSignals(Signal* self, List** signals);
    ErrCode EXPORTED Signal_getConnections(Signal* self, List** connections);
    ErrCode EXPORTED Signal_getStreamed(Signal* self, Bool* streamed);
    ErrCode EXPORTED Signal_setStreamed(Signal* self, Bool streamed);
    ErrCode EXPORTED Signal_getLastValue(Signal* self, BaseObject** value);

#ifdef __cplusplus
}
#endif
