//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:06:52.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqComponentStatusContainer daqComponentStatusContainer;
    typedef struct daqString daqString;
    typedef struct daqEnumeration daqEnumeration;
    typedef struct daqDict daqDict;

    EXPORTED extern const daqIntfID DAQ_COMPONENT_STATUS_CONTAINER_INTF_ID;

    daqErrCode EXPORTED daqComponentStatusContainer_getStatus(daqComponentStatusContainer* self, daqString* name, daqEnumeration** value);
    daqErrCode EXPORTED daqComponentStatusContainer_getStatuses(daqComponentStatusContainer* self, daqDict** statuses);
    daqErrCode EXPORTED daqComponentStatusContainer_getStatusMessage(daqComponentStatusContainer* self, daqString* name, daqString** message);
    daqErrCode EXPORTED daqComponentStatusContainer_createComponentStatusContainer(daqComponentStatusContainer** obj);

#ifdef __cplusplus
}
#endif
