//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:06:50.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqComponent daqComponent;
    typedef struct daqString daqString;
    typedef struct daqContext daqContext;
    typedef struct daqTags daqTags;
    typedef struct daqList daqList;
    typedef struct daqEvent daqEvent;
    typedef struct daqComponentStatusContainer daqComponentStatusContainer;

    EXPORTED extern const daqIntfID DAQ_COMPONENT_INTF_ID;

    daqErrCode EXPORTED daqComponent_getLocalId(daqComponent* self, daqString** localId);
    daqErrCode EXPORTED daqComponent_getGlobalId(daqComponent* self, daqString** globalId);
    daqErrCode EXPORTED daqComponent_getActive(daqComponent* self, daqBool* active);
    daqErrCode EXPORTED daqComponent_setActive(daqComponent* self, daqBool active);
    daqErrCode EXPORTED daqComponent_getContext(daqComponent* self, daqContext** context);
    daqErrCode EXPORTED daqComponent_getParent(daqComponent* self, daqComponent** parent);
    daqErrCode EXPORTED daqComponent_getName(daqComponent* self, daqString** name);
    daqErrCode EXPORTED daqComponent_setName(daqComponent* self, daqString* name);
    daqErrCode EXPORTED daqComponent_getDescription(daqComponent* self, daqString** description);
    daqErrCode EXPORTED daqComponent_setDescription(daqComponent* self, daqString* description);
    daqErrCode EXPORTED daqComponent_getTags(daqComponent* self, daqTags** tags);
    daqErrCode EXPORTED daqComponent_getVisible(daqComponent* self, daqBool* visible);
    daqErrCode EXPORTED daqComponent_setVisible(daqComponent* self, daqBool visible);
    daqErrCode EXPORTED daqComponent_getLockedAttributes(daqComponent* self, daqList** attributes);
    daqErrCode EXPORTED daqComponent_getOnComponentCoreEvent(daqComponent* self, daqEvent** event);
    daqErrCode EXPORTED daqComponent_getStatusContainer(daqComponent* self, daqComponentStatusContainer** statusContainer);
    daqErrCode EXPORTED daqComponent_findComponent(daqComponent* self, daqString* id, daqComponent** outComponent);
    daqErrCode EXPORTED daqComponent_getOperationMode(daqComponent* self, daqOperationModeType* modeType);
    daqErrCode EXPORTED daqComponent_createComponent(daqComponent** obj, daqContext* context, daqComponent* parent, daqString* localId, daqString* className);

#ifdef __cplusplus
}
#endif
