//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    /*!
     * @brief Allows the component to be notified when it is removed.
     */
    DAQ_EXTENDS_INTERFACE(daqRemovable, daqBaseObject);

    typedef struct daqRemovable daqRemovable;

    EXPORTED extern const daqIntfID DAQ_REMOVABLE_INTF_ID;
    void EXPORTED daqRemovable_getInterfaceId(daqIntfID* intfId);

    /*!
     * @brief Notifies the component that it is being removed.
     *
     * Call `remove` on the component to mark it as removed. It's up to the implementation
     * to define what is does on the act of removal. Basic implementation of `Component`
     * will switch it to inactive state and it cannot be activated again.
     */
    daqErrCode EXPORTED daqRemovable_remove(daqRemovable* self);

    /*!
     * @brief Returns True if component was removed.
     * @param[out] removed True if component was removed; otherwise False.
     */
    daqErrCode EXPORTED daqRemovable_isRemoved(daqRemovable* self, daqBool* removed);

#ifdef __cplusplus
}
#endif
