//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    /*!
     * @brief Private interface to component tags. Allows for adding/removing tags.
     *
     * Modifying the tags of a component might have unintended sideffects and should in most cases only be done
     * by the component owner module.
     */
    DAQ_EXTENDS_INTERFACE(daqTagsPrivate, daqBaseObject);

    typedef struct daqTagsPrivate daqTagsPrivate;
    typedef struct daqString daqString;
    typedef struct daqList daqList;

    EXPORTED extern const daqIntfID DAQ_TAGS_PRIVATE_INTF_ID;
    void EXPORTED daqTagsPrivate_getInterfaceId(daqIntfID* intfId);

    /*!
     * @brief Adds a new tag to the list.
     * @param name The name of the tag to be added.
     * @retval OPENDAQ_IGNORED if a node with the `name` is already in the list of tags.
     */
    daqErrCode EXPORTED daqTagsPrivate_add(daqTagsPrivate* self, daqString* name);

    /*!
     * @brief Removes a new tag from the list.
     * @param name The name of the tag to be removed.
     * @retval OPENDAQ_IGNORED if a node with the `name` is not in the list of tags.
     */
    daqErrCode EXPORTED daqTagsPrivate_remove(daqTagsPrivate* self, daqString* name);

    /*!
     * @brief Replaces all tags.
     * @param tags The new list of tags.
     */
    daqErrCode EXPORTED daqTagsPrivate_replace(daqTagsPrivate* self, daqList* tags DAQ_LIST_ELEMENT_TYPE(daqString));

#ifdef __cplusplus
}
#endif
