= Setting up (C#)

To start working with openDAQ(TM), the requisite binaries are required. They can be obtained at {docs-website}[the openDAQ(TM) documentation and releases webpage] or from http://nuget.org (recommended way). 

NOTE: The .NET binaries are currently only available in the Windows(TM) SDK packages. For Linux(TM) they are included in the NuGet package, although here the .NET Bindings are not tested.  

All commands in this guide use the .NET command-line interface (dotnet CLI) which is a cross-platform toolchain for developing, building, running, and publishing .NET applications.

== Creating an openDAQ(TM) project

Below, we start a Console Project in Visual Studio(TM) from scratch but there are also example files which can be found in the examples archive from the {docs-website}[openDAQ(TM) documentation and releases webpage].

=== Requirements

[tabs]
====
Windows::
+
--
 * .NET compiler, e.g.
   - https://learn.microsoft.com/en-us/dotnet/core/sdk[.NET SDK] (used in this guide).
   - Visual Studio 2022(TM).
   - Visual Studio Code with extension "C# Dev Kit".
--

Linux::
+
--
 * Ubuntu 22.04 (see also the note below).
 * On Windows(TM) users can just cross-compile the project for Linux(TM) using the Windows(TM)-requirements (used in this guide).
 * For development (not tested) and running on Linux(TM): +
   https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?tabs=dotnet8&pivots=os-linux-ubuntu-2204[Install .NET SDK or .NET Runtime on Ubuntu].

NOTE: On Windows there is the https://learn.microsoft.com/en-us/windows/wsl/install[Windows Subsystem for Linux (WSL)] where the cross-compiled executables can be tested.
--
====

In general everything around .NET can be found here: +
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

=== Creating and building the project

In this guide we use a `Developer PowerShell for VS2022` prompt on Windows(TM) for creating and (cross-) building the project. +
For the cross-compilation we use a `bash` prompt on Linux(TM) (or WSL on Windows(TM)) to run the result.

To start, create a `csharp/quick_start` directory and navigate to it.

With  the following commands we first create an empty (.NET8.0) console application project and then we add the _openDAQ.Net_ Bindings NuGet package reference to the project, which contains all the needed binaries.

[source,shell]
----
dotnet new console
dotnet add package openDAQ.Net
----

With this, we are ready to start developing: +
We fill in our `Program.cs` executable code as follows (replacing the default content):

[source,csharp]
----
using Daq.Core.Types;
using Daq.Core.Objects;
using Daq.Core.OpenDAQ;

// Create a fresh openDAQ(TM) instance, which acts as the entry point into our application
Console.WriteLine("create instance...");
var instance = OpenDAQFactory.Instance();

Console.WriteLine();
Console.WriteLine($"successfully created the instance '{instance.Name}'");

Console.WriteLine();
Console.Write("Press a key to exit the application ...");
Console.ReadKey(intercept: true);
----

NOTE: When creating the openDAQ(TM) `instance`, we don't need to specify the root directory of our openDAQ(TM) Modules as they are conveniently being deployed by the NuGet package and found where they are.

Now we can compile and run our program in our PowerShell(TM) instance from above.

[tabs]
====
Windows::
+
--
[source,shell]
----
dotnet run
----
--

Linux::
+
--
Cross-compiling on Windows(TM) and running the result on Linux(TM) using WSL:
[source,shell]
----
dotnet build --runtime linux-x64
wsl
cd ./bin/Debug/net8.0/linux-x64/
./quick_start
exit
----

NOTE: `dotnet build --runtime linux-x64` builds the console application for Linux(TM) and uses the associated binaries from the NuGet package. The result (`./bin/Debug/net8.0/linux-x64/quick_start`) can then be run in WSL under Ubuntu 22.04 (see Requirements above).
--
====

With the `run` command the project is being built (when there was a change after the last run) and the resulting `quick_start.exe` executed. +
All binaries from the Nuget package will be copied to the target directory (which defaults to `./bin/Debug/net8.0`). These dependencies are also entered in the file `quick_start.deps.json` so that the executable can find the openDAQ(TM) SDK binaries during execution.  

Congratulations, if you managed to reach this point, you have successfully created your first openDAQ(TM) project! +
To find out more about using openDAQ(TM) applications to connect to, configure, and read data of Devices, continue with the xref:quick_start_application.adoc[openDAQ(TM) application quick start guide].
