= Setting up (Python)

Pre-built packages of Python bindings for the openDAQ(TM) SDK are currently only available for:

 * 64-bit Windows 
 * x86_64 Linux (built on manylinux 2014, requires GLIBC >= 2.17)

On supported systems you can install it with:
[source,bash]
----
pip install opendaq
----

== Installing latest (development) Python bindings

The latest versions of the Python bindings are available at https://www.docs-dev.opendaq.com. There you can downlowd the Python Wheels for your OS/Python version. 

The python version the wheel is intended for can be discerned from the name of the file. Eg. opendaq-3.2.8_ad68082-cp310-cp310-win_amd64.whl is to be used with Python 3.10, as indicated by the "cp310" part of the filename.

== Prerequisites

Python *3.8-12* for Windows can be downloaded from https://www.python.org/downloads/. On Linux it can be installed via the package manager.

== Testing the installation

To test the installation, start the Python interactive shell (type `python`) from the directory where the binaries live and type:

[source,python]
----
import opendaq as daq

instance = daq.Instance()
for device_info in instance.available_devices:
    print("Name:", device_info.name, "Connection string:", device_info.connection_string)
----

When using just a reference module without being connected to a physical device, the expected output will be something similar to:

[source]
----
Name: Device 0 Connection string: daqref://device0
Name: Device 1 Connection string: daqref://device1
----

== Python application

The Python pip package comes bundled with a simple openDAQ(TM) application. It can be run from a terminal using the following command:

[source,bash]
----
py -m opendaq
----