//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:41.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/opendaq/instance.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID INSTANCE_INTF_ID = { daq::IInstance::Id.Data1, daq::IInstance::Id.Data2, daq::IInstance::Id.Data3, daq::IInstance::Id.Data4_UInt64 };

ErrCode Instance_getModuleManager(Instance* self, ModuleManager** manager)
{
    return reinterpret_cast<daq::IInstance*>(self)->getModuleManager(reinterpret_cast<daq::IModuleManager**>(manager));
}

ErrCode Instance_getRootDevice(Instance* self, Device** rootDevice)
{
    return reinterpret_cast<daq::IInstance*>(self)->getRootDevice(reinterpret_cast<daq::IDevice**>(rootDevice));
}

ErrCode Instance_setRootDevice(Instance* self, String* connectionString, PropertyObject* config)
{
    return reinterpret_cast<daq::IInstance*>(self)->setRootDevice(reinterpret_cast<daq::IString*>(connectionString), reinterpret_cast<daq::IPropertyObject*>(config));
}

ErrCode Instance_getAvailableServerTypes(Instance* self, Dict** serverTypes)
{
    return reinterpret_cast<daq::IInstance*>(self)->getAvailableServerTypes(reinterpret_cast<daq::IDict**>(serverTypes));
}

ErrCode Instance_addStandardServers(Instance* self, List** servers)
{
    return reinterpret_cast<daq::IInstance*>(self)->addStandardServers(reinterpret_cast<daq::IList**>(servers));
}

ErrCode Instance_createInstance(Instance** obj, Context* context, String* localId)
{
    daq::IInstance* ptr = nullptr;
    ErrCode err = daq::createInstance(&ptr, reinterpret_cast<daq::IContext*>(context), reinterpret_cast<daq::IString*>(localId));
    *obj = reinterpret_cast<Instance*>(ptr);
    return err;
}

ErrCode Instance_createInstanceFromBuilder(Instance** obj, InstanceBuilder* builder)
{
    daq::IInstance* ptr = nullptr;
    ErrCode err = daq::createInstanceFromBuilder(&ptr, reinterpret_cast<daq::IInstanceBuilder*>(builder));
    *obj = reinterpret_cast<Instance*>(ptr);
    return err;
}

ErrCode Device_createClient(Device** obj, Context* ctx, String* localId, DeviceInfo* defaultDeviceInfo, Component* parent)
{
    daq::IDevice* ptr = nullptr;
    ErrCode err = daq::createClient(&ptr, reinterpret_cast<daq::IContext*>(ctx), reinterpret_cast<daq::IString*>(localId), reinterpret_cast<daq::IDeviceInfo*>(defaultDeviceInfo), reinterpret_cast<daq::IComponent*>(parent));
    *obj = reinterpret_cast<Device*>(ptr);
    return err;
}
