name: 🚀 Feature request
description: Request a new feature
title: "[FEATURE] <title here>"
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: What feature would you like to see implemented within the openDAQ SDK?
    description: A concise description of what you would like to see implemented.
  validations:
    required: true
