//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:16.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/component/component_update_context.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID COMPONENT_UPDATE_CONTEXT_INTF_ID = { daq::IComponentUpdateContext::Id.Data1, daq::IComponentUpdateContext::Id.Data2, daq::IComponentUpdateContext::Id.Data3, daq::IComponentUpdateContext::Id.Data4_UInt64 };

ErrCode ComponentUpdateContext_setInputPortConnection(ComponentUpdateContext* self, String* parentId, String* portId, String* signalId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->setInputPortConnection(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IString*>(portId), reinterpret_cast<daq::IString*>(signalId));
}

ErrCode ComponentUpdateContext_getInputPortConnections(ComponentUpdateContext* self, String* parentId, Dict** connections)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getInputPortConnections(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IDict**>(connections));
}

ErrCode ComponentUpdateContext_removeInputPortConnection(ComponentUpdateContext* self, String* parentId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->removeInputPortConnection(reinterpret_cast<daq::IString*>(parentId));
}

ErrCode ComponentUpdateContext_getRootComponent(ComponentUpdateContext* self, Component** rootComponent)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getRootComponent(reinterpret_cast<daq::IComponent**>(rootComponent));
}

ErrCode ComponentUpdateContext_getSignal(ComponentUpdateContext* self, String* parentId, String* portId, Signal** signal)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getSignal(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IString*>(portId), reinterpret_cast<daq::ISignal**>(signal));
}

ErrCode ComponentUpdateContext_setSignalDependency(ComponentUpdateContext* self, String* signalId, String* parentId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->setSignalDependency(reinterpret_cast<daq::IString*>(signalId), reinterpret_cast<daq::IString*>(parentId));
}

ErrCode ComponentUpdateContext_getReAddDevicesEnabled(ComponentUpdateContext* self, Bool* enabled)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getReAddDevicesEnabled(enabled);
}
