//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:13.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/component/component_status_container_private.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID COMPONENT_STATUS_CONTAINER_PRIVATE_INTF_ID = { daq::IComponentStatusContainerPrivate::Id.Data1, daq::IComponentStatusContainerPrivate::Id.Data2, daq::IComponentStatusContainerPrivate::Id.Data3, daq::IComponentStatusContainerPrivate::Id.Data4_UInt64 };

ErrCode ComponentStatusContainerPrivate_addStatus(ComponentStatusContainerPrivate* self, String* name, Enumeration* initialValue)
{
    return reinterpret_cast<daq::IComponentStatusContainerPrivate*>(self)->addStatus(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(initialValue));
}

ErrCode ComponentStatusContainerPrivate_setStatus(ComponentStatusContainerPrivate* self, String* name, Enumeration* value)
{
    return reinterpret_cast<daq::IComponentStatusContainerPrivate*>(self)->setStatus(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(value));
}

ErrCode ComponentStatusContainerPrivate_addStatusWithMessage(ComponentStatusContainerPrivate* self, String* name, Enumeration* initialValue, String* message)
{
    return reinterpret_cast<daq::IComponentStatusContainerPrivate*>(self)->addStatusWithMessage(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(initialValue), reinterpret_cast<daq::IString*>(message));
}

ErrCode ComponentStatusContainerPrivate_setStatusWithMessage(ComponentStatusContainerPrivate* self, String* name, Enumeration* value, String* message)
{
    return reinterpret_cast<daq::IComponentStatusContainerPrivate*>(self)->setStatusWithMessage(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(value), reinterpret_cast<daq::IString*>(message));
}
