//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:11.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/component/component_deserialize_context.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID COMPONENT_DESERIALIZE_CONTEXT_INTF_ID = { daq::IComponentDeserializeContext::Id.Data1, daq::IComponentDeserializeContext::Id.Data2, daq::IComponentDeserializeContext::Id.Data3, daq::IComponentDeserializeContext::Id.Data4_UInt64 };

ErrCode ComponentDeserializeContext_getParent(ComponentDeserializeContext* self, Component** parent)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getParent(reinterpret_cast<daq::IComponent**>(parent));
}

ErrCode ComponentDeserializeContext_getRoot(ComponentDeserializeContext* self, Component** root)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getRoot(reinterpret_cast<daq::IComponent**>(root));
}

ErrCode ComponentDeserializeContext_getLocalId(ComponentDeserializeContext* self, String** localId)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getLocalId(reinterpret_cast<daq::IString**>(localId));
}

ErrCode ComponentDeserializeContext_getContext(ComponentDeserializeContext* self, Context** context)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getContext(reinterpret_cast<daq::IContext**>(context));
}

ErrCode ComponentDeserializeContext_getIntfID(ComponentDeserializeContext* self, IntfID* intfID)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getIntfID(copendaq::utils::toDaqIntfId(intfID));
}

ErrCode ComponentDeserializeContext_getTriggerCoreEvent(ComponentDeserializeContext* self, Procedure** triggerCoreEvent)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->getTriggerCoreEvent(reinterpret_cast<daq::IProcedure**>(triggerCoreEvent));
}

ErrCode ComponentDeserializeContext_clone(ComponentDeserializeContext* self, Component* newParent, String* newLocalId, ComponentDeserializeContext** newComponentDeserializeContext, IntfID* newIntfID, Procedure* newTriggerCoreEvent)
{
    return reinterpret_cast<daq::IComponentDeserializeContext*>(self)->clone(reinterpret_cast<daq::IComponent*>(newParent), reinterpret_cast<daq::IString*>(newLocalId), reinterpret_cast<daq::IComponentDeserializeContext**>(newComponentDeserializeContext), copendaq::utils::toDaqIntfId(newIntfID), reinterpret_cast<daq::IProcedure*>(newTriggerCoreEvent));
}

ErrCode ComponentDeserializeContext_createComponentDeserializeContext(ComponentDeserializeContext** obj, Context* context, Component* root, Component* parent, String* localId, IntfID* intfID, Procedure* triggerCoreEvent)
{
    daq::IComponentDeserializeContext* ptr = nullptr;
    ErrCode err = daq::createComponentDeserializeContext(&ptr, reinterpret_cast<daq::IContext*>(context), reinterpret_cast<daq::IComponent*>(root), reinterpret_cast<daq::IComponent*>(parent), reinterpret_cast<daq::IString*>(localId), copendaq::utils::toDaqIntfId(intfID), reinterpret_cast<daq::IProcedure*>(triggerCoreEvent));
    *obj = reinterpret_cast<ComponentDeserializeContext*>(ptr);
    return err;
}
