//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:07.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/component/folder.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID FOLDER_INTF_ID = { daq::IFolder::Id.Data1, daq::IFolder::Id.Data2, daq::IFolder::Id.Data3, daq::IFolder::Id.Data4_UInt64 };

ErrCode Folder_getItems(Folder* self, List** items, SearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IFolder*>(self)->getItems(reinterpret_cast<daq::IList**>(items), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

ErrCode Folder_isEmpty(Folder* self, Bool* empty)
{
    return reinterpret_cast<daq::IFolder*>(self)->isEmpty(empty);
}

ErrCode Folder_hasItem(Folder* self, String* localId, Bool* value)
{
    return reinterpret_cast<daq::IFolder*>(self)->hasItem(reinterpret_cast<daq::IString*>(localId), value);
}

ErrCode Folder_getItem(Folder* self, String* localId, Component** item)
{
    return reinterpret_cast<daq::IFolder*>(self)->getItem(reinterpret_cast<daq::IString*>(localId), reinterpret_cast<daq::IComponent**>(item));
}
