//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:25.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/device/device_domain.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID DEVICE_DOMAIN_INTF_ID = { daq::IDeviceDomain::Id.Data1, daq::IDeviceDomain::Id.Data2, daq::IDeviceDomain::Id.Data3, daq::IDeviceDomain::Id.Data4_UInt64 };

ErrCode DeviceDomain_getTickResolution(DeviceDomain* self, Ratio** tickResolution)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getTickResolution(reinterpret_cast<daq::IRatio**>(tickResolution));
}

ErrCode DeviceDomain_getOrigin(DeviceDomain* self, String** origin)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getOrigin(reinterpret_cast<daq::IString**>(origin));
}

ErrCode DeviceDomain_getUnit(DeviceDomain* self, Unit** unit)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getUnit(reinterpret_cast<daq::IUnit**>(unit));
}

ErrCode DeviceDomain_getReferenceDomainInfo(DeviceDomain* self, ReferenceDomainInfo** referenceDomainInfo)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getReferenceDomainInfo(reinterpret_cast<daq::IReferenceDomainInfo**>(referenceDomainInfo));
}

ErrCode DeviceDomain_createDeviceDomain(DeviceDomain** obj, Ratio* tickResolution, String* origin, Unit* unit)
{
    daq::IDeviceDomain* ptr = nullptr;
    ErrCode err = daq::createDeviceDomain(&ptr, reinterpret_cast<daq::IRatio*>(tickResolution), reinterpret_cast<daq::IString*>(origin), reinterpret_cast<daq::IUnit*>(unit));
    *obj = reinterpret_cast<DeviceDomain*>(ptr);
    return err;
}

ErrCode DeviceDomain_createDeviceDomainWithReferenceDomainInfo(DeviceDomain** obj, Ratio* tickResolution, String* origin, Unit* unit, ReferenceDomainInfo* referenceDomainInfo)
{
    daq::IDeviceDomain* ptr = nullptr;
    ErrCode err = daq::createDeviceDomainWithReferenceDomainInfo(&ptr, reinterpret_cast<daq::IRatio*>(tickResolution), reinterpret_cast<daq::IString*>(origin), reinterpret_cast<daq::IUnit*>(unit), reinterpret_cast<daq::IReferenceDomainInfo*>(referenceDomainInfo));
    *obj = reinterpret_cast<DeviceDomain*>(ptr);
    return err;
}
