//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:04.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/device/device_domain.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_DEVICE_DOMAIN_INTF_ID = { daq::IDeviceDomain::Id.Data1, daq::IDeviceDomain::Id.Data2, daq::IDeviceDomain::Id.Data3, daq::IDeviceDomain::Id.Data4_UInt64 };

daqErrCode daqDeviceDomain_getTickResolution(daqDeviceDomain* self, daqRatio** tickResolution)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getTickResolution(reinterpret_cast<daq::IRatio**>(tickResolution));
}

daqErrCode daqDeviceDomain_getOrigin(daqDeviceDomain* self, daqString** origin)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getOrigin(reinterpret_cast<daq::IString**>(origin));
}

daqErrCode daqDeviceDomain_getUnit(daqDeviceDomain* self, daqUnit** unit)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getUnit(reinterpret_cast<daq::IUnit**>(unit));
}

daqErrCode daqDeviceDomain_getReferenceDomainInfo(daqDeviceDomain* self, daqReferenceDomainInfo** referenceDomainInfo)
{
    return reinterpret_cast<daq::IDeviceDomain*>(self)->getReferenceDomainInfo(reinterpret_cast<daq::IReferenceDomainInfo**>(referenceDomainInfo));
}

daqErrCode daqDeviceDomain_createDeviceDomain(daqDeviceDomain** obj, daqRatio* tickResolution, daqString* origin, daqUnit* unit)
{
    daq::IDeviceDomain* ptr = nullptr;
    daqErrCode err = daq::createDeviceDomain(&ptr, reinterpret_cast<daq::IRatio*>(tickResolution), reinterpret_cast<daq::IString*>(origin), reinterpret_cast<daq::IUnit*>(unit));
    *obj = reinterpret_cast<daqDeviceDomain*>(ptr);
    return err;
}

daqErrCode daqDeviceDomain_createDeviceDomainWithReferenceDomainInfo(daqDeviceDomain** obj, daqRatio* tickResolution, daqString* origin, daqUnit* unit, daqReferenceDomainInfo* referenceDomainInfo)
{
    daq::IDeviceDomain* ptr = nullptr;
    daqErrCode err = daq::createDeviceDomainWithReferenceDomainInfo(&ptr, reinterpret_cast<daq::IRatio*>(tickResolution), reinterpret_cast<daq::IString*>(origin), reinterpret_cast<daq::IUnit*>(unit), reinterpret_cast<daq::IReferenceDomainInfo*>(referenceDomainInfo));
    *obj = reinterpret_cast<daqDeviceDomain*>(ptr);
    return err;
}
