//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:19.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/device/device_type.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID DEVICE_TYPE_INTF_ID = { daq::IDeviceType::Id.Data1, daq::IDeviceType::Id.Data2, daq::IDeviceType::Id.Data3, daq::IDeviceType::Id.Data4_UInt64 };

ErrCode DeviceType_getConnectionStringPrefix(DeviceType* self, String** prefix)
{
    return reinterpret_cast<daq::IDeviceType*>(self)->getConnectionStringPrefix(reinterpret_cast<daq::IString**>(prefix));
}

ErrCode DeviceType_createDeviceType(DeviceType** obj, String* id, String* name, String* description, PropertyObject* defaultConfig, String* prefix)
{
    daq::IDeviceType* ptr = nullptr;
    ErrCode err = daq::createDeviceType(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::IPropertyObject*>(defaultConfig), reinterpret_cast<daq::IString*>(prefix));
    *obj = reinterpret_cast<DeviceType*>(ptr);
    return err;
}
