//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:22.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/device/server_capability.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID SERVER_CAPABILITY_INTF_ID = { daq::IServerCapability::Id.Data1, daq::IServerCapability::Id.Data2, daq::IServerCapability::Id.Data3, daq::IServerCapability::Id.Data4_UInt64 };

ErrCode ServerCapability_getConnectionString(ServerCapability* self, String** connectionString)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

ErrCode ServerCapability_getConnectionStrings(ServerCapability* self, List** connectionStrings)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getConnectionStrings(reinterpret_cast<daq::IList**>(connectionStrings));
}

ErrCode ServerCapability_getProtocolName(ServerCapability* self, String** protocolName)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getProtocolName(reinterpret_cast<daq::IString**>(protocolName));
}

ErrCode ServerCapability_getProtocolId(ServerCapability* self, String** protocolId)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getProtocolId(reinterpret_cast<daq::IString**>(protocolId));
}

ErrCode ServerCapability_getProtocolType(ServerCapability* self, ProtocolType* type)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getProtocolType(reinterpret_cast<daq::ProtocolType*>(type));
}

ErrCode ServerCapability_getPrefix(ServerCapability* self, String** prefix)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getPrefix(reinterpret_cast<daq::IString**>(prefix));
}

ErrCode ServerCapability_getConnectionType(ServerCapability* self, String** type)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getConnectionType(reinterpret_cast<daq::IString**>(type));
}

ErrCode ServerCapability_getCoreEventsEnabled(ServerCapability* self, Bool* enabled)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getCoreEventsEnabled(enabled);
}

ErrCode ServerCapability_getAddresses(ServerCapability* self, List** addresses)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getAddresses(reinterpret_cast<daq::IList**>(addresses));
}

ErrCode ServerCapability_getPort(ServerCapability* self, Integer** port)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getPort(reinterpret_cast<daq::IInteger**>(port));
}

ErrCode ServerCapability_getAddressInfo(ServerCapability* self, List** addressInfo)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getAddressInfo(reinterpret_cast<daq::IList**>(addressInfo));
}

ErrCode ServerCapability_getProtocolVersion(ServerCapability* self, String** version)
{
    return reinterpret_cast<daq::IServerCapability*>(self)->getProtocolVersion(reinterpret_cast<daq::IString**>(version));
}
