//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:23.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/device/user_lock.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID USER_LOCK_INTF_ID = { daq::IUserLock::Id.Data1, daq::IUserLock::Id.Data2, daq::IUserLock::Id.Data3, daq::IUserLock::Id.Data4_UInt64 };

ErrCode UserLock_lock(UserLock* self, User* user)
{
    return reinterpret_cast<daq::IUserLock*>(self)->lock(reinterpret_cast<daq::IUser*>(user));
}

ErrCode UserLock_unlock(UserLock* self, User* user)
{
    return reinterpret_cast<daq::IUserLock*>(self)->unlock(reinterpret_cast<daq::IUser*>(user));
}

ErrCode UserLock_forceUnlock(UserLock* self)
{
    return reinterpret_cast<daq::IUserLock*>(self)->forceUnlock();
}

ErrCode UserLock_isLocked(UserLock* self, Bool* isLockedOut)
{
    return reinterpret_cast<daq::IUserLock*>(self)->isLocked(isLockedOut);
}

ErrCode UserLock_createUserLock(UserLock** obj)
{
    daq::IUserLock* ptr = nullptr;
    ErrCode err = daq::createUserLock(&ptr);
    *obj = reinterpret_cast<UserLock*>(ptr);
    return err;
}
