//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:33.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/functionblock/function_block.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID FUNCTION_BLOCK_INTF_ID = { daq::IFunctionBlock::Id.Data1, daq::IFunctionBlock::Id.Data2, daq::IFunctionBlock::Id.Data3, daq::IFunctionBlock::Id.Data4_UInt64 };

ErrCode FunctionBlock_getFunctionBlockType(FunctionBlock* self, FunctionBlockType** type)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getFunctionBlockType(reinterpret_cast<daq::IFunctionBlockType**>(type));
}

ErrCode FunctionBlock_getInputPorts(FunctionBlock* self, List** ports, SearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getInputPorts(reinterpret_cast<daq::IList**>(ports), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

ErrCode FunctionBlock_getSignals(FunctionBlock* self, List** signals, SearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getSignals(reinterpret_cast<daq::IList**>(signals), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

ErrCode FunctionBlock_getSignalsRecursive(FunctionBlock* self, List** signals, SearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getSignalsRecursive(reinterpret_cast<daq::IList**>(signals), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

ErrCode FunctionBlock_getStatusSignal(FunctionBlock* self, Signal** statusSignal)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getStatusSignal(reinterpret_cast<daq::ISignal**>(statusSignal));
}

ErrCode FunctionBlock_getFunctionBlocks(FunctionBlock* self, List** functionBlocks, SearchFilter* searchFilter)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getFunctionBlocks(reinterpret_cast<daq::IList**>(functionBlocks), reinterpret_cast<daq::ISearchFilter*>(searchFilter));
}

ErrCode FunctionBlock_getAvailableFunctionBlockTypes(FunctionBlock* self, Dict** functionBlockTypes)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->getAvailableFunctionBlockTypes(reinterpret_cast<daq::IDict**>(functionBlockTypes));
}

ErrCode FunctionBlock_addFunctionBlock(FunctionBlock* self, FunctionBlock** functionBlock, String* typeId, PropertyObject* config)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->addFunctionBlock(reinterpret_cast<daq::IFunctionBlock**>(functionBlock), reinterpret_cast<daq::IString*>(typeId), reinterpret_cast<daq::IPropertyObject*>(config));
}

ErrCode FunctionBlock_removeFunctionBlock(FunctionBlock* self, FunctionBlock* functionBlock)
{
    return reinterpret_cast<daq::IFunctionBlock*>(self)->removeFunctionBlock(reinterpret_cast<daq::IFunctionBlock*>(functionBlock));
}
