//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 01.04.2025 17:02:03.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoreobjects/callable_info.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID CALLABLE_INFO_INTF_ID = { daq::ICallableInfo::Id.Data1, daq::ICallableInfo::Id.Data2, daq::ICallableInfo::Id.Data3, daq::ICallableInfo::Id.Data4_UInt64 };

ErrCode CallableInfo_getReturnType(CallableInfo* self, CoreType* type)
{
    return reinterpret_cast<daq::ICallableInfo*>(self)->getReturnType(reinterpret_cast<daq::CoreType*>(type));
}

ErrCode CallableInfo_getArguments(CallableInfo* self, List** argumentInfo)
{
    return reinterpret_cast<daq::ICallableInfo*>(self)->getArguments(reinterpret_cast<daq::IList**>(argumentInfo));
}

ErrCode CallableInfo_isConst(CallableInfo* self, Bool* constFlag)
{
    return reinterpret_cast<daq::ICallableInfo*>(self)->isConst(constFlag);
}

ErrCode CallableInfo_createCallableInfo(CallableInfo** obj, List* argumentInfo, CoreType returnType, Bool constFlag)
{
    daq::ICallableInfo* ptr = nullptr;
    ErrCode err = daq::createCallableInfo(&ptr, reinterpret_cast<daq::IList*>(argumentInfo), static_cast<daq::CoreType>(returnType), constFlag);
    *obj = reinterpret_cast<CallableInfo*>(ptr);
    return err;
}
