//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:05:11.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/end_update_event_args.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_END_UPDATE_EVENT_ARGS_INTF_ID = { daq::IEndUpdateEventArgs::Id.Data1, daq::IEndUpdateEventArgs::Id.Data2, daq::IEndUpdateEventArgs::Id.Data3, daq::IEndUpdateEventArgs::Id.Data4_UInt64 };

daqErrCode daqEndUpdateEventArgs_getProperties(daqEndUpdateEventArgs* self, daqList** properties)
{
    return reinterpret_cast<daq::IEndUpdateEventArgs*>(self)->getProperties(reinterpret_cast<daq::IList**>(properties));
}

daqErrCode daqEndUpdateEventArgs_getIsParentUpdating(daqEndUpdateEventArgs* self, daqBool* isParentUpdating)
{
    return reinterpret_cast<daq::IEndUpdateEventArgs*>(self)->getIsParentUpdating(isParentUpdating);
}

daqErrCode daqEndUpdateEventArgs_createEndUpdateEventArgs(daqEndUpdateEventArgs** obj, daqList* properties, daqBool isParentUpdating)
{
    daq::IEndUpdateEventArgs* ptr = nullptr;
    daqErrCode err = daq::createEndUpdateEventArgs(&ptr, reinterpret_cast<daq::IList*>(properties), isParentUpdating);
    *obj = reinterpret_cast<daqEndUpdateEventArgs*>(ptr);
    return err;
}
