//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 06.06.2025 19:05:52.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/object_lock_guard.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_LOCK_GUARD_INTF_ID = { daq::ILockGuard::Id.Data1, daq::ILockGuard::Id.Data2, daq::ILockGuard::Id.Data3, daq::ILockGuard::Id.Data4_UInt64 };


