//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:05:14.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/permissions.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PERMISSIONS_INTF_ID = { daq::IPermissions::Id.Data1, daq::IPermissions::Id.Data2, daq::IPermissions::Id.Data3, daq::IPermissions::Id.Data4_UInt64 };

daqErrCode daqPermissions_getInherited(daqPermissions* self, daqBool* isInherited)
{
    return reinterpret_cast<daq::IPermissions*>(self)->getInherited(isInherited);
}

daqErrCode daqPermissions_getAllowed(daqPermissions* self, daqDict** permissions)
{
    return reinterpret_cast<daq::IPermissions*>(self)->getAllowed(reinterpret_cast<daq::IDict**>(permissions));
}

daqErrCode daqPermissions_getDenied(daqPermissions* self, daqDict** permissions)
{
    return reinterpret_cast<daq::IPermissions*>(self)->getDenied(reinterpret_cast<daq::IDict**>(permissions));
}
