//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:05:14.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/permission_mask_builder.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PERMISSION_MASK_BUILDER_INTF_ID = { daq::IPermissionMaskBuilder::Id.Data1, daq::IPermissionMaskBuilder::Id.Data2, daq::IPermissionMaskBuilder::Id.Data3, daq::IPermissionMaskBuilder::Id.Data4_UInt64 };

daqErrCode daqPermissionMaskBuilder_read(daqPermissionMaskBuilder* self)
{
    return reinterpret_cast<daq::IPermissionMaskBuilder*>(self)->read();
}

daqErrCode daqPermissionMaskBuilder_write(daqPermissionMaskBuilder* self)
{
    return reinterpret_cast<daq::IPermissionMaskBuilder*>(self)->write();
}

daqErrCode daqPermissionMaskBuilder_execute(daqPermissionMaskBuilder* self)
{
    return reinterpret_cast<daq::IPermissionMaskBuilder*>(self)->execute();
}

daqErrCode daqPermissionMaskBuilder_clear(daqPermissionMaskBuilder* self)
{
    return reinterpret_cast<daq::IPermissionMaskBuilder*>(self)->clear();
}

daqErrCode daqPermissionMaskBuilder_build(daqPermissionMaskBuilder* self, daqInt* permissionMask)
{
    return reinterpret_cast<daq::IPermissionMaskBuilder*>(self)->build(permissionMask);
}

daqErrCode daqPermissionMaskBuilder_createPermissionMaskBuilder(daqPermissionMaskBuilder** obj)
{
    daq::IPermissionMaskBuilder* ptr = nullptr;
    daqErrCode err = daq::createPermissionMaskBuilder(&ptr);
    *obj = reinterpret_cast<daqPermissionMaskBuilder*>(ptr);
    return err;
}

daqErrCode daqPermissionMaskBuilder_createPermissionMaskBuilderFromMask(daqPermissionMaskBuilder** obj, daqInt permissionMask)
{
    daq::IPermissionMaskBuilder* ptr = nullptr;
    daqErrCode err = daq::createPermissionMaskBuilderFromMask(&ptr, permissionMask);
    *obj = reinterpret_cast<daqPermissionMaskBuilder*>(ptr);
    return err;
}
