//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/permissions_internal.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PERMISSIONS_INTERNAL_INTF_ID = { daq::IPermissionsInternal::Id.Data1, daq::IPermissionsInternal::Id.Data2, daq::IPermissionsInternal::Id.Data3, daq::IPermissionsInternal::Id.Data4_UInt64 };

void daqPermissionsInternal_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PERMISSIONS_INTERNAL_INTF_ID;
}

daqErrCode daqPermissionsInternal_getAssigned(daqPermissionsInternal* self, daqDict** permissions)
{
    return reinterpret_cast<daq::IPermissionsInternal*>(self)->getAssigned(reinterpret_cast<daq::IDict**>(permissions));
}
