//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 06.06.2025 19:05:53.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/permission_manager_internal.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PERMISSION_MANAGER_INTERNAL_INTF_ID = { daq::IPermissionManagerInternal::Id.Data1, daq::IPermissionManagerInternal::Id.Data2, daq::IPermissionManagerInternal::Id.Data3, daq::IPermissionManagerInternal::Id.Data4_UInt64 };

daqErrCode daqPermissionManagerInternal_setParent(daqPermissionManagerInternal* self, daqPermissionManager* parentManager)
{
    return reinterpret_cast<daq::IPermissionManagerInternal*>(self)->setParent(reinterpret_cast<daq::IPermissionManager*>(parentManager));
}

daqErrCode daqPermissionManagerInternal_addChildManager(daqPermissionManagerInternal* self, daqPermissionManager* childManager)
{
    return reinterpret_cast<daq::IPermissionManagerInternal*>(self)->addChildManager(reinterpret_cast<daq::IPermissionManager*>(childManager));
}

daqErrCode daqPermissionManagerInternal_removeChildManager(daqPermissionManagerInternal* self, daqPermissionManager* childManager)
{
    return reinterpret_cast<daq::IPermissionManagerInternal*>(self)->removeChildManager(reinterpret_cast<daq::IPermissionManager*>(childManager));
}

daqErrCode daqPermissionManagerInternal_getPermissions(daqPermissionManagerInternal* self, daqPermissions** permissionsOut)
{
    return reinterpret_cast<daq::IPermissionManagerInternal*>(self)->getPermissions(reinterpret_cast<daq::IPermissions**>(permissionsOut));
}

daqErrCode daqPermissionManagerInternal_updateInheritedPermissions(daqPermissionManagerInternal* self)
{
    return reinterpret_cast<daq::IPermissionManagerInternal*>(self)->updateInheritedPermissions();
}
