//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 05.06.2025 21:36:42.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/property_object.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROPERTY_OBJECT_INTF_ID = { daq::IPropertyObject::Id.Data1, daq::IPropertyObject::Id.Data2, daq::IPropertyObject::Id.Data3, daq::IPropertyObject::Id.Data4_UInt64 };

daqErrCode daqPropertyObject_getClassName(daqPropertyObject* self, daqString** className)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getClassName(reinterpret_cast<daq::IString**>(className));
}

daqErrCode daqPropertyObject_setPropertyValue(daqPropertyObject* self, daqString* propertyName, daqBaseObject* value)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->setPropertyValue(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IBaseObject*>(value));
}

daqErrCode daqPropertyObject_getPropertyValue(daqPropertyObject* self, daqString* propertyName, daqBaseObject** value)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getPropertyValue(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqPropertyObject_getPropertySelectionValue(daqPropertyObject* self, daqString* propertyName, daqBaseObject** value)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getPropertySelectionValue(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqPropertyObject_clearPropertyValue(daqPropertyObject* self, daqString* propertyName)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->clearPropertyValue(reinterpret_cast<daq::IString*>(propertyName));
}

daqErrCode daqPropertyObject_hasProperty(daqPropertyObject* self, daqString* propertyName, daqBool* hasProperty)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->hasProperty(reinterpret_cast<daq::IString*>(propertyName), hasProperty);
}

daqErrCode daqPropertyObject_getProperty(daqPropertyObject* self, daqString* propertyName, daqProperty** property)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getProperty(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IProperty**>(property));
}

daqErrCode daqPropertyObject_addProperty(daqPropertyObject* self, daqProperty* property)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->addProperty(reinterpret_cast<daq::IProperty*>(property));
}

daqErrCode daqPropertyObject_removeProperty(daqPropertyObject* self, daqString* propertyName)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->removeProperty(reinterpret_cast<daq::IString*>(propertyName));
}

daqErrCode daqPropertyObject_getOnPropertyValueWrite(daqPropertyObject* self, daqString* propertyName, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getOnPropertyValueWrite(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyObject_getOnPropertyValueRead(daqPropertyObject* self, daqString* propertyName, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getOnPropertyValueRead(reinterpret_cast<daq::IString*>(propertyName), reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyObject_getOnAnyPropertyValueWrite(daqPropertyObject* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getOnAnyPropertyValueWrite(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyObject_getOnAnyPropertyValueRead(daqPropertyObject* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getOnAnyPropertyValueRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyObject_getVisibleProperties(daqPropertyObject* self, daqList** properties)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getVisibleProperties(reinterpret_cast<daq::IList**>(properties));
}

daqErrCode daqPropertyObject_getAllProperties(daqPropertyObject* self, daqList** properties)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getAllProperties(reinterpret_cast<daq::IList**>(properties));
}

daqErrCode daqPropertyObject_setPropertyOrder(daqPropertyObject* self, daqList* orderedPropertyNames)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->setPropertyOrder(reinterpret_cast<daq::IList*>(orderedPropertyNames));
}

daqErrCode daqPropertyObject_beginUpdate(daqPropertyObject* self)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->beginUpdate();
}

daqErrCode daqPropertyObject_endUpdate(daqPropertyObject* self)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->endUpdate();
}

daqErrCode daqPropertyObject_getUpdating(daqPropertyObject* self, daqBool* updating)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getUpdating(updating);
}

daqErrCode daqPropertyObject_getOnEndUpdate(daqPropertyObject* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getOnEndUpdate(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyObject_getPermissionManager(daqPropertyObject* self, daqPermissionManager** permissionManager)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->getPermissionManager(reinterpret_cast<daq::IPermissionManager**>(permissionManager));
}

daqErrCode daqPropertyObject_findProperties(daqPropertyObject* self, daqList** properties, daqSearchFilter* propertyFilter, daqSearchFilter* componentFilter)
{
    return reinterpret_cast<daq::IPropertyObject*>(self)->findProperties(reinterpret_cast<daq::IList**>(properties), reinterpret_cast<daq::ISearchFilter*>(propertyFilter), reinterpret_cast<daq::ISearchFilter*>(componentFilter));
}

daqErrCode daqPropertyObject_createPropertyObject(daqPropertyObject** obj)
{
    daq::IPropertyObject* ptr = nullptr;
    daqErrCode err = daq::createPropertyObject(&ptr);
    *obj = reinterpret_cast<daqPropertyObject*>(ptr);
    return err;
}

daqErrCode daqPropertyObject_createPropertyObjectWithClassAndManager(daqPropertyObject** obj, daqTypeManager* manager, daqString* className)
{
    daq::IPropertyObject* ptr = nullptr;
    daqErrCode err = daq::createPropertyObjectWithClassAndManager(&ptr, reinterpret_cast<daq::ITypeManager*>(manager), reinterpret_cast<daq::IString*>(className));
    *obj = reinterpret_cast<daqPropertyObject*>(ptr);
    return err;
}
