//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 01.04.2025 17:02:15.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoreobjects/unit_builder.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID UNIT_BUILDER_INTF_ID = { daq::IUnitBuilder::Id.Data1, daq::IUnitBuilder::Id.Data2, daq::IUnitBuilder::Id.Data3, daq::IUnitBuilder::Id.Data4_UInt64 };

ErrCode UnitBuilder_build(UnitBuilder* self, Unit** unit)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->build(reinterpret_cast<daq::IUnit**>(unit));
}

ErrCode UnitBuilder_setId(UnitBuilder* self, Int id)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->setId(id);
}

ErrCode UnitBuilder_getId(UnitBuilder* self, Int* id)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->getId(id);
}

ErrCode UnitBuilder_setSymbol(UnitBuilder* self, String* symbol)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->setSymbol(reinterpret_cast<daq::IString*>(symbol));
}

ErrCode UnitBuilder_getSymbol(UnitBuilder* self, String** symbol)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->getSymbol(reinterpret_cast<daq::IString**>(symbol));
}

ErrCode UnitBuilder_setName(UnitBuilder* self, String* name)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->setName(reinterpret_cast<daq::IString*>(name));
}

ErrCode UnitBuilder_getName(UnitBuilder* self, String** name)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->getName(reinterpret_cast<daq::IString**>(name));
}

ErrCode UnitBuilder_setQuantity(UnitBuilder* self, String* quantity)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->setQuantity(reinterpret_cast<daq::IString*>(quantity));
}

ErrCode UnitBuilder_getQuantity(UnitBuilder* self, String** quantity)
{
    return reinterpret_cast<daq::IUnitBuilder*>(self)->getQuantity(reinterpret_cast<daq::IString**>(quantity));
}

ErrCode UnitBuilder_createUnitBuilder(UnitBuilder** obj)
{
    daq::IUnitBuilder* ptr = nullptr;
    ErrCode err = daq::createUnitBuilder(&ptr);
    *obj = reinterpret_cast<UnitBuilder*>(ptr);
    return err;
}

ErrCode UnitBuilder_createUnitBuilderFromExisting(UnitBuilder** obj, Unit* unitToCopy)
{
    daq::IUnitBuilder* ptr = nullptr;
    ErrCode err = daq::createUnitBuilderFromExisting(&ptr, reinterpret_cast<daq::IUnit*>(unitToCopy));
    *obj = reinterpret_cast<UnitBuilder*>(ptr);
    return err;
}
