//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:48.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqEnumerationType daqEnumerationType;
    typedef struct daqList daqList;
    typedef struct daqDict daqDict;
    typedef struct daqString daqString;

    EXPORTED extern const daqIntfID DAQ_ENUMERATION_TYPE_INTF_ID;

    daqErrCode EXPORTED daqEnumerationType_getEnumeratorNames(daqEnumerationType* self, daqList** names);
    daqErrCode EXPORTED daqEnumerationType_getAsDictionary(daqEnumerationType* self, daqDict** dictionary);
    daqErrCode EXPORTED daqEnumerationType_getEnumeratorIntValue(daqEnumerationType* self, daqString* name, daqInt* value);
    daqErrCode EXPORTED daqEnumerationType_getCount(daqEnumerationType* self, daqSizeT* count);
    daqErrCode EXPORTED daqEnumerationType_createEnumerationType(daqEnumerationType** obj, daqString* typeName, daqList* enumeratorNames, daqInt firstEnumeratorIntValue);
    daqErrCode EXPORTED daqEnumerationType_createEnumerationTypeWithValues(daqEnumerationType** obj, daqString* typeName, daqDict* enumerators);

#ifdef __cplusplus
}
#endif
