//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:49.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqErrorInfo daqErrorInfo;
    typedef struct daqString daqString;

    EXPORTED extern const daqIntfID DAQ_ERROR_INFO_INTF_ID;

    daqErrCode EXPORTED daqErrorInfo_setMessage(daqErrorInfo* self, daqString* message);
    daqErrCode EXPORTED daqErrorInfo_getMessage(daqErrorInfo* self, daqString** message);
    daqErrCode EXPORTED daqErrorInfo_setSource(daqErrorInfo* self, daqString* source);
    daqErrCode EXPORTED daqErrorInfo_getSource(daqErrorInfo* self, daqString** source);
    daqErrCode EXPORTED daqErrorInfo_setFileName(daqErrorInfo* self, daqCharPtr fileName);
    daqErrCode EXPORTED daqErrorInfo_getFileName(daqErrorInfo* self, daqCharPtr* fileName);
    daqErrCode EXPORTED daqErrorInfo_setFileLine(daqErrorInfo* self, daqInt fileLine);
    daqErrCode EXPORTED daqErrorInfo_getFileLine(daqErrorInfo* self, daqInt* fileLine);
    daqErrCode EXPORTED daqErrorInfo_createErrorInfo(daqErrorInfo** obj);

#ifdef __cplusplus
}
#endif
