//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 12.03.2025 16:30:57.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct FloatObject FloatObject;

    ErrCode EXPORTED FloatObject_getValue(FloatObject* self, Float* value);
    ErrCode EXPORTED FloatObject_equalsValue(FloatObject* self, Float value, Bool* equals);
    ErrCode EXPORTED FloatObject_createFloat(FloatObject** obj, Float value);
    ErrCode EXPORTED FloatObject_createFloatObject(FloatObject** obj, Float value);

#ifdef __cplusplus
}
#endif
