//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    /*!
     * @brief Transforms a mutable object to an immutable object.
     *
     * If an object supports IFreezable interface, it is possible to transform it to immutable object.
     * Once the object is frozen, it should not allow to change any of its properties or internal state.
     */
    DAQ_EXTENDS_INTERFACE(daqFreezable, daqBaseObject);

    typedef struct daqFreezable daqFreezable;

    EXPORTED extern const daqIntfID DAQ_FREEZABLE_INTF_ID;
    void EXPORTED daqFreezable_getInterfaceId(daqIntfID* intfId);

    /*!
     * @brief Makes the object frozen/immutable. It should return OPENDAQ_IGNORED value if the object is already frozen.
     */
    daqErrCode EXPORTED daqFreezable_freeze(daqFreezable* self);

    /*!
     * @brief Checks if the objects is frozen/immutable.
     * @param[out] isFrozen The object's frozen/immutable state.
     */
    daqErrCode EXPORTED daqFreezable_isFrozen(daqFreezable* self, daqBool* isFrozen);

#ifdef __cplusplus
}
#endif
