//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 12.03.2025 16:30:58.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct Function Function;

    ErrCode EXPORTED Function_call(Function* self, BaseObject* params, BaseObject** result);
    ErrCode EXPORTED Function_createFunction(Function** obj, FuncCall value);

#ifdef __cplusplus
}
#endif
