//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 13.03.2025 21:47:25.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct SerializedObject SerializedObject;
typedef struct String String;
typedef struct SerializedList SerializedList;
typedef struct Function Function;
typedef struct List List;

    ErrCode EXPORTED SerializedObject_readSerializedObject(SerializedObject* self, String* key, SerializedObject** plainObj);
    ErrCode EXPORTED SerializedObject_readSerializedList(SerializedObject* self, String* key, SerializedList** list);
    ErrCode EXPORTED SerializedObject_readList(SerializedObject* self, String* key, BaseObject* context, Function* factoryCallback, List** list);
    ErrCode EXPORTED SerializedObject_readObject(SerializedObject* self, String* key, BaseObject* context, Function* factoryCallback, BaseObject** obj);
    ErrCode EXPORTED SerializedObject_readString(SerializedObject* self, String* key, String** string);
    ErrCode EXPORTED SerializedObject_readBool(SerializedObject* self, String* key, Bool* boolean);
    ErrCode EXPORTED SerializedObject_readFloat(SerializedObject* self, String* key, Float* real);
    ErrCode EXPORTED SerializedObject_readInt(SerializedObject* self, String* key, Int* integer);
    ErrCode EXPORTED SerializedObject_hasKey(SerializedObject* self, String* key, Bool* hasKey);
    ErrCode EXPORTED SerializedObject_getKeys(SerializedObject* self, List** list);
    ErrCode EXPORTED SerializedObject_getType(SerializedObject* self, String* key, CoreType* type);
    ErrCode EXPORTED SerializedObject_isRoot(SerializedObject* self, Bool* isRoot);
    ErrCode EXPORTED SerializedObject_toJson(SerializedObject* self, String** jsonString);

#ifdef __cplusplus
}
#endif
