//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 25.03.2025 01:13:33.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

    typedef struct Serializer Serializer;
    typedef struct Serializable Serializable;
    typedef struct String String;

    EXPORTED extern const IntfID SERIALIZER_INTF_ID;

    ErrCode EXPORTED Serializer_startTaggedObject(Serializer* self, Serializable* obj);
    ErrCode EXPORTED Serializer_startObject(Serializer* self);
    ErrCode EXPORTED Serializer_endObject(Serializer* self);
    ErrCode EXPORTED Serializer_startList(Serializer* self);
    ErrCode EXPORTED Serializer_endList(Serializer* self);
    ErrCode EXPORTED Serializer_getOutput(Serializer* self, String** serialized);
    ErrCode EXPORTED Serializer_key(Serializer* self, ConstCharPtr string);
    ErrCode EXPORTED Serializer_keyStr(Serializer* self, String* name);
    ErrCode EXPORTED Serializer_keyRaw(Serializer* self, ConstCharPtr string, SizeT length);
    ErrCode EXPORTED Serializer_writeInt(Serializer* self, Int integer);
    ErrCode EXPORTED Serializer_writeBool(Serializer* self, Bool boolean);
    ErrCode EXPORTED Serializer_writeFloat(Serializer* self, Float real);
    ErrCode EXPORTED Serializer_writeString(Serializer* self, ConstCharPtr string, SizeT length);
    ErrCode EXPORTED Serializer_writeNull(Serializer* self);
    ErrCode EXPORTED Serializer_reset(Serializer* self);
    ErrCode EXPORTED Serializer_isComplete(Serializer* self, Bool* complete);
    ErrCode EXPORTED Serializer_getUser(Serializer* self, BaseObject** user);
    ErrCode EXPORTED Serializer_setUser(Serializer* self, BaseObject* user);

#ifdef __cplusplus
}
#endif
