//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 13.03.2025 21:47:25.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct SimpleType SimpleType;

    ErrCode EXPORTED SimpleType_createSimpleType(SimpleType** obj, CoreType coreType);

#ifdef __cplusplus
}
#endif
