//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:50.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/event_args.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_EVENT_ARGS_INTF_ID = { daq::IEventArgs::Id.Data1, daq::IEventArgs::Id.Data2, daq::IEventArgs::Id.Data3, daq::IEventArgs::Id.Data4_UInt64 };

daqErrCode daqEventArgs_getEventId(daqEventArgs* self, daqInt* id)
{
    return reinterpret_cast<daq::IEventArgs*>(self)->getEventId(id);
}

daqErrCode daqEventArgs_getEventName(daqEventArgs* self, daqString** name)
{
    return reinterpret_cast<daq::IEventArgs*>(self)->getEventName(reinterpret_cast<daq::IString**>(name));
}

daqErrCode daqEventArgs_createEventArgs(daqEventArgs** obj, daqInt eventId, daqString* eventName)
{
    daq::IEventArgs* ptr = nullptr;
    daqErrCode err = daq::createEventArgs(&ptr, eventId, reinterpret_cast<daq::IString*>(eventName));
    *obj = reinterpret_cast<daqEventArgs*>(ptr);
    return err;
}
