//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 25.03.2025 01:13:28.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoretypes/function.h"

#include <opendaq/opendaq.h>

const IntfID FUNCTION_INTF_ID = { daq::IFunction::Id.Data1, daq::IFunction::Id.Data2, daq::IFunction::Id.Data3, daq::IFunction::Id.Data4_UInt64 };

ErrCode Function_call(Function* self, BaseObject* params, BaseObject** result)
{
    return reinterpret_cast<daq::IFunction*>(self)->call(reinterpret_cast<daq::IBaseObject*>(params), reinterpret_cast<daq::IBaseObject**>(result));
}

ErrCode Function_createFunction(Function** obj, FuncCall value)
{
    daq::IFunction* ptr = nullptr;
    ErrCode err = daq::createFunction(&ptr, reinterpret_cast<daq::FuncCall>(value)); // UB but could work
    *obj = reinterpret_cast<Function*>(ptr);
    return err;
}
