//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:32:46.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/iterator.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID ITERATOR_INTF_ID = { daq::IIterator::Id.Data1, daq::IIterator::Id.Data2, daq::IIterator::Id.Data3, daq::IIterator::Id.Data4_UInt64 };

ErrCode Iterator_moveNext(Iterator* self)
{
    return reinterpret_cast<daq::IIterator*>(self)->moveNext();
}

ErrCode Iterator_getCurrent(Iterator* self, BaseObject** obj)
{
    return reinterpret_cast<daq::IIterator*>(self)->getCurrent(reinterpret_cast<daq::IBaseObject**>(obj));
}
