//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 13.03.2025 21:47:22.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoretypes/iterable.h"

#include <opendaq/opendaq.h>

ErrCode Iterable_createStartIterator(Iterable* self, Iterator** iterator)
{
    return reinterpret_cast<daq::IIterable*>(self)->createStartIterator(reinterpret_cast<daq::IIterator**>(iterator));
}

ErrCode Iterable_createEndIterator(Iterable* self, Iterator** iterator)
{
    return reinterpret_cast<daq::IIterable*>(self)->createEndIterator(reinterpret_cast<daq::IIterator**>(iterator));
}
