//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:54.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/iterable.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ITERABLE_INTF_ID = { daq::IIterable::Id.Data1, daq::IIterable::Id.Data2, daq::IIterable::Id.Data3, daq::IIterable::Id.Data4_UInt64 };

daqErrCode daqIterable_createStartIterator(daqIterable* self, daqIterator** iterator)
{
    return reinterpret_cast<daq::IIterable*>(self)->createStartIterator(reinterpret_cast<daq::IIterator**>(iterator));
}

daqErrCode daqIterable_createEndIterator(daqIterable* self, daqIterator** iterator)
{
    return reinterpret_cast<daq::IIterable*>(self)->createEndIterator(reinterpret_cast<daq::IIterator**>(iterator));
}
