//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/list_element_type.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_LIST_ELEMENT_TYPE_INTF_ID = { daq::IListElementType::Id.Data1, daq::IListElementType::Id.Data2, daq::IListElementType::Id.Data3, daq::IListElementType::Id.Data4_UInt64 };

void daqListElementType_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_LIST_ELEMENT_TYPE_INTF_ID;
}

daqErrCode daqListElementType_getElementInterfaceId(daqListElementType* self, daqIntfID* id)
{
    return reinterpret_cast<daq::IListElementType*>(self)->getElementInterfaceId(copendaq::utils::toDaqIntfId(id));
}
