//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 05.03.2026 11:31:39.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/number.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_NUMBER_INTF_ID = { daq::INumber::Id.Data1, daq::INumber::Id.Data2, daq::INumber::Id.Data3, daq::INumber::Id.Data4_UInt64 };

void daqNumber_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_NUMBER_INTF_ID;
}

daqErrCode daqNumber_getFloatValue(daqNumber* self, daqFloat* value)
{
    return reinterpret_cast<daq::INumber*>(self)->getFloatValue(value);
}

daqErrCode daqNumber_getIntValue(daqNumber* self, daqInt* value)
{
    return reinterpret_cast<daq::INumber*>(self)->getIntValue(value);
}
