//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:58.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/serializable.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_SERIALIZABLE_INTF_ID = { daq::ISerializable::Id.Data1, daq::ISerializable::Id.Data2, daq::ISerializable::Id.Data3, daq::ISerializable::Id.Data4_UInt64 };

daqErrCode daqSerializable_serialize(daqSerializable* self, daqSerializer* serializer)
{
    return reinterpret_cast<daq::ISerializable*>(self)->serialize(reinterpret_cast<daq::ISerializer*>(serializer));
}

daqErrCode daqSerializable_getSerializeId(daqSerializable* self, daqConstCharPtr* id)
{
    return reinterpret_cast<daq::ISerializable*>(self)->getSerializeId(reinterpret_cast<daq::ConstCharPtr*>(id));
}
