//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 31.03.2025 16:56:31.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoretypes/stringobject.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID STRING_INTF_ID = { daq::IString::Id.Data1, daq::IString::Id.Data2, daq::IString::Id.Data3, daq::IString::Id.Data4_UInt64 };

ErrCode String_getCharPtr(String* self, ConstCharPtr* value)
{
    return reinterpret_cast<daq::IString*>(self)->getCharPtr(value);
}

ErrCode String_getLength(String* self, SizeT* size)
{
    return reinterpret_cast<daq::IString*>(self)->getLength(size);
}

ErrCode String_createString(String** obj, ConstCharPtr str)
{
    daq::IString* ptr = nullptr;
    ErrCode err = daq::createString(&ptr, str);
    *obj = reinterpret_cast<String*>(ptr);
    return err;
}

ErrCode String_createStringN(String** obj, ConstCharPtr str, SizeT length)
{
    daq::IString* ptr = nullptr;
    ErrCode err = daq::createStringN(&ptr, str, length);
    *obj = reinterpret_cast<String*>(ptr);
    return err;
}
