//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 13.03.2025 21:47:29.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoretypes/type_manager.h"

#include <opendaq/opendaq.h>

ErrCode TypeManager_addType(TypeManager* self, Type* type)
{
    return reinterpret_cast<daq::ITypeManager*>(self)->addType(reinterpret_cast<daq::IType*>(type));
}

ErrCode TypeManager_removeType(TypeManager* self, String* typeName)
{
    return reinterpret_cast<daq::ITypeManager*>(self)->removeType(reinterpret_cast<daq::IString*>(typeName));
}

ErrCode TypeManager_getType(TypeManager* self, String* typeName, Type** type)
{
    return reinterpret_cast<daq::ITypeManager*>(self)->getType(reinterpret_cast<daq::IString*>(typeName), reinterpret_cast<daq::IType**>(type));
}

ErrCode TypeManager_getTypes(TypeManager* self, List** types)
{
    return reinterpret_cast<daq::ITypeManager*>(self)->getTypes(reinterpret_cast<daq::IList**>(types));
}

ErrCode TypeManager_hasType(TypeManager* self, String* typeName, Bool* hasType)
{
    return reinterpret_cast<daq::ITypeManager*>(self)->hasType(reinterpret_cast<daq::IString*>(typeName), hasType);
}

ErrCode TypeManager_createTypeManager(TypeManager** obj)
{
    daq::ITypeManager* ptr = nullptr;
    ErrCode err = daq::createTypeManager(&ptr);
    *obj = reinterpret_cast<TypeManager*>(ptr);
    return err;
}
