//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 05.03.2026 11:31:43.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/type.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_TYPE_INTF_ID = { daq::IType::Id.Data1, daq::IType::Id.Data2, daq::IType::Id.Data3, daq::IType::Id.Data4_UInt64 };

void daqType_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_TYPE_INTF_ID;
}

daqErrCode daqType_getName(daqType* self, daqString** typeName)
{
    return reinterpret_cast<daq::IType*>(self)->getName(reinterpret_cast<daq::IString**>(typeName));
}
