//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:32:54.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/type_manager_private.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const IntfID TYPE_MANAGER_PRIVATE_INTF_ID = { daq::ITypeManagerPrivate::Id.Data1, daq::ITypeManagerPrivate::Id.Data2, daq::ITypeManagerPrivate::Id.Data3, daq::ITypeManagerPrivate::Id.Data4_UInt64 };

ErrCode TypeManagerPrivate_setCoreEventCallback(TypeManagerPrivate* self, Procedure* callback)
{
    return reinterpret_cast<daq::ITypeManagerPrivate*>(self)->setCoreEventCallback(reinterpret_cast<daq::IProcedure*>(callback));
}
