//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:18:05.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/updatable.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_UPDATABLE_INTF_ID = { daq::IUpdatable::Id.Data1, daq::IUpdatable::Id.Data2, daq::IUpdatable::Id.Data3, daq::IUpdatable::Id.Data4_UInt64 };

daqErrCode daqUpdatable_update(daqUpdatable* self, daqSerializedObject* update, daqBaseObject* config)
{
    return reinterpret_cast<daq::IUpdatable*>(self)->update(reinterpret_cast<daq::ISerializedObject*>(update), reinterpret_cast<daq::IBaseObject*>(config));
}

daqErrCode daqUpdatable_serializeForUpdate(daqUpdatable* self, daqSerializer* serializer)
{
    return reinterpret_cast<daq::IUpdatable*>(self)->serializeForUpdate(reinterpret_cast<daq::ISerializer*>(serializer));
}

daqErrCode daqUpdatable_updateEnded(daqUpdatable* self, daqBaseObject* context)
{
    return reinterpret_cast<daq::IUpdatable*>(self)->updateEnded(reinterpret_cast<daq::IBaseObject*>(context));
}

daqErrCode daqUpdatable_updateInternal(daqUpdatable* self, daqSerializedObject* update, daqBaseObject* context)
{
    return reinterpret_cast<daq::IUpdatable*>(self)->updateInternal(reinterpret_cast<daq::ISerializedObject*>(update), reinterpret_cast<daq::IBaseObject*>(context));
}
