//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 13.03.2025 21:47:30.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ccoretypes/version_info.h"

#include <opendaq/opendaq.h>

ErrCode VersionInfo_getMajor(VersionInfo* self, SizeT* major)
{
    return reinterpret_cast<daq::IVersionInfo*>(self)->getMajor(major);
}

ErrCode VersionInfo_getMinor(VersionInfo* self, SizeT* minor)
{
    return reinterpret_cast<daq::IVersionInfo*>(self)->getMinor(minor);
}

ErrCode VersionInfo_getPatch(VersionInfo* self, SizeT* patch)
{
    return reinterpret_cast<daq::IVersionInfo*>(self)->getPatch(patch);
}

ErrCode VersionInfo_createVersionInfo(VersionInfo** obj, SizeT major, SizeT minor, SizeT patch)
{
    daq::IVersionInfo* ptr = nullptr;
    ErrCode err = daq::createVersionInfo(&ptr, major, minor, patch);
    *obj = reinterpret_cast<VersionInfo*>(ptr);
    return err;
}
