//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:38.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct Module Module;
    typedef struct ModuleInfo ModuleInfo;
    typedef struct List List;
    typedef struct Dict Dict;
    typedef struct Device Device;
    typedef struct String String;
    typedef struct Component Component;
    typedef struct PropertyObject PropertyObject;
    typedef struct FunctionBlock FunctionBlock;
    typedef struct Server Server;
    typedef struct Streaming Streaming;
    typedef struct ServerCapability ServerCapability;
    typedef struct ServerCapabilityConfig ServerCapabilityConfig;

    EXPORTED extern const IntfID MODULE_INTF_ID;

    ErrCode EXPORTED Module_getModuleInfo(Module* self, ModuleInfo** info);
    ErrCode EXPORTED Module_getAvailableDevices(Module* self, List** availableDevices);
    ErrCode EXPORTED Module_getAvailableDeviceTypes(Module* self, Dict** deviceTypes);
    ErrCode EXPORTED Module_createDevice(Module* self, Device** device, String* connectionString, Component* parent, PropertyObject* config);
    ErrCode EXPORTED Module_getAvailableFunctionBlockTypes(Module* self, Dict** functionBlockTypes);
    ErrCode EXPORTED Module_createFunctionBlock(Module* self, FunctionBlock** functionBlock, String* id, Component* parent, String* localId, PropertyObject* config);
    ErrCode EXPORTED Module_getAvailableServerTypes(Module* self, Dict** serverTypes);
    ErrCode EXPORTED Module_createServer(Module* self, Server** server, String* serverTypeId, Device* rootDevice, PropertyObject* config);
    ErrCode EXPORTED Module_createStreaming(Module* self, Streaming** streaming, String* connectionString, PropertyObject* config);
    ErrCode EXPORTED Module_completeServerCapability(Module* self, Bool* succeeded, ServerCapability* source, ServerCapabilityConfig* target);
    ErrCode EXPORTED Module_getAvailableStreamingTypes(Module* self, Dict** streamingTypes);

#ifdef __cplusplus
}
#endif
