//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.6.0) on 27.04.2025 18:33:39.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct ModuleManager ModuleManager;
    typedef struct List List;
    typedef struct Module Module;
    typedef struct Context Context;
    typedef struct String String;

    EXPORTED extern const IntfID MODULE_MANAGER_INTF_ID;

    ErrCode EXPORTED ModuleManager_getModules(ModuleManager* self, List** modules);
    ErrCode EXPORTED ModuleManager_addModule(ModuleManager* self, Module* module);
    ErrCode EXPORTED ModuleManager_loadModules(ModuleManager* self, Context* context);
    ErrCode EXPORTED ModuleManager_createModuleManager(ModuleManager** obj, String* path);
    ErrCode EXPORTED ModuleManager_createModuleManagerMultiplePaths(ModuleManager** obj, List* paths);

#ifdef __cplusplus
}
#endif
