//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 05.06.2025 17:28:23.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqModuleManager daqModuleManager;
    typedef struct daqList daqList;
    typedef struct daqModule daqModule;
    typedef struct daqContext daqContext;
    typedef struct daqString daqString;

    EXPORTED extern const daqIntfID DAQ_MODULE_MANAGER_INTF_ID;

    daqErrCode EXPORTED daqModuleManager_getModules(daqModuleManager* self, daqList** modules);
    daqErrCode EXPORTED daqModuleManager_addModule(daqModuleManager* self, daqModule* module);
    daqErrCode EXPORTED daqModuleManager_loadModules(daqModuleManager* self, daqContext* context);
    daqErrCode EXPORTED daqModuleManager_loadModule(daqModuleManager* self, daqString* path, daqModule** module);
    daqErrCode EXPORTED daqModuleManager_createModuleManager(daqModuleManager** obj, daqString* path);
    daqErrCode EXPORTED daqModuleManager_createModuleManagerMultiplePaths(daqModuleManager** obj, daqList* paths);

#ifdef __cplusplus
}
#endif
