//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:37:29.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/modulemanager/context_internal.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID CONTEXT_INTERNAL_INTF_ID = { daq::IContextInternal::Id.Data1, daq::IContextInternal::Id.Data2, daq::IContextInternal::Id.Data3, daq::IContextInternal::Id.Data4_UInt64 };

ErrCode ContextInternal_moveModuleManager(ContextInternal* self, ModuleManager** manager)
{
    return reinterpret_cast<daq::IContextInternal*>(self)->moveModuleManager(reinterpret_cast<daq::IModuleManager**>(manager));
}
