//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:33.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/scheduler/task.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_TASK_INTF_ID = { daq::ITask::Id.Data1, daq::ITask::Id.Data2, daq::ITask::Id.Data3, daq::ITask::Id.Data4_UInt64 };

daqErrCode daqTask_getName(daqTask* self, daqString** name)
{
    return reinterpret_cast<daq::ITask*>(self)->getName(reinterpret_cast<daq::IString**>(name));
}

daqErrCode daqTask_setName(daqTask* self, daqString* name)
{
    return reinterpret_cast<daq::ITask*>(self)->setName(reinterpret_cast<daq::IString*>(name));
}

daqErrCode daqTask_then(daqTask* self, daqTask* continuation)
{
    return reinterpret_cast<daq::ITask*>(self)->then(reinterpret_cast<daq::ITask*>(continuation));
}

daqErrCode daqTask_createTask(daqTask** obj, daqProcedure* work, daqString* name)
{
    daq::ITask* ptr = nullptr;
    daqErrCode err = daq::createTask(&ptr, reinterpret_cast<daq::IProcedure*>(work), reinterpret_cast<daq::IString*>(name));
    *obj = reinterpret_cast<daqTask*>(ptr);
    return err;
}
