//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 01.04.2025 17:02:04.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

    typedef struct CoreEventArgs CoreEventArgs;
    typedef struct Dict Dict;
    typedef struct String String;
    typedef struct PropertyObject PropertyObject;
    typedef struct Property Property;
    typedef struct Type Type;

    EXPORTED extern const IntfID CORE_EVENT_ARGS_INTF_ID;

    ErrCode EXPORTED CoreEventArgs_getParameters(CoreEventArgs* self, Dict** parameters);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgs(CoreEventArgs** obj, CoreEventId eventId, String* eventName, Dict* parameters);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsPropertyValueChanged(CoreEventArgs** obj, PropertyObject* propOwner, String* propName, BaseObject* value, String* path);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsPropertyObjectUpdateEnd(CoreEventArgs** obj, PropertyObject* propOwner, Dict* updatedProperties, String* path);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsPropertyAdded(CoreEventArgs** obj, PropertyObject* propOwner, Property* prop, String* path);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsPropertyRemoved(CoreEventArgs** obj, PropertyObject* propOwner, String* propName, String* path);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsTypeAdded(CoreEventArgs** obj, Type* type);
    ErrCode EXPORTED CoreEventArgs_createCoreEventArgsTypeRemoved(CoreEventArgs** obj, String* typeName);

#ifdef __cplusplus
}
#endif
