name: Build Documentation
description: Build Doxygen API reference documentation

inputs:
  build-path:
    description: 'Path to CMake build directory'
    required: true
  artifact-name:
    description: 'Artifact name for upload. If empty, documentation will not be uploaded'
    required: false
    default: ''
  artifact-retention-days:
    description: 'Retention days for artifact'
    required: false
    default: '7'

outputs:
  documentation-path:
    description: 'Path to documentation zip file'
    value: ${{ steps.build.outputs.documentation-path }}

runs:
  using: composite
  steps:
    - name: Build Documentation
      id: build
      shell: bash
      run: |
        cmake -B ${{ inputs.build-path }} -DOPENDAQ_BUILD_DOCUMENTATION=ON
        cmake --build ${{ inputs.build-path }} --target doc_doxygen

        cd ${{ inputs.build-path }}/doc_doxygen/html
        zip -r ../opendaq_cpp_api_reference.zip .

        echo "documentation-path=${{ inputs.build-path }}/doc_doxygen/opendaq_cpp_api_reference.zip" >> "$GITHUB_OUTPUT"

    - name: Upload Documentation
      if: inputs.artifact-name != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.build.outputs.documentation-path }}
        retention-days: ${{ inputs.artifact-retention-days }}
