= Measure a single value

openDAQ offers a variety of solutions for reading Signal values, including Readers. 

However, for developers requiring access to only the most recent value, the Signal interface provides a method for doing just that.

[#last_value_signal]
== Getting the last value of a Signal

Reading the last value of a Signal yields an openDAQ Base object-type value. Said value contains the last sample of the most recent Packet sent through the Signal.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
----
Python::
+
[source,python]
----

----
====


[#last_value_signal_types]
== Last value and Signal types

The method for getting the last value yields an openDAQ Base object-type value.

The underlying type of the openDAQ Base object-type value we get from the method call corresponds to the Sample Type in the Data Descriptor of the Signal.

* openDAQ Float object-type corresponds to `Float32` or `Float64` Sample Types
* openDAQ Integer object-type corresponds to `Int8` through `Int64` or `UInt8` through `UInt64` Sample Types
* openDAQ Complex Float object-type corresponds to `ComplexFloat32` or `ComplexFloat64` Sample Types
* openDAQ Range object-type corresponds to `RangeInt64` Sample Type
* openDAQ Struct object-type corresponds to `Struct` Sample Type and the Data Descriptor must have Struct Fields defined
* openDAQ List object-type corresponds to any of the aforementioned Sample Types and the Data Descriptor must have Dimensions defined

An example of casting the last value object into an openDAQ Float interface:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Cast to IFloat
auto number = lastValue.asPtr<IFloat>();
----
Python::
+
[source,python]
----

----
====

In the above example, the Data Descriptor of the Signal on which the method for getting the last value is called might be:

[tabs]
====
Cpp::
+
[source,cpp]
----
// The Data Descriptor for Float64
auto descriptor = DataDescriptorBuilder().setSampleType(SampleType::Float64).build();
----
Python::
+
[source,python]
----

----
====

[#last_value_struct]
== Getting the last value with a Struct

A Data Descriptor for a Struct might be:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Create a Data Descriptor
auto descriptor = DataDescriptorBuilder()
					  .setName("MyStruct")
					  .setSampleType(SampleType::Struct)
					  .setStructFields(List<DataDescriptorPtr>(
						  DataDescriptorBuilder()
							  .setName("MyInt32")
							  .setSampleType(SampleType::Int32)
							  .build(),
						  DataDescriptorBuilder()
							  .setName("MyFloat64")
							  .setSampleType(SampleType::Float64)
							  .build()))
					  .build();
// Set the Data Descriptor, thereby adding MyStruct to the Type Manager
signal.setDescriptor(descriptor);
----
Python::
+
[source,python]
----

----
====

In the above example, a Data Descriptor of a custom Struct that has two fields is first built. The first field has Sample Type `Int32` and the second one has Sample Type `Float64`.

[CAUTION]
====
`opendaq.SampleType.Struct` is not yet supported in Python.
====

[NOTE]
====
Because our Struct represents a custom type, we must call `setDescriptor` (`descriptor` in Python) on our Signal in order to add `MyStruct` to the Type Manager.
====

[CAUTION]
====
All custom Structs and their respective fields must have their names set, which is a deviation from the previous examples.
====

After some data has been sent to our Signal, we can capture a single value similar to the previous examples:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
// Cast to IStruct
auto myStruct = lastValue.asPtr<IStruct>();
// Extract values
auto myInt = myStruct.get("MyInt32");
auto myFloat = myStruct.get("MyFloat64");
----
Python::
+
[source,python]
----

----
====

[NOTE]
====
Structs can be nested within the Data Descriptor.
====

[#last_value_list]
== Getting the last value with a List

It's possible for the last value to be a List.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
// Cast to IList
auto myList = lastValue.asPtr<IList>();
// Extract the third item on myList
auto third = myList.getItemAt(2);
----
Python::
+
[source,python]
----

----
====

[NOTE]
====
Dimensions of the Data Descriptor that can be set via the method for setting dimensions for Lists in the Data Descriptor Builder and must contain exactly one dimension.
====

[NOTE]
====
Lists may contain (nested) Structs. In such cases, be sure to configure the Data Descriptor appropriately.
====
