= Instance configuration

The Instance is the top-level openDAQ(TM) object, serving as a container for the openDAQ context and the base module manager.

**Related articles:**

  * xref:background_info:opendaq_architecture.adoc#instance[Architecture - Instance]

== Creating the default openDAQ(TM) Instance
Upon creation, it generates Client device as default root device. The client device is capable of using the module manager to add function blocks, and connect to any device supported by the loaded modules. The Client device can connect to any supported device. The Client is set as the root device when the instance is created if the root device has not been replaced by developer.

== Creating openDAQ(TM) Instance with Instance Builder

openDAQ(TM) provides an advanced way to configure an Instance using the Instance Builder. With the Instance Builder, developers can configure the Logger, Scheduler, Module Manager, and Root Device by setting custom modules or modifying default objects.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder();
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

instance_builder = opendaq.InstanceBuilder()
instance = instance_builder.build()
----
====

== Configure openDAQ(TM) Instance Logger
By default, the Instance Logger level is set to the info log level if the release version of the project was built or debug if the project was built in debug mode. There are two ways to override the default level. The first one is to set the global default logger level.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder();
    instanceBuilder.setGlobalLogLevel(daq::LogLevel::Warn);
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

instance_builder = opendaq.InstanceBuilder()
instance_builder.global_log_level = opendaq.LogLevel.Warn
instance = instance_builder.build()
----
====

In addition to changing the logging level, the developer can also set the logging level for individual components and sinks. In the example below, the developer sets two logger sinks: `StdOutLoggerSink` with the default log level and `BasicFileLoggerSink` with the error log level. Additionally, custom log levels are set for the components `Instance` and `Some Module`.
[tabs]
====
Cpp::
+
[source,cpp]
----
daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder()
                    .addLoggerSink(StdOutLoggerSink())
                    .setSinkLogLevel(BasicFileLoggerSink("logfile.log"),  daq::LogLevel::Error)
                    .setComponentLogLevel("Instance", daq::LogLevel::Warn)
                    .setComponentLogLevel("Some Module", daq::LogLevel::Off);

daq::InstancePtr instance = instanceBuilder.build();
----
Python::
+
[source,python]
----
import opendaq

instance_builder = opendaq.InstanceBuilder()
instance_builder.add_logger_sink(opendaq.StdOutLoggerSink())
instance_builder.set_sink_log_level(opendaq.BasicFileLoggerSink("logfile.log"), opendaq.LogLevel.Error)
instance_builder.set_component_log_level("Instance", opendaq.LogLevel.Warn)
instance_builder.set_component_log_level("Some Module", opendaq.LogLevel.Off)

instance = instance_builder.build()
----
====

An advanced way of configuring the Instance logger is to configure the logger object and set it with the logger configuration method.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>


int main(int argc, const char* argv[])
{
    daq::ListPtr<ILoggerSink> sinks = daq::List<ILoggerSink>(StdOutLoggerSink());
    daq::LoggerPtr logger = daq::LoggerWithSinks(sinks, daq::LogLevel::Warn);
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setLogger(logger);

    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
====

[NOTE]
====
Alternatively, a developer can create their own implementation of the logger, which implements the ILogger interface.
====

== Configure openDAQ(TM) Instance Module Manager
By default, the Instance Module Manager uses the current path for loading modules. In the Instance Builder, developers can set a custom module path or replace the default Module Manager with a custom implementation that implements the IModuleManager interface.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>


int main(int argc, const char* argv[])
{
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setModulePath("/path/to/modules");
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

instance_builder = opendaq.InstanceBuilder()
instance_builder.module_path = "/path/to/modules"
instance = instance_builder.build()
----
Overriding module path
====

[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::ModuleManagerPtr moduleManager = daq::ModuleManager("/path/to/modules");
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setModuleManager(moduleManager);
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

module_manager = opendaq.ModuleManager("/path/to/modules")
instance_builder = opendaq.InstanceBuilder()
instance_builder.module_manager = module_manager
instance = instance_builder.build()
----
Setting module manager
====

== Configure openDAQ(TM) Instance Scheduler
By default, the Instance creates a Scheduler with a number of workers equal to the maximum physical threads. To manually change this amount, developers can use the Instance Builder method `setSchedulerWorkerNum`.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setSchedulerWorkerNum(2);
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

instance_builder = opendaq.InstanceBuilder()
instance_builder.scheduler_worker_num = 2
instance = instance_builder.build()
----
====
As in previous examples, developers can implement their own solution for the scheduler and use it in the Instance Builder.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::SchedulerPtr scheduler = daq::Scheduler(4);
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setScheduler(scheduler);
    daq::InstancePtr instance = instanceBuilder.build();

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

scheduler = opendaq.Scheduler(4)
instance_builder = opendaq.InstanceBuilder()
instance_builder.scheduler = scheduler
instance = instance_builder.build()
----
====

== Configure openDAQ(TM) Default Root Device
The Instance has client device as default root device. Developer can modify default device by setting default root device info and local id in instance builder.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::DeviceInfoPtr defaultRootDeviceInfo = daq::DeviceInfo("daqref://defaultRootDevice");
    defaultRootDeviceInfo.setSerialNumber("ABCD-0000-0000-0000");
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder()
                                                    .setDefaultRootDeviceInfo(defaultRootDeviceInfo)
                                                    .setDefaultRootDeviceLocalId("defaultRootDeviceLocalId");
    daq::InstancePtr instance = instanceBuilder.build();

    assert(instance.getInfo() == defaultRootDeviceInfo);

    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

default_root_device_info = opendaq.DeviceInfo("daqref://defaultRootDevice")
default_root_device_info.serial_number = "ABCD-0000-0000-0000"

instance_builder = opendaq.InstanceBuilder()
instance_builder.default_root_device_info = default_root_device_info
instance_builder.default_root_device_local_id = "defaultRootDeviceLocalId"
instance = instance_builder.build()
----
====

== Configure openDAQ(TM) Root Device
Developer can replace default root device with device with giver connection string. When the instance is created a connection to the device with the given connection string will be established, and the device will be placed at the root of the component tree structure.
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>
#include <iostream>

int main(int argc, const char* argv[])
{
    daq::InstanceBuilderPtr instanceBuilder = daq::InstanceBuilder().setRootDevice("daqref://device0");
    daq::InstancePtr instance = instanceBuilder.build();
    return 0;
}
----
Python::
+
[source,python]
----
import opendaq

# Create an openDAQ(TM) instance with a custom root device
instance_builder = opendaq.InstanceBuilder()
instance_builder.root_device ="daqref://device0"
instance = instance_builder.build()
----
====