= Measure a single value

openDAQ offers a variety of solutions for reading Signal values, including Readers. 

However, for developers requiring access to only the most recent value, the Signal and Data Packet interfaces provide a method for doing just that.

[#last_value_signal]
== Getting the last value of a Signal

Reading the last value of a Signal yields an openDAQ base object-type value. Said value contains the last sample of the most recent packet sent through the Signal.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
----
Python::
+
[source,python]
----

----
====

[#last_value_data_packet]
== Getting the last value of a Data Packet

Similar is true when reading the last value of a Data Packet.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Data Packet
auto lastValue = packet.getLastValue();
----
====

[CAUTION]
====
Getting the last value of a Data Packet is not yet supported in Python.
====


[#last_value_signal_types]
== Last value and Signal types

The method for getting the last value yields an openDAQ base object-type value.

The underlying type of the openDAQ base object-type we get from the method call can be cast into either:

* `IFloat` if the type is `Float32` or `Float64`
* `IInteger` if the type is `Int8` through `Int64` or `UInt8` through `UInt64`
* `IComplexNumber` if the type is `ComplexFloat32` or `ComplexFloat64`
* `IRange` if the type is `RangeInt64`
* `IStruct` if the type is `Struct`
* `IList` of the aforementioned types if there is exactly one dimension in the single value

An example of casting the last value object into an openDAQ Float interface:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Cast to IFloat
auto number = lastValue.asPtr<IFloat>();
----
Python::
+
[source,python]
----

----
====

In the above example, the Data Descriptor of the Data Packet or its Signal on which the method for getting the last value is called might be:

[tabs]
====
Cpp::
+
[source,cpp]
----
// The Data Descriptor for Float64
auto descriptor = DataDescriptorBuilder().setSampleType(SampleType::Float64).build();
----
Python::
+
[source,python]
----

----
====

[#last_value_range]
== Getting the last value with a Range

The following example demonstrates casting the last value object into an openDAQ Range interface. We can then call the methods of the underlying interface and access its members.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Cast to IRange
auto range = lastValue.asPtr<IRange>();
// Extract values
auto low = range.getLowValue();
auto high = range.getHighValue();
----
Python::
+
[source,python]
----

----
====

In the above example, the Data Descriptor of the Data Packet or Signal on which the method for getting the last value is called is similar to the the one from the previous example (the Data Descriptor with Sample Type `Float64`), except the Sample Type is `RangeInt64`.

[#last_value_complex_number]
== Getting the last value with a Complex Number

In the following example:

* Last value is extracted via a `getLastValue` (`last_value` in Python) call
* `lastValue` object is cast into a `IComplexNumber` type (not needed in Python)
* Methods of the underlying type such as the `getReal` (`real` in Python) and the `getImaginary` (`imaginary` in Python) are called, in this case provided by the `IComplexNumber` interface

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
// Cast to IComplexNumber
auto complex = lastValue.asPtr<IComplexNumber>();
// Extract values
auto real = complex.getReal();
auto imaginary = complex.getImaginary();
----
Python::
+
[source,python]
----

====

A Data Descriptor for this Complex Number example is again very similar to the ones from previous examples, except the Sample Type might be `ComplexFloat32` or `ComplexFloat64` or  instead of `Float64` or `RangeInt64`.

[#last_value_struct]
== Getting the last value with a Struct

A Data Descriptor for a Struct might be:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Create a Data Descriptor
auto descriptor = DataDescriptorBuilder()
					  .setName("MyStruct")
					  .setSampleType(SampleType::Struct)
					  .setStructFields(List<DataDescriptorPtr>(
						  DataDescriptorBuilder()
							  .setName("MyInt32")
							  .setSampleType(SampleType::Int32)
							  .build(),
						  DataDescriptorBuilder()
							  .setName("MyFloat64")
							  .setSampleType(SampleType::Float64)
							  .build()))
					  .build();
// Set the Data Descriptor, thereby adding MyStruct to the Type Manager
signal.setDescriptor(descriptor);
----
Python::
+
[source,python]
----

----
====

In the above example, a Data Descriptor of a custom Struct that has two fields is first built. The first field has Sample Type `Int32` and the second one has Sample Type `Float64`.

[CAUTION]
====
`opendaq.SampleType.Struct` is not yet supported in Python.
====

[NOTE]
====
Because our Struct represents a custom type, we must call `setDescriptor` (`descriptor` in Python) on our Signal in order to add `MyStruct` to the Type Manager.
====

[CAUTION]
====
All custom Structs and their respective fields must have their names set, which is a deviation from the previous examples.
====

After some data has been sent to our Signal, we can capture a single value similar to the previous examples:

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
// Cast to IStruct
auto myStruct = lastValue.asPtr<IStruct>();
// Extract values
auto myInt = myStruct.get("MyInt32");
auto myFloat = myStruct.get("MyFloat64");
----
Python::
+
[source,python]
----

----
====

[CAUTION]
====
If we want to call the method for getting last value on a Data Packet (as opposed to a Signal) and the underlying data type is a Struct, we must provide the optional parameter, Type Manager, which has had the custom Struct added to it.
====

[NOTE]
====
Structs can be nested within the Data Descriptor.
====

[#last_value_list]
== Getting the last value with a List

It's possible for the last value to be a List.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
// Cast to IList
auto myList = lastValue.asPtr<IList>();
// Extract the third item on myList
auto third = myList.getItemAt(2);
----
Python::
+
[source,python]
----

----
====

[NOTE]
====
Dimensions of the Data Descriptor that can be set via the method for setting dimensions for Lists in the Data Descriptor Builder and must contain exactly one dimension.
====

[NOTE]
====
Lists may contain (nested) Structs. In such cases, be sure to configure the Data Descriptor appropriately.
====
