= Measure a single value

openDAQ offers a variety of solutions for reading Signal values, including Readers. 

However, for developers requiring access to only the most recent value, the Signal interface provides a method for doing just that.

[#last_value_signal]
== Getting the last value of a Signal

Reading the last value of a Signal yields an openDAQ Base object-type value. Said value contains the last sample of the most recent Packet sent through the Signal.

[tabs]
====
Cpp::
+
[source,cpp]
----
// Get last value of a Signal
auto lastValue = signal.getLastValue();
----
Python::
+
[source,python]
----
# Get last value of a Signal
last_value = signal.last_value
----
====

[#last_value_signal_types]
== Last value and Signal types

The method for getting the last value yields an openDAQ Base object-type value.

The underlying type of the openDAQ Base object-type value we get from the method call corresponds to the Sample Type in the Data Descriptor of the Signal.

* openDAQ Float object-type corresponds to `Float32` or `Float64` Sample Types
* openDAQ Integer object-type corresponds to `Int8` through `Int64` or `UInt8` through `UInt64` Sample Types
* openDAQ Complex Float object-type corresponds to `ComplexFloat32` or `ComplexFloat64` Sample Types
* openDAQ Range object-type corresponds to `RangeInt64` Sample Type
* openDAQ Struct object-type corresponds to `Struct` Sample Type and the Data Descriptor must have Struct Fields defined
* openDAQ List object-type corresponds to any of the aforementioned Sample Types and the Data Descriptor must have Dimensions defined

[NOTE]
====
Dimensions of the Data Descriptor for Lists may contain exactly one dimension.
====

[NOTE]
====
Lists may contain (nested) Structs. In such cases, be sure to configure the Data Descriptor appropriately.
====
