= Configure Streaming

Typically, in addition to publishing its own structure (xref:glossary:glossary.adoc#signal[Signal]s,
xref:glossary:glossary.adoc#channel[Channel]s, xref:glossary:glossary.adoc#function_block[Function Block]s, etc.),
an openDAQ(TM) xref:glossary:glossary.adoc#device[Device] also publishes information about
xref:glossary:glossary.adoc#streaming[Streaming] protocols it supports. This information includes the
streaming protocol ID (e.g. 'daq.wss' or 'daq.ns'), which doubles as a prefix in the connection string,
enabling the routing of streaming instantiation to the appropriate openDAQ(TM)
xref:glossary:glossary.adoc#module[Module]. Additionally, it includes the device's IP address (used if the
streaming protocol requires a network connection) and a range of optional parameters (e.g. port number).
When a streaming server starting on the device, this automatically generates and prepares mentioned
information to be published along with the device's structural details.

As a result, when connecting an openDAQ(TM) device, a streaming connection can be established automatically
using the published streaming connection details.

[#streaming_config_per_device]
== Configure Streaming per Device

The xref:glossary:glossary.adoc#device[Device] configuration xref:glossary:glossary.adoc#property_object[Property
object] provides a mechanism for customizing the filtering of available Streaming protocols by enabling or
disabling specific ones. Additionally, it allows to set the "primary" protocol type of the Streaming
connection to be initially used as an active Streaming source for all of the
xref:glossary:glossary.adoc#device[Signal]s.

Furthermore, there's an option to specify a Streaming path heuristic, particularly useful for multiple
nested devices connected in a tree-structured manner (as illustrated in the xref:background_info:device.adoc#nested_devices[diagram]).
The allowed heuristics include:

* "Minimize-connections" mode (ID 0) - is used to establish the fewest Streaming connections possible at
the cost of routing Signals' data through gateway Devices, increasing the hop count.
* "Minimize-hops" mode (ID 1) - is used to attempt streaming data directly from nested Devices to minimize
the amount of hops between Devices the data must make.
* "Fallback" mode (ID 2) - is used to establish all possible Streaming connections.
* "Not connected" mode (ID 3) - with this set the information about supported streaming protocols published
by the Device is not used to automatically establish Streaming connections.

[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>

using namespace daq;

int main()
{
    // Create a new Instance that we will use for all the interactions with the SDK
    daq::InstancePtr instance = daq::Instance(MODULE_PATH);

    // Get the default configuration Property object for OPC UA enabled device type
    daq::PropertyObjectPtr deviceConfig = instance.getAvailableDeviceTypes().get("daq.opcua").createDefaultConfig();

    // Allow multiple streaming protocols by device configuration
    deviceConfig.setPropertyValue("AllowedStreamingProtocols", daq::List<daq::IString>("daq.ns", "daq.wss"));

    // Set websocket streaming protocol as primary by device configuration
    deviceConfig.setPropertyValue("PrimaryStreamingProtocol", "daq.wss");

    // Disregard direct streaming connections for nested devices,
    // establish the minimum number of streaming connections possible.
    deviceConfig.setPropertyValue("StreamingConnectionHeuristic", 0);  

    // Find and connect to a device hosting an OPC UA TMS server
    const auto availableDevices = instance.getAvailableDevices();
    daq::DevicePtr device;
    for (const auto& deviceInfo : availableDevices)
    {
        if (deviceInfo.getConnectionString().toView().find("daq.opcua://") != std::string::npos)
        {
            // Add device using modified configuration Property object
            device = instance.addDevice(deviceInfo.getConnectionString(), deviceConfig);
            break;
        }
    }

    if (!device.assigned())
        std::cerr << "No relevant device found!" << std::endl;
    else
        // Output the name of the added device
        std::cout << device.getInfo().getName() << std::endl;
    
    return 0;
}
----
====

[#streaming_config_per_signal]
== Configure Streaming per Signal

Once the xref:glossary:glossary.adoc#device[Device] is connected, the Streaming sources of its
xref:glossary:glossary.adoc#signal[Signal]s can be examined and modified for each signal individually
at any given time.

The Streaming sources are identified by a connection string that includes the protocol prefix, indicating
the protocol type ID, and parameters based on the protocol type (IP address, port number etc.).
To manipulate the Streaming sources of particular Signal the `MirroredSignalConfig` object is used,
it provides ability to:

* retrieve a list of streaming sources available for signal,
* get the currently active streaming source,
* modify the active source or unset it to disable data streaming for a signal.

[tabs]
====
Cpp::
+
[source,cpp]
----
#include <opendaq/opendaq.h>

using namespace daq;

// Corresponding document: Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
int main()
{
    ...

    // Get the first signal of conencted device
    daq::SignalPtr signal = device.getSignalsRecursive()[0];

    daq::StringPtr nativeStreamingSource;
    daq::StringPtr websocketStreamingSource;

    // Find and output the streaming sources available for signal
    std::cout << "Signal supports " << signal.getStreamingSources().getCount()
              << " streaming sources:" << std::endl;
    for (const auto& source : signal.getStreamingSources())
    {
        std::cout << source << std::endl;
        if (source.toView().find("daq.ns://") != std::string::npos)
            nativeStreamingSource = source;
        if (source.toView().find("daq.wss://") != std::string::npos)
            websocketStreamingSource = source;
    }

    // Output the active streaming source of signal
    std::cout << "Active streaming source of signal: " << signal.getActiveStreamingSource();

    // Change the active streaming source of signal
    signal.setActiveStreamingSource(nativeStreamingSource);

    std::cout << "Press \"enter\" to exit the application..." << std::endl;
    std::cin.get();
    return 0;
}
----
====

== Full listing

The following is a fully working example of configuring Streaming and reading Signal data using different
Streaming sources.

.The full example code listing
[tabs]
====
Cpp::
+
[source,cpp]
----
#include <chrono>
#include <iostream>
#include <thread>
#include <opendaq/opendaq.h>

void readSamples(const daq::MirroredSignalConfigPtr signal)
{
    using namespace std::chrono_literals;
    daq::StreamReaderPtr reader = daq::StreamReader<double, uint64_t>(signal);

    // Get the resolution and origin
    daq::DataDescriptorPtr descriptor = signal.getDomainSignal().getDescriptor();
    daq::RatioPtr resolution = descriptor.getTickResolution();
    daq::StringPtr origin = descriptor.getOrigin();
    daq::StringPtr unitSymbol = descriptor.getUnit().getSymbol();

    std::cout << "\nReading signal: " << signal.getName()
              << "; active streaming source: " << signal.getActiveStreamingSource() << std::endl;
    std::cout << "Origin: " << origin << std::endl;

    // Allocate buffer for reading double samples
    double samples[100];
    uint64_t domainSamples[100];
    for (int i = 0; i < 40; ++i)
    {
        std::this_thread::sleep_for(25ms);

        // Read up to 100 samples every 25ms, storing the amount read into `count`
        daq::SizeT count = 100;
        reader.readWithDomain(samples, domainSamples, &count);
        if (count > 0)
        {
            daq::Float domainValue = (daq::Int) domainSamples[count - 1] * resolution;
            std::cout << "Value: " << samples[count - 1] << ", Domain: " << domainValue << unitSymbol << std::endl;
        }
    }
}

int main(int /*argc*/, const char* /*argv*/[])
{
    // Create a new Instance that we will use for all the interactions with the SDK
    daq::InstancePtr instance = daq::Instance(MODULE_PATH);

    // Get the default configuration Property object for OPC UA enabled device type
    daq::PropertyObjectPtr deviceConfig = instance.getAvailableDeviceTypes().get("daq.opcua").createDefaultConfig();

    // Allow multiple streaming protocol by device configuration
    deviceConfig.setPropertyValue("AllowedStreamingProtocols", daq::List<daq::IString>("daq.ns", "daq.wss"));

    // Set websocket streaming protocol as primary by device configuration
    deviceConfig.setPropertyValue("PrimaryStreamingProtocol", "daq.wss");

    // Find and connect to a device hosting an OPC UA TMS server
    const auto availableDevices = instance.getAvailableDevices();
    daq::DevicePtr device;
    for (const auto& deviceInfo : availableDevices)
    {
        if (deviceInfo.getConnectionString().toView().find("daq.opcua://") != std::string::npos)
        {
            // Add device using modified configuration Property object
            device = instance.addDevice(deviceInfo.getConnectionString(), deviceConfig);
            break;
        }
    }

    // Exit if no device is found
    if (!device.assigned())
    {
        std::cerr << "No relevant device found!" << std::endl;
        return 0;
    }

    // Output the name of the added device
    std::cout << device.getInfo().getName() << std::endl;

    // Find the AI signal
    auto signals = device.getSignalsRecursive();

    daq::ChannelPtr channel;
    daq::MirroredSignalConfigPtr signal;
    for (const auto& sig : signals)
    {
        auto name = sig.getDescriptor().getName();

        if (name.toView().find("AI") != std::string_view::npos)
        {
            signal = sig;
            channel = signal.getParent().getParent();
            break;
        }
    }

    if (!signal.assigned())
    {
        std::cerr << "No AI signal found!" << std::endl;
        return 1;
    }

    // Set the mirrored DI signal to use on AI
    channel.setPropertyValue("InputMux", 1);

    // Find and output the streaming sources of signal
    daq::StringPtr nativeStreamingSource;
    daq::StringPtr websocketStreamingSource;
    std::cout << "AI signal has " << signal.getStreamingSources().getCount()
              << " streaming sources:" << std::endl;
    for (const auto& source : signal.getStreamingSources())
    {
        std::cout << source << std::endl;
        if (source.toView().find("daq.ns://") != std::string::npos)
            nativeStreamingSource = source;
        if (source.toView().find("daq.wss://") != std::string::npos)
            websocketStreamingSource = source;
    }

    // Check the active streaming source of signal
    if (signal.getActiveStreamingSource() != websocketStreamingSource)
    {
        std::cerr << "Wrong active streaming source of AI signal" << std::endl;
        return 1;
    }
    // Output samples using reader with websocket streaming
    readSamples(signal);

    // Change the active streaming source of signal
    signal.setActiveStreamingSource(nativeStreamingSource);
    // Output samples using reader with native streaming
    readSamples(signal);

    std::cout << "Press \"enter\" to exit the application..." << std::endl;
    std::cin.get();
    return 0;
}
----
====
