= Components

Components represent all data acquisition objects that define the tree structure of an openDAQ(TM) system.
Generally, they represent objects that represent physical device components (eg. xref:device.adoc[Device], 
xref:function_blocks.adoc#channel[Channel]), or data processing objects that form the xref:data_path.adoc[Data path]
(eg. xref:function_blocks.adoc[Function blocks], xref:signals.adoc[Signals], or xref:function_blocks.adoc#input_port[Input Ports]).

Each Component inherits all capabilities of a xref:property_system.adoc[Property Object] and uses its features to allow for
the definition of user-customizable parameters such as a Device's sample rate, or the number of averaged samples in an 
Averaging Function block.

The Component differentiates itself from base Property Objects in that it has a Local and Global ID in an openDAQ(TM) system 
and thus is a building block of the system's structure. When viewed from the perspective of a user interface, Components
would show up as a tree-view that represents the structure, while Properties (including xref:property_system.adoc#object[Object-type properties] 
that represent base Property Objects), appear as customizable properties to the user in a separate part of the user interface.

== Component types

The following components are currently available in the openDAQ(TM) SDK. The table below outlines their purpose in a brief
explanation, and provides links to articles describing each component in detail.

[cols="1,4"]
|===
| **Component**
| **Description**

| Component
| A base Component that describes any custom Component of a Device.

| <<folder, Folder>>
| A base Component that can have 0 or more child Components. 

| <<folder, IO Folder>>
| A base Component that can have 0 or more IO (input-output) Components. IO Folders and Channels are IO Components.

| xref:device.adoc[Device]
| Representation of a physical, or virtual data acquisition Device that acts as a container for Channels, Function Blocks, Signals, and other Devices

| xref:function_blocks.adoc#channel[Channel]
| Representation of physical hardware input, or output Channel. Examples of Channels are analog or digital inputs or outputs of DAQ hardware.  

| xref:signals.adoc[Signal]
| Signals carry data streams in the form of packets through openDAQ(TM) systems. They are used to form data paths from data producers (eg. Channels) to consumers
  (eg. Function Blocks with Input Ports).

| xref:function_blocks.adoc[Function Block]
| Data processing Component of the SDK. Function blocks can have 0 or more Input Ports through which they acquire data and 0 or more Output Signals through which
  they send data to any data consumer. Note that a Function Block can have multiple modes of operation that do not require any Input Ports or Output Signals 
  (for example, a File writer that writes acquired data from an Input Port to a file, but does not produce Output Signals).

| xref:function_blocks.adoc#input_port[Input Port]
| Port object to which a Signal is connected, forming a xref:data_path.adoc#connection[Connection] between them. When a Signal is connected to an Input Port the 
  Input Port acts as a consumer and will receive xref:packets.adoc[Packets] sent by the signal.
|===

== Component IDs

Each Component in the openDAQ(TM) tree has a unique Global ID. The Global ID is formed using the 
hierarchical structure of Components, with it being formed with the Local IDs of the Component's ancestors
separated by forward slashes ("/"). A xref:device.adoc[Device] with a Local ID "DAQDevice" that has a 
xref:function_blocks.adoc#channel[Channel] named "CH1" with xref:signals.adoc[Output Signals] 
"Scaled" and "Raw" would have the following components:

[cols="1,3"]
|===

| **Local ID**
| **Global ID**

| DAQDevice
| DAQDevice

| CH1
| DAQDevice/IO/CH1

| Scaled
| DAQDevice/IO/CH1/Scaled

| Raw
| DAQDevice/IO/CH1/Raw

|===

Of note are the `IO` components that separate the Device and Channel Components. These represent the Device's IO Folder
that is automatically created by the openDAQ(TM) Device in addition to the `FB` (Function Blocks) and `Sig` (Signals)
folders. 

[#folder]
== Folders

Folders are standard Components that can also have child Components. A xref:device.adoc[Device] for example, is a Folder,
as is a xref:function_blocks.adoc[Function Block]. Folders are used to define the structure of an openDAQ(TM) system. 
Organization of standardized Folders such as Function Blocks and Devices, as well as standard Device folders (`IO`, `Sig`, `Fb`, `Dev`)
is done automatically when such Components are added in an openDAQ(TM) system.

Non-standardized Folder structures can be designed by Devices with custom Components/Folders, as well as Function Blocks with
nested Function Block structures. These are explored in detail in their respective articles.

=== Traversing Folders

Folders such as xref:device.adoc[Devices] and xref:function_blocks.adoc[Function Blocks] offer methods to simply navigate
through their child Components. Devices provide getters for their Channel/Function Block/Signal/Device child Components,
while Function Block provide similar getter methods for their Output Signals and nested Function Blocks.

When working with a custom Folder implementation, however, a generic getter method is available that returns all child
Components. Folders, unless specialized (eg. <<IO Folders>>), should only have base Folders or base Components as children.
A base Folder should not have Devices, Function Blocks, Signals, or other DAQ Components as child Components.

Each specialized, or generic child `get` call has an optional parameter, allowing for customizing your search query.
By default, the getters will not search recursively, and will only return children with `visible` set to `true`.

Example code snippet that recursively finds all signals in a given device and prints their global IDs:


[tabs]
====
Cpp::
+
[source,cpp]
----
void findSignals(const DevicePtr& device)
{
    const auto searchParams = SearchParamsBuilder()
                              .setRecursive(true)
                              .setVisibleOnly(false)
                              .build();

    for (const auto& signal : device.getSignals(searchParams))
        std::cout << signal.getGlobalId() << std::endl;
}
----
Python::
+
[source,python]
----
def findSignals(device: opendaq.IDevice):
    builder = opendaq.SearchParamsBuilder()
    builder.recursive = true
    builder.visible_only = false

    for signal in folder.get_signals(builder.build()):
        print(signal.global_id)
----
====

[#io_folder]
=== IO Folders

Folders can have specializations where only specific child Components can be added as children. Currently openDAQ(TM)
contains only the IO Folder specialization. IO Folders can only have other IO Folders or Channels as children. This
allows Devices to organize their channels below the IO Folder in a tree structure but prevents them from placing 
non-Channel Components into the folder.

NOTE: Each Device always has an `IO` folder as its child, and all its Channels should be children of the IO Folder. 
