/*
 * Copyright 2022-2023 Blueberry d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
#include "opcuatms/opcuatms.h"

namespace daq::opcua
{
    ADD_CUSTOM_TYPE_MAPPING(UA_BaseRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_BASERULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_CustomRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_CUSTOMRULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_ConstantRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_CONSTANTRULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_LinearRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_LINEARRULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_ListRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_LISTRULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_LogRuleDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_LOGRULEDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_EUInformationWithQuantity, &UA_TYPES_TMSBT[UA_TYPES_TMSBT_EUINFORMATIONWITHQUANTITY])
    ADD_CUSTOM_TYPE_MAPPING(UA_DataDescriptorStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_DATADESCRIPTORSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_StructDescriptorStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_STRUCTDESCRIPTORSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_DimensionDescriptorStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_DIMENSIONDESCRIPTORSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_RationalNumber64, &UA_TYPES_TMSBT[UA_TYPES_TMSBT_RATIONALNUMBER64])
    ADD_CUSTOM_TYPE_MAPPING(UA_PostScalingStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_POSTSCALINGSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_LinearScalingDescriptionStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_LINEARSCALINGDESCRIPTIONSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_FunctionBlockInfoStructure, &UA_TYPES_TMSBSP[UA_TYPES_TMSBSP_FUNCTIONBLOCKINFOSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_DaqKeyValuePair, &UA_TYPES_TMSBT[UA_TYPES_TMSBT_DAQKEYVALUEPAIR])
    ADD_CUSTOM_TYPE_MAPPING(UA_SelectionEntryStructure, &UA_TYPES_TMSBT[UA_TYPES_TMSBT_SELECTIONENTRYSTRUCTURE])
    ADD_CUSTOM_TYPE_MAPPING(UA_DeviceDomainStructure, &UA_TYPES_TMSDEVICE[UA_TYPES_TMSDEVICE_DEVICEDOMAINSTRUCTURE])
}
