//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 03.03.2025 20:46:25.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct Boolean Boolean;

    ErrCode EXPORTED Boolean_getValue(Boolean* obj, Bool* value);
    ErrCode EXPORTED Boolean_equalsValue(Boolean* obj, Bool value, Bool* equal);
    ErrCode EXPORTED Boolean_createBoolean(Boolean** obj, Bool value);
    ErrCode EXPORTED Boolean_createBoolObject(Boolean** obj, Bool value);

#ifdef __cplusplus
}
#endif
