//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 03.03.2025 20:46:31.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ccommon.h"

typedef struct Iterator Iterator;

    ErrCode EXPORTED Iterator_moveNext(Iterator* obj);
    ErrCode EXPORTED Iterator_getCurrent(Iterator* self, BaseObject** obj);

#ifdef __cplusplus
}
#endif
