= Examples

== How to emulate openDAQ(TM) native streaming server

Here, we consider the minimal package flow required from the server-side perspective to enable the native communication protocol to stream a single value signal with domain signal.

To simplify the example, let's assume that both the server and client are running on the same host. The server is reachable for the client via the IPv4 address "127.0.0.1" and port number 7420.
The client is either the openDAQ(TM) client application, based on the provided <<An openDAQ client application code example,code snippet below>>, or the openDAQ(TM) Python GUI application. In both scenarios, the client uses the connection string
"daq.ns://127.0.0.1:7420" to connect to the emulated server.

The emulated server will advertise two signals:

* _Value signal_: An asynchronous signal with a data type of double, having a symbolic ID of "/ValueSignal" and a numeric ID of "1"
* _Domain signal_: A signal with a data type of unsigned 64-bit integer, featuring a symbolic ID of "/DomainSignal" and a numeric ID of "2"

The server application needs to listen for incoming TCP connections on the loopback interface and port number 7420.
Once an incoming TCP connection is accepted, it should be upgraded to a WebSocket connection following the procedure outlined in the Establishing a connection section.

Once the connection is established, the server application should begin reading incoming data, expecting the receipt of a 4-byte package header first.
Upon receiving a xref:streaming.adoc#init_req[Streaming initialization request] from the client, it should reply with two xref:streaming.adoc#available[Signal available notification packages]: one for the value signal and another for the domain signal.

Below are examples of how the serialized signal strings inside signal available notifications might appear for the given scenario.

_Value signal_:

[source,json]
----
{
    "__type": "Signal",
    "domainSignalId": "/DomainSignal",
    "dataDescriptor": {
        "__type": "DataDescriptor",
        "name": "",
        "sampleType": 2,
        "dimensions": [],
        "rule": {
            "__type": "DataRule",
            "ruleType": 3,
            "params": {
                "__type": "Dict",
                "values": []
            }
        },
        "origin": "",
        "metadata": {
            "__type": "Dict",
            "values": []
        },
        "structFields": []
    },
    "public": true,
    "description": "Value signal description",
    "name": "ValueSignalName"
}
----

_Domain signal_:

[source,json]
----
{
    "__type": "Signal",
    "dataDescriptor": {
        "__type": "DataDescriptor",
        "name": "",
        "sampleType": 9,
        "dimensions": [],
        "rule": {
            "__type": "DataRule",
            "ruleType": 3,
            "params": {
                "__type": "Dict",
                "values": []
            }
        },
        "origin": "",
        "metadata": {
            "__type": "Dict",
            "values": []
        },
        "structFields": []
    },
    "public": true,
    "description": "Domain signal description",
    "name": "DomainSignalName"
}
----

Subsequently, the server application should send a xref:streaming.adoc#init_done_ack[Streaming initialization done acknowledgement] to finalize the streaming initialization process.
Following this, the server application should continue to read incoming data.
When it receives xref:streaming.adoc#subscribe_req[subscription requests] for the domain and value signals, it should respond with xref:streaming.adoc#subscribe_ack[subscription acknowledgements] for each request.

Once these xref:streaming.adoc#subscribe_ack[subscription acknowledgments] are sent, both the value and domain signals are considered as subscribed, and the server application can start sending signal packets for these signals.
Initially, the server should send the xref:packet_streaming:event_packet.adoc#ddc_event_packet[Data descriptor changed event packet], followed by the xref:packet_streaming:data_packet.adoc[data packets].

=== An openDAQ client application code example

[source,cpp]
----
#include <opendaq/opendaq.h>
#include <chrono>
#include <iostream>
#include <thread>
int main(int /*argc*/, const char* /*argv*/[])
{
    using namespace daq;
    // Create a new Instance that we will use for all the interactions with the SDK
    InstancePtr instance = Instance(MODULE_PATH);
    // Connect to a Native streaming server
    DevicePtr device = instance.addDevice("daq.ns://127.0.0.1:7420");
    // Exit if connection failed
    if (!device.assigned())
    {
        std::cerr << "Connection failed!" << std::endl;
        return 0;
    }
    // Get the value signal
    SignalPtr signal = device.getSignals()[0];
    // Read data of value signal
    const auto packetReader = PacketReader(signal);
    while (true)
    {
        const auto packet = packetReader.read();
        if (packet.assigned() && packet.getType() == PacketType::Data)
        {
            DataPacketPtr dataPacket = packet;
            const auto data = reinterpret_cast<double*>(dataPacket.getData());
            for (size_t index = 0; index < dataPacket.getSampleCount(); ++index)
                std::cout << "Value signal data: " << data[index] << std::endl;
        }
        else
        {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
    }
    return 0;
----

// == How to emulate openDAQ(TM) native configuration protocol server
// TODO
