//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 03.03.2025 20:46:27.
// </auto-generated>
//------------------------------------------------------------------------------

#include "dictobject.h"

#include <opendaq/opendaq.h>

ErrCode Dict_get(Dict* obj, BaseObject* key, BaseObject** value)
{
    return reinterpret_cast<daq::IDict*>(obj)->get(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject**>(value));
}

ErrCode Dict_set(Dict* obj, BaseObject* key, BaseObject* value)
{
    return reinterpret_cast<daq::IDict*>(obj)->set(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject*>(value));
}

ErrCode Dict_remove(Dict* obj, BaseObject* key, BaseObject** value)
{
    return reinterpret_cast<daq::IDict*>(obj)->remove(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject**>(value));
}

ErrCode Dict_deleteItem(Dict* obj, BaseObject* key)
{
    return reinterpret_cast<daq::IDict*>(obj)->deleteItem(reinterpret_cast<daq::IBaseObject*>(key));
}

ErrCode Dict_clear(Dict* obj)
{
    return reinterpret_cast<daq::IDict*>(obj)->clear();
}

ErrCode Dict_getCount(Dict* obj, SizeT* size)
{
    return reinterpret_cast<daq::IDict*>(obj)->getCount(size);
}

ErrCode Dict_hasKey(Dict* obj, BaseObject* key, Bool* hasKey)
{
    return reinterpret_cast<daq::IDict*>(obj)->hasKey(reinterpret_cast<daq::IBaseObject*>(key), hasKey);
}

ErrCode Dict_getKeyList(Dict* obj, List** keys)
{
    return reinterpret_cast<daq::IDict*>(obj)->getKeyList(reinterpret_cast<daq::IList**>(keys));
}

ErrCode Dict_getValueList(Dict* obj, List** values)
{
    return reinterpret_cast<daq::IDict*>(obj)->getValueList(reinterpret_cast<daq::IList**>(values));
}

ErrCode Dict_getKeys(Dict* obj, Iterable** iterable)
{
    return reinterpret_cast<daq::IDict*>(obj)->getKeys(reinterpret_cast<daq::IIterable**>(iterable));
}

ErrCode Dict_getValues(Dict* obj, Iterable** iterable)
{
    return reinterpret_cast<daq::IDict*>(obj)->getValues(reinterpret_cast<daq::IIterable**>(iterable));
}

ErrCode Dict_createDict(Dict** obj)
{
    daq::IDict* dict = nullptr;
    ErrCode err = daq::createDict(&dict);
    *obj = reinterpret_cast<Dict*>(dict);
    return err;
}

// ErrCode Dict_createDictWithExpectedTypes(Dict** obj, IntfID* keyType, IntfID* valueType)
// {
//     *obj = reinterpret_cast<Dict*>(daq::createDictWithExpectedTypes(keyType, valueType));
//     return 0;
// }
