//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.1.0) on 03.03.2025 20:46:28.
// </auto-generated>
//------------------------------------------------------------------------------

#include "float1.h"

#include <opendaq/opendaq.h>

ErrCode Float_getValue(FloatObject* obj, Float* value)
{
    return reinterpret_cast<daq::IFloat*>(obj)->getValue(value);
}

ErrCode Float_equalsValue(FloatObject* obj, Float value, Bool* equals)
{
    return reinterpret_cast<daq::IFloat*>(obj)->equalsValue(value, equals);
}

ErrCode Float_createFloat(FloatObject** obj, Float value)
{
    daq::IFloat* floatObj = nullptr;
    ErrCode err = daq::createFloat(&floatObj, value);
    *obj = reinterpret_cast<FloatObject*>(floatObj);
    return err;
}

ErrCode Float_createFloatObject(FloatObject** obj, Float value)
{
    daq::IFloat* floatObj = nullptr;
    ErrCode err = daq::createFloat(&floatObj, value);
    *obj = reinterpret_cast<FloatObject*>(floatObj);
    return err;
}
