name: Build openDAQ SDK
description: Configure, build and test openDAQ SDK

inputs:
  additional-dependencies:
    description: 'Additional packages to install (apt on Linux, choco on Windows)'
    required: false
    default: ''
  cmake-generator:
    description: 'CMake generator (e.g., "Ninja", "Visual Studio 17 2022")'
    required: false
    default: ''
  cmake-config-preset:
    description: 'CMake configure preset name'
    required: false
    default: ''
  cmake-config-args:
    description: 'Additional CMake configure arguments (e.g., -D flags)'
    required: false
    default: ''
  cmake-build-type:
    description: 'Build configuration (Release, Debug). Required for multi-config generators (Visual Studio)'
    required: false
    default: ''
  enable-tests:
    description: 'Run tests after build'
    required: false
    default: 'false'
  python-versions:
    description: 'Python version(s) to install (space-separated for multiple versions)'
    required: false
    default: ''

outputs:
  gtest-xml-path:
    description: 'Path to GTest XML reports directory'
    value: ${{ steps.test.outputs.gtest-xml-path }}

runs:
  using: composite
  steps:
    - name: Check inputs
      shell: bash
      env:
        CMAKE_GENERATOR: ${{ inputs.cmake-generator }}
      run: |
        if [ -z "$CMAKE_GENERATOR" ]; then
          echo "::error::✗ The cmake-generator input is not set."
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: pwsh
      run: choco install nsis ${{ inputs.additional-dependencies }} -y --no-progress

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          ${{ inputs.additional-dependencies || '' }} \
          lld mono-runtime libmono-system-json-microsoft4.0-cil libmono-system-data4.0-cil \
          libx11-dev libxi-dev libxcursor-dev libxrandr-dev libgl-dev libudev-dev libfreetype6-dev

    - name: Install ninja-build
      if: inputs.cmake-generator == 'Ninja'
      uses: seanmiddleditch/gha-setup-ninja@v5

    # https://github.com/actions/runner-images/issues/10001
    - name: Setup MSVC toolchain
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Python dependencies
      shell: bash
      run: |
        echo "Installing numpy for Python versions: $(python --version)"
        python -m pip install numpy
        echo "Done installing Python dependencies"

    - name: Configure
      id: cmake-config
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_GENERATOR: ${{ inputs.cmake-generator }}
        CI_GIT_BRANCH: ${{ github.head_ref }}
      run: |
        CMAKE_BUILD_PATH="build"
        mkdir -p "$CMAKE_BUILD_PATH"
        CMAKE_BUILD_PATH=$(cd "$CMAKE_BUILD_PATH" && pwd)
        echo "build-path=$CMAKE_BUILD_PATH" >> "$GITHUB_OUTPUT"

        CMAKE_ARGS=""
        if [ -n "${{ inputs.cmake-config-preset }}" ]; then
          CMAKE_ARGS="--preset ${{ inputs.cmake-config-preset }}"
        fi

        # Visual Studio specific options
        if [[ "$CMAKE_GENERATOR" == "Visual Studio"* ]]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_MSVC_SINGLE_PROCESS_BUILD=ON"
        fi

        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
        fi

        CMAKE_ARGS="$CMAKE_ARGS -DCI_GIT_BRANCH=$CI_GIT_BRANCH"

        echo "::group::CMake Configure"
        cmake -B "$CMAKE_BUILD_PATH" -G "$CMAKE_GENERATOR" $CMAKE_ARGS ${{ inputs.cmake-config-args }}
        echo "::endgroup::"

    - name: Build
      shell: bash
      env:
        SHORT_SHA: ci # .NET bindings version suffix (e.g., 1.0.0-beta-ci)
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        CMAKE_BUILD_ARGS=""
        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CMAKE_BUILD_ARGS="--config $CMAKE_BUILD_TYPE"
        fi

        echo "::group::CMake Build"
        cmake --build "$CMAKE_BUILD_PATH" $CMAKE_BUILD_ARGS
        echo "::endgroup::"

    - name: Grant Linux capabilities to test executables
      if: runner.os == 'Linux' && inputs.enable-tests == 'true'
      shell: bash
      env:
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        # Grant capability to test binaries that use raw sockets (e.g. ICMP ping for reachability checks)
        echo "::group::Grant CAP_NET_RAW"
        test="$CMAKE_BUILD_PATH/bin/test_device_modules"
        if [ -f "$test" ]; then
          sudo setcap cap_net_raw=ep "$test"
          echo "$test - Granted"
        fi
        echo "::endgroup::"

    - name: Test
      id: test
      if: inputs.enable-tests == 'true'
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        GTEST_XML_PATH="$CMAKE_BUILD_PATH/test_results"
        mkdir -p "$GTEST_XML_PATH"

        if command -v cygpath &> /dev/null; then
          GTEST_XML_PATH=$(cygpath -w "$GTEST_XML_PATH")
        fi

        export GTEST_OUTPUT="xml:$GTEST_XML_PATH/"
        echo "gtest-xml-path=$GTEST_XML_PATH" >> "$GITHUB_OUTPUT"

        CTEST_ARGS=""
        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CTEST_ARGS="--build-config $CMAKE_BUILD_TYPE"
        fi

        echo "::group::CTest"
        ctest --test-dir "$CMAKE_BUILD_PATH" --preset run_tests --output-on-failure $CTEST_ARGS
        echo "::endgroup::"
