name: Build openDAQ SDK
description: Configure, build and test openDAQ SDK

inputs:
  skip-setup-python:
    description: 'Skip actions/setup-python (for containers with pre-installed Python)'
    required: false
    default: 'false'
  skip-setup-ninja:
    description: 'Skip ninja-build installation action (for containers with pre-installed ninja)'
    required: false
    default: 'false'
  additional-dependencies:
    description: 'Additional packages to install (apt/yum on Linux, choco on Windows, brew on macOS)'
    required: false
    default: ''
  cmake-generator:
    description: 'CMake generator (e.g., "Ninja", "Visual Studio 17 2022")'
    required: false
    default: ''
  cmake-config-preset:
    description: 'CMake configure preset name'
    required: false
    default: ''
  cmake-config-args:
    description: 'Additional CMake configure arguments (e.g., -D flags)'
    required: false
    default: ''
  cmake-build-type:
    description: 'Build configuration (Release, Debug). Required for multi-config generators (Visual Studio)'
    required: false
    default: ''
  enable-32bit:
    description: 'Build for 32-bit architecture'
    required: false
    default: 'false'
  enable-tests:
    description: 'Run tests after build'
    required: false
    default: 'false'
  ctest-preset:
    description: 'CTest preset name'
    required: false
    default: ''
  bindings-csharp-version-suffix:
    description: 'Version suffix for C# bindings NuGet package (e.g., "ci" -> 1.0.0-beta-ci)'
    required: false
    default: 'ci'
  cpack-generator:
    description: 'CPack generator (NSIS, DEB, RPM, ZIP, TGZ). If set, Build Installer step will run'
    required: false
    default: ''
  generate-python-bindings:
    description: 'Generate Python bindings (true/false/empty). Empty = use preset or cmake-config-args'
    required: false
    default: ''
  generate-csharp-bindings:
    description: 'Generate C# bindings (true/false/empty). Empty = use preset or cmake-config-args'
    required: false
    default: ''
  package-artifact-name:
    description: 'Artifact name for installer upload. If empty, installer will not be uploaded'
    required: false
    default: ''
  package-artifact-retention-days:
    description: 'Retention days for installer artifact'
    required: false
    default: '7'

outputs:
  build-path:
    description: 'Path to build directory'
    value: ${{ steps.cmake-config.outputs.build-path }}
  gtest-xml-path:
    description: 'Path to GTest XML reports directory'
    value: ${{ steps.test.outputs.gtest-xml-path }}
  package-name:
    description: 'Installer artifact name (package filename without extension)'
    value: ${{ steps.build-installer.outputs.package-name }}
  package-path:
    description: 'Full path to the installer file'
    value: ${{ steps.build-installer.outputs.package-path }}

runs:
  using: composite
  steps:
    - name: Check inputs
      shell: bash
      env:
        CMAKE_GENERATOR: ${{ inputs.cmake-generator }}
      run: |
        if [ -z "$CMAKE_GENERATOR" ]; then
          echo "::error::✗ The cmake-generator input is not set."
          exit 1
        fi

    - name: Detect package manager
      id: detect-linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if command -v apt-get &> /dev/null; then
          echo "pkg-manager=apt" >> $GITHUB_OUTPUT
        elif command -v yum &> /dev/null; then
          echo "pkg-manager=yum" >> $GITHUB_OUTPUT
        else
          echo "::error::Can not detect package manager: expected apt or yum"
          exit 1
        fi

    - name: Set up Python
      if: |
        inputs.skip-setup-python != 'true' &&
        inputs.generate-python-bindings != 'false' &&
        !(inputs.enable-32bit == 'true' && runner.os == 'Linux')
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        architecture: ${{ inputs.enable-32bit == 'true' && 'x86' || 'x64' }}

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Install Windows dependencies
      if: runner.os == 'Windows' && inputs.additional-dependencies != ''
      shell: pwsh
      run: choco install ${{ inputs.additional-dependencies }} -y --no-progress

    - name: Remove conflicting packages (for 32-bit build)
      if: steps.detect-linux.outputs.pkg-manager == 'apt' && inputs.enable-32bit == 'true'
      shell: bash
      run: |
        echo "Removing bootloader packages that conflict with i386 multi-arch"
        if ! sudo apt-get remove -y --allow-remove-essential shim-signed grub-efi-amd64-signed grub2-common grub-efi-amd64-bin grub-common; then
          echo "::warning::Failed to remove bootloader packages"
        fi
        echo "Removing pre-installed 64-bit Python to avoid conflicts with 32-bit build"
        if ! sudo apt-get remove -y python3 python3-pip python3-dev; then
          echo "::warning::Failed to remove pre-installed Python packages"
        fi
        sudo apt-get autoremove -y

    - name: Install Linux dependencies (apt)
      if: steps.detect-linux.outputs.pkg-manager == 'apt'
      shell: bash
      env:
        ENABLE_32BIT: ${{ inputs.enable-32bit }}
      run: |
        if [ "$ENABLE_32BIT" == "true" ]; then
          sudo dpkg --add-architecture i386
          PKG_FILE=".github/packages/apt-i386.txt"
        else
          PKG_FILE=".github/packages/apt.txt"
        fi

        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          ${{ inputs.additional-dependencies || '' }} \
          $(cat "$PKG_FILE")

    - name: Install Linux dependencies (yum)
      if: steps.detect-linux.outputs.pkg-manager == 'yum'
      shell: bash
      run: |
        yum install -y \
          ${{ inputs.additional-dependencies }} \
          $(cat .github/packages/yum.txt)

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install mono ${{ inputs.additional-dependencies }}

    - name: Install ninja-build
      if: inputs.cmake-generator == 'Ninja' && inputs.skip-setup-ninja != 'true'
      uses: seanmiddleditch/gha-setup-ninja@v6

    - name: Setup MSYS2 MINGW64
      if: runner.os == 'Windows' && env.CXX == 'g++'
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc

    - name: Add MSYS2 MINGW64 to PATH
      if: runner.os == 'Windows' && env.CXX == 'g++'
      shell: bash
      run: |
        echo "${{ steps.msys2.outputs.msys2-location }}/mingw64/bin" >> $GITHUB_PATH
        echo "Added MSYS2 MINGW64 to PATH: ${{ steps.msys2.outputs.msys2-location }}/mingw64/bin"

    # https://github.com/actions/runner-images/issues/10001
    - name: Setup MSVC toolchain
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Intel LLVM compiler
      if: runner.os == 'Windows' && env.CXX == 'icx'
      uses: ./.github/actions/setup-compiler-icx

    - name: Install Python dependencies
      if: |
        inputs.skip-setup-python != 'true' &&
        inputs.generate-python-bindings != 'false' &&
        !(inputs.enable-32bit == 'true' && runner.os == 'Linux')
      shell: bash
      run: |
        echo "Installing numpy for Python: $(python --version)"
        python -m pip install numpy
        echo "Done installing Python dependencies"

    - name: Configure
      id: cmake-config
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_GENERATOR: ${{ inputs.cmake-generator }}
        CI_GIT_BRANCH: ${{ github.head_ref }}
        ENABLE_32BIT: ${{ inputs.enable-32bit }}
      run: |
        CMAKE_BUILD_PATH="build"
        mkdir -p "$CMAKE_BUILD_PATH"
        CMAKE_BUILD_PATH=$(cd "$CMAKE_BUILD_PATH" && pwd)
        if command -v cygpath &> /dev/null; then
          echo "build-path=$(cygpath -w "$CMAKE_BUILD_PATH")" >> "$GITHUB_OUTPUT"
        else
          echo "build-path=$CMAKE_BUILD_PATH" >> "$GITHUB_OUTPUT"
        fi

        CMAKE_ARGS=""
        if [ -n "${{ inputs.cmake-config-preset }}" ]; then
          CMAKE_ARGS="--preset ${{ inputs.cmake-config-preset }}"
        fi

        # Detect Visual Studio generator
        IS_VISUAL_STUDIO=false
        if [[ "$CMAKE_GENERATOR" == "Visual Studio"* ]]; then
          IS_VISUAL_STUDIO=true
        fi

        # Visual Studio specific options
        if [ "$IS_VISUAL_STUDIO" == "true" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_MSVC_SINGLE_PROCESS_BUILD=ON"
        fi

        # 32-bit build configuration
        if [ "$ENABLE_32BIT" == "true" ]; then
          if [ "$IS_VISUAL_STUDIO" == "true" ]; then
            CMAKE_ARGS="$CMAKE_ARGS -A Win32"
          else
            CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_FORCE_COMPILE_32BIT=ON"
          fi
        fi

        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
        fi

        CMAKE_ARGS="$CMAKE_ARGS -DCI_GIT_BRANCH=$CI_GIT_BRANCH"

        # Python bindings
        if [ "${{ inputs.generate-python-bindings }}" == "true" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_GENERATE_PYTHON_BINDINGS=ON"
        elif [ "${{ inputs.generate-python-bindings }}" == "false" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF"
        fi

        # C# bindings
        if [ "${{ inputs.generate-csharp-bindings }}" == "true" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_GENERATE_CSHARP_BINDINGS=ON"
        elif [ "${{ inputs.generate-csharp-bindings }}" == "false" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF"
        fi

        echo "::group::CMake Configure"
        cmake -B "$CMAKE_BUILD_PATH" -G "$CMAKE_GENERATOR" $CMAKE_ARGS ${{ inputs.cmake-config-args }}
        echo "::endgroup::"

    - name: Build
      shell: bash
      env:
        SHORT_SHA: ${{ inputs.bindings-csharp-version-suffix }}
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        CMAKE_BUILD_ARGS=""
        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CMAKE_BUILD_ARGS="--config $CMAKE_BUILD_TYPE"
        fi

        echo "::group::CMake Build"
        cmake --build "$CMAKE_BUILD_PATH" $CMAKE_BUILD_ARGS
        echo "::endgroup::"

    - name: Test
      id: test
      if: inputs.enable-tests == 'true'
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        GTEST_XML_PATH="$CMAKE_BUILD_PATH/test_results"
        mkdir -p "$GTEST_XML_PATH"

        if command -v cygpath &> /dev/null; then
          GTEST_XML_PATH=$(cygpath -w "$GTEST_XML_PATH")
        fi

        export GTEST_OUTPUT="xml:$GTEST_XML_PATH/"
        echo "gtest-xml-path=$GTEST_XML_PATH" >> "$GITHUB_OUTPUT"

        CTEST_ARGS=""
        if [ -n "${{ inputs.ctest-preset }}" ]; then
          CTEST_ARGS="--preset ${{ inputs.ctest-preset }}"
        fi

        if [ -n "$CMAKE_BUILD_TYPE" ]; then
          CTEST_ARGS="$CTEST_ARGS --build-config $CMAKE_BUILD_TYPE"
        fi

        SUDO_CMD=""
        if command -v sudo &> /dev/null; then
          SUDO_CMD="sudo -E"
        fi

        echo "::group::CTest"
        $SUDO_CMD ctest --test-dir "$CMAKE_BUILD_PATH" --output-on-failure $CTEST_ARGS
        echo "::endgroup::"

    - name: Build Installer
      id: build-installer
      if: inputs.cpack-generator != ''
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{ inputs.cmake-build-type }}
        CMAKE_BUILD_PATH: ${{ steps.cmake-config.outputs.build-path }}
      run: |
        # Convert Windows path to unix if needed
        if command -v cygpath &> /dev/null; then
          CMAKE_BUILD_PATH=$(cygpath -u "$CMAKE_BUILD_PATH")
        fi

        PACKAGE_NAME=$(grep 'CPACK_PACKAGE_FILE_NAME' "$CMAKE_BUILD_PATH/CPackConfig.cmake" | cut -d'"' -f2)

        case "${{ inputs.cpack-generator }}" in
          NSIS) PACKAGE_EXT="exe" ;;
          ZIP) PACKAGE_EXT="zip" ;;
          TGZ) PACKAGE_EXT="tar.gz" ;;
          DEB) PACKAGE_EXT="deb" ;;
          RPM) PACKAGE_EXT="rpm" ;;
          *) echo "Unknown generator: ${{ inputs.cpack-generator }}" && exit 1 ;;
        esac

        PACKAGE_PATH="$CMAKE_BUILD_PATH/_packages"

        echo "::group::CPack"
        cpack --config "$CMAKE_BUILD_PATH/CPackConfig.cmake" -B "$PACKAGE_PATH" -C "$CMAKE_BUILD_TYPE" -G ${{ inputs.cpack-generator }}
        echo "::endgroup::"

        PACKAGE_FILE_PATH="$PACKAGE_PATH/$PACKAGE_NAME.$PACKAGE_EXT"

        echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        if command -v cygpath &> /dev/null; then
          echo "package-path=$(cygpath -w "$PACKAGE_FILE_PATH")" >> $GITHUB_OUTPUT
        else
          echo "package-path=$PACKAGE_FILE_PATH" >> $GITHUB_OUTPUT
        fi

    - name: Upload Installer
      if: inputs.cpack-generator != '' && inputs.package-artifact-name != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package-artifact-name }}
        path: ${{ steps.build-installer.outputs.package-path }}
        retention-days: ${{ inputs.package-artifact-retention-days }}
