//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:57.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/streaming/mirrored_device_config.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_MIRRORED_DEVICE_CONFIG_INTF_ID = { daq::IMirroredDeviceConfig::Id.Data1, daq::IMirroredDeviceConfig::Id.Data2, daq::IMirroredDeviceConfig::Id.Data3, daq::IMirroredDeviceConfig::Id.Data4_UInt64 };

daqErrCode daqMirroredDeviceConfig_addStreamingSource(daqMirroredDeviceConfig* self, daqStreaming* streamingSource)
{
    return reinterpret_cast<daq::IMirroredDeviceConfig*>(self)->addStreamingSource(reinterpret_cast<daq::IStreaming*>(streamingSource));
}

daqErrCode daqMirroredDeviceConfig_removeStreamingSource(daqMirroredDeviceConfig* self, daqString* streamingConnectionString)
{
    return reinterpret_cast<daq::IMirroredDeviceConfig*>(self)->removeStreamingSource(reinterpret_cast<daq::IString*>(streamingConnectionString));
}
