//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.5.0) on 14.04.2025 21:38:13.
// </auto-generated>
//------------------------------------------------------------------------------

#include "copendaq/streaming/streaming.h"

#include <opendaq/opendaq.h>

#include "copendaq_private.h"

const IntfID STREAMING_INTF_ID = { daq::IStreaming::Id.Data1, daq::IStreaming::Id.Data2, daq::IStreaming::Id.Data3, daq::IStreaming::Id.Data4_UInt64 };

ErrCode Streaming_getActive(Streaming* self, Bool* active)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getActive(active);
}

ErrCode Streaming_setActive(Streaming* self, Bool active)
{
    return reinterpret_cast<daq::IStreaming*>(self)->setActive(active);
}

ErrCode Streaming_addSignals(Streaming* self, List* signals)
{
    return reinterpret_cast<daq::IStreaming*>(self)->addSignals(reinterpret_cast<daq::IList*>(signals));
}

ErrCode Streaming_removeSignals(Streaming* self, List* signals)
{
    return reinterpret_cast<daq::IStreaming*>(self)->removeSignals(reinterpret_cast<daq::IList*>(signals));
}

ErrCode Streaming_removeAllSignals(Streaming* self)
{
    return reinterpret_cast<daq::IStreaming*>(self)->removeAllSignals();
}

ErrCode Streaming_getConnectionString(Streaming* self, String** connectionString)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

ErrCode Streaming_getConnectionStatus(Streaming* self, Enumeration** connectionStatus)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getConnectionStatus(reinterpret_cast<daq::IEnumeration**>(connectionStatus));
}
