//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 22:07:59.
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/streaming/streaming.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_STREAMING_INTF_ID = { daq::IStreaming::Id.Data1, daq::IStreaming::Id.Data2, daq::IStreaming::Id.Data3, daq::IStreaming::Id.Data4_UInt64 };

daqErrCode daqStreaming_getActive(daqStreaming* self, daqBool* active)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getActive(active);
}

daqErrCode daqStreaming_setActive(daqStreaming* self, daqBool active)
{
    return reinterpret_cast<daq::IStreaming*>(self)->setActive(active);
}

daqErrCode daqStreaming_addSignals(daqStreaming* self, daqList* signals)
{
    return reinterpret_cast<daq::IStreaming*>(self)->addSignals(reinterpret_cast<daq::IList*>(signals));
}

daqErrCode daqStreaming_removeSignals(daqStreaming* self, daqList* signals)
{
    return reinterpret_cast<daq::IStreaming*>(self)->removeSignals(reinterpret_cast<daq::IList*>(signals));
}

daqErrCode daqStreaming_removeAllSignals(daqStreaming* self)
{
    return reinterpret_cast<daq::IStreaming*>(self)->removeAllSignals();
}

daqErrCode daqStreaming_getConnectionString(daqStreaming* self, daqString** connectionString)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

daqErrCode daqStreaming_getConnectionStatus(daqStreaming* self, daqEnumeration** connectionStatus)
{
    return reinterpret_cast<daq::IStreaming*>(self)->getConnectionStatus(reinterpret_cast<daq::IEnumeration**>(connectionStatus));
}
