/*
 * Copyright 2022-2023 Blueberry d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CSharpGenerator v1.0.0) on D-E-B-U-G.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Daq.Core.Types;


[StructLayout(LayoutKind.Sequential)]
internal unsafe class RawBoolObject : RawBaseObject
{
    //ErrorCode getValue(daq.Bool* value); stdcall;
    public delegate* unmanaged[Stdcall]<IntPtr, out bool, ErrorCode> GetValue;
    //ErrorCode equalsValue(const daq.Bool value, daq.Bool* equal); stdcall;
    public delegate* unmanaged[Stdcall]<IntPtr, bool, out bool, ErrorCode> EqualsValue;
}

[Guid("9f20e31a-d0fb-5679-a188-4942b3fed6e2")]
public class BoolObject : BaseObject
{
    //type-casted base._virtualTable
    private readonly RawBoolObject _rawBoolObject;

    internal BoolObject(IntPtr nativePointer, bool incrementReference)
        : base(nativePointer, incrementReference)
    {
        IntPtr objVirtualTable = Marshal.ReadIntPtr(nativePointer, 0); //read the pointer from the given address
        base._virtualTable =
            _rawBoolObject = Marshal.PtrToStructure<RawBoolObject>(objVirtualTable);
    }

    /// <summary>Gets a boolean value stored in the object.</summary>
    /// <remarks>Call this method to extract the boolean value that is stored in the object.</remarks>
    /// <returns>Stored boolean value.</returns>
    public bool GetValue()
    {
        //native output argument
        bool value;

        unsafe //use native function pointer
        {
            //call native function
            ErrorCode errorCode = (ErrorCode)_rawBoolObject.GetValue(base.NativePointer, out value);

            if (Result.Failed(errorCode))
            {
                throw new OpenDaqException(errorCode);
            }
        }

        return value;
    }

    /// <summary>Compares stored boolean value to the boolean parameter.</summary>
    /// <remarks>Call this method to directly compare the object to the boolean parameter.</remarks>
    /// <param name="value">Value for comparison.</param>
    /// <returns>The result of the comparison.</returns>
    public bool EqualsValue(bool value)
    {
        //native output argument
        bool equal;

        unsafe //use native function pointer
        {
            //call native function
            ErrorCode errorCode = (ErrorCode)_rawBoolObject.EqualsValue(base.NativePointer, value, out equal);

            if (Result.Failed(errorCode))
            {
                throw new OpenDaqException(errorCode);
            }
        }

        return equal;
    }

    #region operators

    //implicit cast operators

    /// <summary>Performs an implicit conversion from <see cref="bool"/> to <see cref="Daq.Core.Types.BoolObject"/>.</summary>
    /// <param name="value">The managed <c>bool</c> value.</param>
    /// <returns>The SDK <c>BoolObject</c>.</returns>
    public static implicit operator BoolObject(bool value) => CoreTypesFactory.CreateBoolean(value);

    /// <summary>Performs an implicit conversion from <see cref="Daq.Core.Types.BoolObject"/> to <see cref="bool"/>.</summary>
    /// <param name="boolObject">The SDK <c>BoolObject</c>.</param>
    /// <returns>The managed <c>bool</c> value.</returns>
    public static implicit operator bool(BoolObject boolObject) => boolObject.GetValue();

    /// <summary>Determines whether this instance and a specified <c>bool</c>, have the same value.</summary>
    /// <param name="other">The other <c>bool</c> to compare to this instance.</param>
    /// <returns><c>true</c> if the other <c>bool</c> value is the same as this instance; otherwise, <c>false</c>.</returns>
    public bool Equals(bool other) => ((bool)this).Equals(other);


    #endregion operators
}


#region Class Factory

// Factory functions of the &apos;CoreTypes&apos; library.
public static partial class CoreTypesFactory
{
    //ErrorCode createBoolean(daq.IBoolean** obj, daq.Bool value); cdecl;
    [DllImport(CoreTypesDllInfo.FileName, CallingConvention = CallingConvention.Cdecl)]
    private static extern ErrorCode createBoolean(out IntPtr obj, bool value);

    public static ErrorCode CreateBoolean(out BoolObject obj, bool value)
    {
        //initialize output argument
        obj = default;

        //native output argument
        IntPtr objPtr;

        //call native function
        ErrorCode errorCode = createBoolean(out objPtr, value);

        if (Result.Succeeded(errorCode))
        {
            //create object
            obj = new BoolObject(objPtr, incrementReference: false);
        }

        return errorCode;
    }

    public static BoolObject CreateBoolean(bool value)
    {
        //native output argument
        IntPtr objPtr;

        //call native function
        ErrorCode errorCode = createBoolean(out objPtr, value);

        if (Result.Failed(errorCode))
        {
            throw new OpenDaqException(errorCode);
        }

        //create and return object
        return new BoolObject(objPtr, incrementReference: false);
    }


    //ErrorCode createBoolObject(daq.IBoolean** obj, daq.Bool value); cdecl;
    [DllImport(CoreTypesDllInfo.FileName, CallingConvention = CallingConvention.Cdecl)]
    private static extern ErrorCode createBoolObject(out IntPtr obj, bool value);

    public static ErrorCode CreateBoolObject(out BoolObject obj, bool value)
    {
        //initialize output argument
        obj = default;

        //native output argument
        IntPtr objPtr;

        //call native function
        ErrorCode errorCode = createBoolObject(out objPtr, value);

        if (Result.Succeeded(errorCode))
        {
            //create object
            obj = new BoolObject(objPtr, incrementReference: false);
        }

        return errorCode;
    }

    public static BoolObject CreateBoolObject(bool value)
    {
        //native output argument
        IntPtr objPtr;

        //call native function
        ErrorCode errorCode = createBoolObject(out objPtr, value);

        if (Result.Failed(errorCode))
        {
            throw new OpenDaqException(errorCode);
        }

        //create and return object
        return new BoolObject(objPtr, incrementReference: false);
    }
}

#endregion Class Factory
