function(set_mode MODE)
    set_property(GLOBAL PROPERTY ALLOW_BANNED_FUNCTIONS ${MODE})
endfunction()

function(get_mode MODE)
    get_property(CMAKE_MODE GLOBAL PROPERTY ALLOW_BANNED_FUNCTIONS)

    set(${MODE} ${CMAKE_MODE} PARENT_SCOPE)
endfunction()

function(include_directories)
    get_property(mode GLOBAL PROPERTY ALLOW_BANNED_FUNCTIONS)
    if (mode STREQUAL "ANCIENT")
        _include_directories(${ARGN})
    elseif (mode STREQUAL "MODERN")
        message(FATAL_ERROR "Use target based target_include_directories")
    else()
        message(FATAL_ERROR "Unknown mode \"${mode}\" when using include_directories()")
    endif()
endfunction()

function(add_definitions)
    get_property(mode GLOBAL PROPERTY ALLOW_BANNED_FUNCTIONS)
    if (mode STREQUAL "ANCIENT")
        _include_directories(${ARGN})
    elseif (mode STREQUAL "MODERN")
        message(FATAL_ERROR "Use target based target_compile_definitions() or target_compile_options()")
    else()
        message(FATAL_ERROR "Unknown mode \"${mode}\" when using add_definitions()")
    endif()
endfunction()

function(link_directories)
    get_property(mode GLOBAL PROPERTY ALLOW_BANNED_FUNCTIONS)
    if (mode STREQUAL "ANCIENT")
        _include_directories(${ARGN})
    elseif (mode STREQUAL "MODERN")
        message(FATAL_ERROR "Use target based target_link_directories()")
    else()
        message(FATAL_ERROR "Unknown mode \"${mode}\" when using link_directories()")
    endif()
endfunction()

set_mode(MODERN)
