set(OPENDAQ_LOG_LEVELS Trace Debug Info Warning Error Critical Off)

function(log_level_str_to_int STR RET)
    string(TOLOWER ${STR} STR)
    if(${STR} STREQUAL "trace")
        set(${RET} 0 PARENT_SCOPE)
    elseif(${STR} STREQUAL "debug")
        set(${RET} 1 PARENT_SCOPE)
    elseif(${STR} STREQUAL "info")
        set(${RET} 2 PARENT_SCOPE)
    elseif(${STR} STREQUAL "warning")
        set(${RET} 3 PARENT_SCOPE)
    elseif(${STR} STREQUAL "error")
        set(${RET} 4 PARENT_SCOPE)
    elseif(${STR} STREQUAL "critical")
        set(${RET} 5 PARENT_SCOPE)
    elseif(${STR} STREQUAL "off")
        set(${RET} 6 PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Log level should be one of ${OPENDAQ_LOG_LEVELS}")
    endif()
endfunction()