if(DEFINED DAQMODULES_REF_FB_MODULE_CMAKE_OPTIONS_INCLUDED)
  return()
endif()
set(DAQMODULES_REF_FB_MODULE_CMAKE_OPTIONS_INCLUDED TRUE)

cmake_dependent_option(DAQMODULES_REF_FB_MODULE_ENABLE_RENDERER "Enable renderer function block" ON "DAQMODULES_REF_FB_MODULE OR NOT DAQMODULES_REF_FB_MODULE_BUILDING_AS_SUBMODULE" ON)
