name: Check License Agreement in headers

on:
  push:
    paths-ignore:
      - '*.adoc'
      - '*.md'
      - 'media/**'

  workflow_dispatch:

jobs:
  check_headers:
    runs-on: ubuntu-22.04
    name: Check SDK Source Headers
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install license-header-checker to ./shared/tools/license-header-checker/bin
        working-directory: ./shared/tools/license-header-checker
        run: ./do-license-header-check.sh --install

      - name: Run license check and modification (container only)
        working-directory: ./shared/tools/license-header-checker
        run: ./do-license-header-check.sh --fix

      - name: Show changed files and fail if there are any
        run: |
            git status -s
            [[ -z `git status -s` ]]
