name: Build and Test openDAQ

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_call:
    inputs:
      cmake_preset:
        type: string
        required: false
        default: "ci"
      ctest_preset:
        type: string
        required: false
        default: "run_tests"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-2022
    name: ${{ matrix.name }}
    if: ${{ ! github.event.pull_request.draft }}
    name: openDAQ
    uses: openDAQ/openDAQ-CI/.github/workflows/reusable.yml@v2
    with:
      timeout: '[{"timeout-minutes": 270}]'
      include-jobs: >
        [
          "windows-2022-x86_64-msvs-v143-debug",
          "windows-2022-x86-msvs-v143-release",
          "windows-2022-x86_64-ninja-clang-release",
          "windows-2022-x86_64-ninja-intel-cc-release",
          "ubuntu-20.04-x86-ninja-gcc-7-release",
          "ubuntu-20.04-x86_64-ninja-clang-9-release",
          "ubuntu-24.04-x86_64-ninja-gcc-14-debug",
          "ubuntu-24.04-x86_64-ninja-gcc-14-release",
          "ubuntu-24.04-x86_64-ninja-clang-18-release",
          "macos-26-x86_64-ninja-appleclang-debug",
          "macos-26-armv8-ninja-appleclang-release",
          "macos-15-x86_64-ninja-appleclang-release"
        ]
      packages: >
        [
          {
            "match-jobs": ["ubuntu-*-x86_64-*"],
            "apt-install": ["lld", "libx11-dev", "libxi-dev", "libxcursor-dev", "libxrandr-dev", "libgl-dev", "libudev-dev", "libfreetype6-dev"]
          },
          {
            "match-jobs": ["ubuntu-*-x86-*"],
            "apt-install": ["lld", "libx11-dev:i386", "libxi-dev:i386", "libxcursor-dev:i386", "libxrandr-dev:i386", "libgl-dev:i386", "libudev-dev:i386", "libfreetype6-dev:i386"]
          },
          {
            "match-jobs": ["windows-*", "*-x86_64-*", "macos-*"],
            "pip-install": ["numpy"],
            "use-python-version": "3.14"
          },
          {
            "match-jobs": ["ubuntu-20.04-*-clang-9-*"],
            "use-python-version": "3.8"
          }
        ]
      cmake-presets: >
        [
          {
            "configure-preset": "${{ inputs.cmake_preset || 'ci' }}",
            "test-preset": "${{ inputs.ctest_preset || 'run_tests' }}",
            "cache-variables": {"OPENDAQ_PYTHON_VERSION": "3.14"}
          },
          {
            "match-jobs": ["windows-*-msvs-*"],
            "cache-variables": {"OPENDAQ_MSVC_SINGLE_PROCESS_BUILD": true}
          },
          {
            "match-jobs": ["macos-*"],
            "run-tests-priv": true,
            "cache-variables": {"CMAKE_OSX_DEPLOYMENT_TARGET": "10.15"}
          },
          {
            "match-jobs": ["ubuntu-20.04-*-gcc-7-*", "ubuntu-20.04-*-clang-9-*"],
            "cache-variables": {
              "DAQMODULES_REF_FB_MODULE_ENABLE_RENDERER": false,
              "DAQMODULES_BASIC_CSV_RECORDER_MODULE": false,
              "OPENDAQ_PYTHON_VERSION": "3.8"
            }
          },
          {
            "match-jobs": ["ubuntu-20.04-x86-*"],
            "cache-variables": {
              "OPENDAQ_FORCE_COMPILE_32BIT": true,
              "OPENDAQ_GENERATE_PYTHON_BINDINGS": false,
              "OPENDAQ_GENERATE_CSHARP_BINDINGS": false,
              "CMAKE_CXX_FLAGS": "-Wno-error=shift-count-overflow"
            }
          },
          {
            "match-jobs": ["*-intel-cc-*"],
            "cache-variables": {
              "OPENDAQ_GENERATE_PYTHON_BINDINGS": false,
              "OPENDAQ_GENERATE_CSHARP_BINDINGS": false
            }
          }
        ]
