name: Build and Upload Artifacts

on:
  push:
    branches:
      - jira/*

  pull_request:
    branches:
      - jira/*

  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cache-key-os: linux
            cmake-build-generator: Ninja
            cmake-package-generator: DEB
            cmake-parallel: --parallel 2
            # cmake-preset: --preset package
            cmake-preset: ''
            cmake-config: Release
            cmake-defines:
              -DOPENDAQ_ENABLE_TESTS=OFF
              # -DCMAKE_SYSTEM_NAME=Linux
              # -DCMAKE_SYSTEM_PROCESSOR=x86_64
              # -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              # -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              # -DDAQMODULES_REF_FB_MODULE=OFF
              # -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              # -DDAQMODULES_REF_DEVICE_MODULE=OFF
              # -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              # -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              # -DOPENDAQ_ENABLE_OPCUA=OFF
              # -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              # -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
            cmake-compiler:
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_C_COMPILER=gcc
              -DCMAKE_CXX_COMPILER=g++

          - os: windows-latest
            cache-key-os: windows
            # cmake-build-generator: 'Visual Studio 17 2022'
            cmake-build-generator: Ninja
            cmake-package-generator: NSIS
            cmake-parallel: ''
            # cmake-preset: --preset package
            cmake-preset: ''
            cmake-config: Release
            cmake-defines:
              -DOPENDAQ_ENABLE_TESTS=OFF
              # -DCMAKE_CXX_FLAGS="/MP /bigobj"
              # -DCMAKE_C_FLAGS="/MP /bigobj"
              # -DCMAKE_SYSTEM_NAME=Linux
              # -DCMAKE_SYSTEM_PROCESSOR=x86_64
              # -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              # -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              # -DDAQMODULES_REF_FB_MODULE=OFF
              # -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              # -DDAQMODULES_REF_DEVICE_MODULE=OFF
              # -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              # -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              # -DOPENDAQ_ENABLE_OPCUA=OFF
              # -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              # -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
            cmake-compiler:
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_C_COMPILER=cl
              -DCMAKE_CXX_COMPILER=cl

          - os: macos-13
            cache-key-os: macos13
            cmake-build-generator: Ninja
            cmake-package-generator: ZIP
            cmake-parallel: --parallel 4
            # cmake-preset: --preset package
            cmake-preset: ''
            cmake-config: Release
            cmake-defines:
              -DOPENDAQ_ENABLE_TESTS=OFF
              # -DCMAKE_SYSTEM_NAME=MacOS
              # -DCMAKE_SYSTEM_PROCESSOR=x86_64
              # -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              # -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              # -DDAQMODULES_REF_FB_MODULE=OFF
              # -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              # -DDAQMODULES_REF_DEVICE_MODULE=OFF
              # -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              # -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              # -DOPENDAQ_ENABLE_OPCUA=OFF
              # -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              # -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF

            cmake-compiler:
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++

    runs-on: ${{ matrix.os }}

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      SCCACHE_DIR: ${{ github.workspace }}\.sccache

    steps:
      - name: Checkout openDAQ repository
        uses: actions/checkout@v4

      - name: Install dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libx11-dev \
              libxrandr-dev \
              libxcursor-dev \
              libxi-dev \
              libgl1-mesa-dev \
              mesa-common-dev \
              freeglut3-dev \
              libudev-dev \
              libfreetype6-dev \
              python3.12-dev \
              python3-pip \
              mono-complete \
              ccache

      - name: Install dependencies Windows
        if: runner.os == 'Windows'
        run: |
          choco install ccache ninja nsis vswhere -y

      - name: Install dependencies MacOS
        if: runner.os == 'macOS'
        run: |
          brew install ccache

      - name: Restore compiler cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ hashFiles('**/*.c','**/*.cpp') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Setup MSVC environment
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $vsPath = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          if (-not $vsPath) { Write-Error "Visual Studio not found"; exit 1 }

          $vcvarsall = Join-Path $vsPath 'VC\Auxiliary\Build\vcvarsall.bat'
          if (-not (Test-Path $vcvarsall)) { Write-Error "vcvarsall.bat not found"; exit 1 }

          cmd /c "`"$vcvarsall`" x64 && set" | ForEach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              $name = $matches[1]
              $value = $matches[2]
              echo "$name=$value" >> $env:GITHUB_ENV
            }
          }

      - name: Configure openDAQ CMake build
        run: cmake -S . -B build -G "${{ matrix.cmake-build-generator }}" ${{ matrix.cmake-preset }} ${{ matrix.cmake_defines }} ${{ matrix.cmake-compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }}

      - name: Perfrom openDAQ CMake build
        run: cmake --build build --config Release ${{ matrix.cmake-parallel }}

      - name: Package openDAQ CPack
        run: cpack --config build/CPackConfig.cmake -G ${{ matrix.cmake-package-generator }}

      - name: Read openDAQ version
        id: opendaq-framework-version
        shell: bash
        run: |
          OPENDAQ_VERSION=$(cat opendaq_version)
          echo Head openDAQ version: $OPENDAQ_VERSION
          echo "name=$OPENDAQ_VERSION" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        id: opendaq-upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: opendaq-${{ steps.opendaq-framework-version.outputs.name }}-${{ matrix.cmake-package-generator }}
          path: build/_packages/*
          retention-days: 1

      - name: Output artifact ID
        run: |
          echo 'Artifact ID:..... ${{ steps.opendaq-upload-artifact.outputs.artifact-id }}'
          echo 'Artifact URL:.... ${{ steps.opendaq-upload-artifact.outputs.artifact-url }}'
          echo 'Artifact digest:. ${{ steps.opendaq-upload-artifact.outputs.artifact-digest }}'

      - name: Print compiler cache stats (Unix)
        run: |
          echo "=== ccache stats ==="
          ccache -s
