name: Build and Upload Artifacts

on:
  push:
    branches:
      - jira/*

  pull_request:
    branches:
      - jira/*

  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cmake-build-generator: Ninja
            cmake-package-generator: DEB
            cmake-preset: --preset package
            cmake-config: Release
            cmake-defines:
              -DCMAKE_SYSTEM_NAME=Linux
              -DCMAKE_SYSTEM_PROCESSOR=x86_64
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
            cmake-compiler:
              -DCMAKE_C_COMPILER=gcc
              -DCMAKE_CXX_COMPILER=g++

          - os: windows-latest
            cmake-build-generator: 'Visual Studio 17 2022'
            cmake-package-generator: NSIS
            cmake-preset: --preset package
            cmake-config: Release
            cmake-defines:
              -DCMAKE_SYSTEM_NAME=Linux
              -DCMAKE_SYSTEM_PROCESSOR=x86_64
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
            cmake-compiler:
              -DCMAKE_C_COMPILER=gcc
              -DCMAKE_CXX_COMPILER=g++

          - os: macos-13
            cmake-build-generator: Ninja
            cmake-package-generator: ZIP
            cmake-preset: ''
            cmake-config: Release
            cmake-defines:
              -DOPENDAQ_ENABLE_TESTS=OFF
              # -DCMAKE_SYSTEM_NAME=MacOS
              # -DCMAKE_SYSTEM_PROCESSOR=x86_64
              # -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              # -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              # -DDAQMODULES_REF_FB_MODULE=OFF
              # -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              # -DDAQMODULES_REF_DEVICE_MODULE=OFF
              # -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              # -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              # -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              # -DOPENDAQ_ENABLE_OPCUA=OFF
              # -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              # -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF

            cmake-compiler:
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++


    runs-on: ${{ matrix.os }}

    steps:
      - name: Cache dependencies (Linux/APT)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/.github/workflows/package-artifacts.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache dependencies (Windows/Chocolatey)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-choco-${{ hashFiles('**/.github/workflows/package-artifacts.yml') }}
          restore-keys: |
            ${{ runner.os }}-choco-

      - name: Install dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libx11-dev \
              libxrandr-dev \
              libxcursor-dev \
              libxi-dev \
              libgl1-mesa-dev \
              mesa-common-dev \
              freeglut3-dev \
              libudev-dev \
              libfreetype6-dev \
              python3.12-dev \
              python3-pip \
              mono-complete

      - name: Install dependencies Windows
        if: runner.os == 'Windows'
        run: |
          choco install nsis -y

      - name: Checkout openDAQ repository
        uses: actions/checkout@v4

      - name: Configure openDAQ CMake build
        run: cmake -S . -B build -G "${{ matrix.cmake-build-generator }}" ${{ matrix.cmake-preset }} ${{ matrix.cmake_defines }} ${{ matrix.cmake-compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }}

      - name: Perfrom openDAQ CMake build
        run: cmake --build build --config Release

      - name: Package openDAQ CPack
        run: cpack --config build/CPackConfig.cmake -G ${{ matrix.cmake-package-generator }}

      - name: Read openDAQ version
        id: opendaq-framework-version
        shell: bash
        run: |
          OPENDAQ_VERSION=$(cat opendaq_version)
          echo Head openDAQ version: $OPENDAQ_VERSION
          echo "name=$OPENDAQ_VERSION" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        id: opendaq-upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: opendaq-${{ steps.opendaq-framework-version.outputs.name }}-${{ matrix.cmake-package-generator }}
          path: build/_packages/*
          retention-days: 1

      - name: Output artifact ID
        run: |
          echo 'Artifact ID:..... ${{ steps.opendaq-upload-artifact.outputs.artifact-id }}'
          echo 'Artifact URL:.... ${{ steps.opendaq-upload-artifact.outputs.artifact-url }}'
          echo 'Artifact digest:. ${{ steps.opendaq-upload-artifact.outputs.artifact-digest }}'
