name: openDAQ regression tests

on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}] # Run every day at midnight
  push: # TODO: delete this before merge
    branches: [regression-tests]
  
env:
  target_tag: v3.0.0
  cmake_preset: regression_tests
  test_path: ${{ github.workspace }}/junit_reports/

jobs:
  regression_tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    # ${{ }} expression syntax because of leading '!'
    # if: ${{ ! github.event.pull_request.draft }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}-${{ matrix.name }} #TODO: not sure if needed
      cancel-in-progress: true
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04 gcc-12 Release
            image: ubuntu:22.04
            cmake_generator: Ninja
            cmake_build_type: Release
            cmake_defines: -DOPENDAQ_ENABLE_REGRESSION_TESTS=ON
            apt_packages: g++-12
            cc: gcc-12
            cxx: g++-12
            cpack: DEB

    container:
      image: ${{ matrix.image }}
      env:
        TZ: Europe/Berlin
        DEBIAN_FRONTEND: noninteractive
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}

    steps:
      - name: Install basic dependencies
        run: |
          apt-get update
          apt-get install -y git openssh-client
          
      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      # TODO: probably don't need everything listed here?
      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends ${{ matrix.apt_packages }} \
            lld ninja-build curl \
            python3-dev python3-numpy python3-distutils python3-pip \
            mono-runtime libmono-system-json-microsoft4.0-cil libmono-system-data4.0-cil \
            libx11-dev libxcursor-dev libxrandr-dev libgl-dev libudev-dev libfreetype6-dev

      - name: Install latest CMake
        run: pip install cmake

      - name: Checkout target
        uses: actions/checkout@v3
        with:
          ref: ${{ env.target_tag }}
          path: target
      
      # TODO: this this step can be safely deleted if the regression_tests preset exists in target (it doesn't exist in openDAQ version 3.0.0)
      # -> maybe not because we always want to have the latest version?
      - name: Checkout CMakePresets.json to get the regression_tests preset
        uses: Bhacaz/checkout-files@v2
        with:
          files: CMakePresets.json
          branch: ${{ github.head_ref || github.ref_name }}

      # TODO: this this step can be safely deleted if the regression_tests preset exists in target (it doesn't exist in openDAQ version 3.0.0)
      # -> maybe not because we always want to have the latest version?
      - name: Move CMakePresets.json to target folder
        run: mv CMakePresets.json target

      # TODO: regression_simulator checkout and move!

      - name: Configure target
        working-directory: target
        run: | #TODO: DCI_GIT_BRANCH?
          mkdir build
          cd build
          cmake -G ${{ matrix.cmake_generator }} --preset ${{ env.cmake_preset }} ${{ matrix.cmake_defines }} -DCI_GIT_BRANCH=${{ github.head_ref }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} ..

      - name: Build target
        working-directory: target/build
        run: cmake --build .

      - name: Checkout current
        uses: actions/checkout@v3
        with:
          path: current
        
      - name: Configure current
        working-directory: current
        run: | #TODO: DCI_GIT_BRANCH?
          mkdir build
          cd build
          cmake -G ${{ matrix.cmake_generator }} --preset ${{ env.cmake_preset }} ${{ matrix.cmake_defines }} -DCI_GIT_BRANCH=${{ github.head_ref }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} ..

      - name: Build current
        working-directory: current/build
        run: cmake --build .

      # TODO: run regression_simulator instead
      - name: Run simulator from target and perform regression tests from current
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}"
        run: |
          cd target/build/bin
          ./quick_start_simulator &
          sleep 5
          cd ../../../current/build
          cmake -E env protocol=opcua ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test
          cmake -E env protocol=nd ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test
          cmake -E env protocol=ns ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test
          cmake -E env protocol=lt ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test

      - name: Upload regression test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Regression Test Results (${{ matrix.name }})
          path: ${{ env.test_path }}
