name: openDAQ regression tests

on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}] # Run every day at midnight
  push: # TODO: delete this before merge
    branches: [regression-tests]
  
env:
  target_tag: v3.0.0
  cmake_preset: regression_tests
  test_path: ${{ github.workspace }}/junit_reports/

jobs:
  regression_tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    # ${{ }} expression syntax because of leading '!'
    # if: ${{ ! github.event.pull_request.draft }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}-${{ matrix.name }}
      cancel-in-progress: true
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04 gcc-12 Release
            image: ubuntu:22.04
            cmake_generator: Ninja
            cmake_build_type: Release
            cmake_defines: -DOPENDAQ_ENABLE_REGRESSION_TESTS=ON
            apt_packages: g++-12
            cc: gcc-12
            cxx: g++-12
            cpack: DEB

    container:
      image: ${{ matrix.image }}
      env:
        TZ: Europe/Berlin
        DEBIAN_FRONTEND: noninteractive
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}

    steps:
      - name: Install basic dependencies
        run: |
          apt-get update
          apt-get install -y git openssh-client
          
      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends ${{ matrix.apt_packages }} \
            lld ninja-build curl \
            python3-dev python3-numpy python3-distutils python3-pip \
            mono-runtime libmono-system-json-microsoft4.0-cil libmono-system-data4.0-cil \
            libx11-dev libxcursor-dev libxrandr-dev libgl-dev libudev-dev libfreetype6-dev

      - name: Install latest CMake
        run: pip install cmake

      - name: Checkout target
        uses: actions/checkout@v3
        with:
          ref: ${{ env.target_tag }}
          path: target
          
      - name: Checkout current
        uses: actions/checkout@v3
        with:
          path: current
      
      # Because we need the regression_tests preset in target
      - name: Copy CMakePresets.json from current to target
        run: cp current/CMakePresets.json target
        
      # Because we need regression_simulator in target
      - name: Copy regression folder from current to target
        run: cp -r current/regression target/regression

      - name: Configure target
        working-directory: target
        run: |
          mkdir build
          cd build
          cmake -G ${{ matrix.cmake_generator }} --preset ${{ env.cmake_preset }} ${{ matrix.cmake_defines }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} ..

      - name: Configure current
        working-directory: current
        run: |
          mkdir build
          cd build
          cmake -G ${{ matrix.cmake_generator }} --preset ${{ env.cmake_preset }} ${{ matrix.cmake_defines }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} ..

      - name: Build target
        working-directory: target/build
        run: cmake --build .
        
      - name: Upload target bin.zip
        uses: actions/upload-artifact@v3
        with: 
          name: target bin (${{ matrix.name }})
          path: target/build/bin

      - name: Build current
        working-directory: current/build
        run: cmake --build .

      - name: OPC UA - Run simulator from target and perform regression tests from current
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_opcua"
        run: |
          ./target/build/bin/regression_simulator &
          sleep 5
          cmake -E env protocol=opcua ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"
          pkill regression_simulator
          
      - name: ND - Run simulator from target and perform regression tests from current
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_nd"
        run: |
          ./target/build/bin/regression_simulator &
          sleep 5
          cmake -E env protocol=nd ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"
          pkill regression_simulator
          
      - name: NS - Run simulator from target and perform regression tests from current
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_ns"
        run: |
          ./target/build/bin/regression_simulator &
          sleep 5
          cmake -E env protocol=ns ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"
          pkill regression_simulator
          
      - name: LT - Run simulator from target and perform regression tests from current
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_lt"
        run: |
          ./target/build/bin/regression_simulator &
          sleep 5
          cmake -E env protocol=lt ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"
          pkill regression_simulator

      # TODO: delete this
      - name: test1 (don't pkill)
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_test1"
        run: |
          ./target/build/bin/regression_simulator &
          sleep 5
          cmake -E env protocol=lt ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"

      # TODO: delete this
      - name: test2 (does it persist?)
        env:
          GTEST_OUTPUT: "xml:${{ env.test_path }}/regression_test2"
        run: |
          cmake -E env protocol=lt ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir current/build --gtest_output="xml:${{ env.test_path }}"

      - name: Upload regression test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Regression Test Results (${{ matrix.name }})
          path: ${{ env.test_path }}
