name: GitHub documentation deploy

on:
  push:
    branches:
      - 'main'
      - 'release/**'

  workflow_dispatch:

jobs:
  deploy_github_docs:
    runs-on: ubuntu-22.04
    name: Trigger Github documentation deployment
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PIPELINES_PAT }}
          repository: openDAQ/opendaq.github.io
          event-type: deploy-docs
