name: GitHub downstream deploy

on:
  push:
    branches:
      - 'main'
      - 'release/**'

  workflow_dispatch:

jobs:
  deploy_github_docs:
    runs-on: ubuntu-22.04
    name: Trigger Github documentation deployment
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PIPELINES_PAT }}
          repository: openDAQ/opendaq.github.io
          event-type: deploy-docs
          
  trigger_changelog_notifications:
    runs-on: ubuntu-22.04
    name: Trigger changelog notifications
    steps:
      - name: Checkout openDAQ repository
        uses: actions/checkout@v4

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Check for changelog changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changelog:
              - 'changelog/**'

      - name: Check for pat availability
        id: check-pat
        env:
          PAT_TOKEN: ${{ secrets.PIPELINES_PAT }}
        run: echo "pat_available=${{ env.PAT_TOKEN != '' }}" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        if: steps.check-pat.outputs.pat_available == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PIPELINES_PAT }}
          repository: openDAQ/openDAQ-Pipelines
          event-type: trigger-webhook
          client-payload: '{"current_branch": "${{ steps.branch-name.outputs.current_branch }}", "changelog-modified": "${{ steps.changes.outputs.changelog }}", "github": ${{ toJson(github) }}}'